### ISSUE TITLE
CCServer spontaneously freezes and holds CPU 100%

### ISSUE THREAD

**Issue by rekonnected** [Bendr0id/xmrigCC#10]
This only happens for me on a 512MB DO VPS running Ubuntu 16.04 ~~with CC version 1.2.2. 1.2.1 does not have this issue, so I reverted to that version, which I had saved.~~ UPDATE: Even after reverting to version 1.2.1, the issue persists for some reason. Included is a 24hr graph of CPU/Memory usage (memory will be flaky, enabled 4GB Swap. CPU is the important one.)
![image](https://user-images.githubusercontent.com/31298266/34327377-cc70395e-e890-11e7-8579-ff62315d8336.png)

The CPU Spike is when the dashboard dies, and the dip is when I manually kill and reload it (Ctrl+C, then ./xmrigCCServer). Memory is all over the place thanks to swap.

**Comment by Bendr0id** [comment]
Thanks for updating this ticket. Good to know that is not related to the fix of the memory leak. 
But for me it is still not reproducable. 
I'm hosting XMRigCCServer for 10 miners on a RaspberryPi.
I need some more details, how much miners are connected, is the update interval im config.json changed to something lower then 10? Is it stopping always after same amount of hours? Does it recover after some time? Is this the only service running on that vps? Could it be that the host does some strange things?

**Comment by rekonnected** [comment]
Alright, so I actually have a ton of miners. I've migrated my personal swarm of rigs to this, so I've actually got ~300 miners. Average update interval is at 15, never recovers. It might be the number of miners.

**Comment by Bendr0id** [comment]
Hmm, could have different root causes, could be for example a dead lock, which of course has higher chance to occur with more miners. I'll try to simulate that amount miners on may raspberry to debug.

Is it solved by moving the dashboard to a more powerful machine, or does the same problem exist there?

**Comment by rekonnected** [comment]
Haven't tried that. I'll temporarily upgrade the VPS.

**Comment by Bendr0id** [comment]
If you have telegram: @bendr0id

**Comment by Bendr0id** [comment]
any new infos so far?

**Comment by rekonnected** [comment]
Sorry, been busy. Haven't done anything yet. Will have info tonight.

**Comment by rekonnected** [comment]
At 4:52 AM EST, the CPU spiked again and held, but this time only at ~50%. The VPS was upgraded to a 2GB 2Core, so this shows that the program is only using a single core. However, instead of completely stopping the CC Servers' web access by giving a 'Connection Refused' error, now the URL delivers the 'Please Configure a Dashboard' page built-into the server. 

At this time, the network bandwidth used also was cut in half, although it was minimal to begin with. (0.16 Mbps > 0.6 Mbps.) The processes list shows that the CC Server is still holding the CPU. I am not able to find a log file, although one is defined (log.txt) in the config_cc.json file.

So far the only fix, albeit temporary, is to reload the CC Server, which resets any data collected, such as offline miners, etc.
