### ISSUE TITLE
1.6.0 - 1.6.1 windows 32bit version

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#101]
Hello, is possible to have the windows 32bit version binaries download?

Regards

**Comment by Bendr0id** [comment]
Will do later today a full release, including 32bit binaries. I finally fixed the 32bit issues.

**Comment by MrCook1es** [comment]
1.6.2 beta, on win32 build.
On top of the web page it says: "Update! XMRigCC v1.5.5 is available for download"
But in the xmrigCCServer.exeinterface i see version 1.6.2

**Comment by Bendr0id** [comment]
Released.

**Comment by Bendr0id** [comment]
Reload the page

Am 19.04.2018 18:06 schrieb MrCook1es <notifications@github.com>:

1.6.2 beta, on win32 build.
On top of the web page it says: "Update! XMRigCC v1.5.5 is available for download"
But in the xmrigCCServer.exeinterface i see version 1.6.2
