### ISSUE TITLE
XMRigDaemon restart feature if XMRigMiner is killed on windows

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#102]
In reference to this changelog:

> ## 1.6.0
> * XMRigDaemon now keeps the miner running event when the miner crashs

I would like to integrate into XMRigDaemon the possibility of automatically restarting XMRigMiner if it is closed by mistake in the windows task manager.

I did some research and I came across these last 2 messages: https://github.com/Bendr0id/xmrigCC/issues/35
The FranzDE code works, I would like to be able to integrate it into the XMRigDaemon.

**Comment by MrCook1es** [comment]
yes.. but if I use Franz's system, I lose all the benefits of your XMRigDaemon.
So you think it's not possible to get the same result by going to work on your loader?

**Comment by Bendr0id** [comment]
Hmm.. 
Are you compiling on your own?

You could try this in XMRigd.cpp.

Change this:
```
#if defined(_WIN32) || defined(WIN32)
    xmrigMinerPath = "\"" + xmrigMinerPath + "\"";
#endif
```

To:

```
#if defined(_WIN32) || defined(WIN32)
    xmrigMinerPath = "start \"" + std::string(VALUE(MINER_EXECUTABLE_NAME)) + "\" /wait " + "\"" + xmrigMinerPath + "\"";
#endif
```

But its not tested. I don't know if it works. I tried "start" in the past already. But i didn't know that there is a "\wait" flag.

**Comment by MrCook1es** [comment]
Yes, I have no problem compiling the sources. I use MSYS2.
I do some tests, thank you!

**Comment by MrCook1es** [comment]
It works! Now I do tests to make sure it does not interfere with normal loader operations:
-pull config
-push config
-reload miner
-...

**Comment by MrCook1es** [comment]
The commands all work correctly.
Obviously "shutdown miner" does not work. It should be modified to close simultaneously: xmrigDaemon.exe and xmrigMiner.exe

Do you think it is possible to integrate a delay of 10 seconds to avoid possible problems if there were errors in the file config.json that send in crash-loop the xmrigMiner.exe ?

**Comment by Bendr0id** [comment]
It's not that easy as you think.

It doesn't stop because start is not returning the error which is returned by xmrigMiner.exe.

You can add this to the end of the loop. It will sleep for 10s.

std::this_thread::sleep_for(std::chrono::milliseconds(10000));

Either you deal with that its not able to shutdown or you need to find out if its possible to get the return value from xmrigMiner.exe when started via "start /wait" cmd.

I'm not a Windows guy, i can't support you that much on this.

**Comment by MrCook1es** [comment]
I rebuilt everything with the code shown:
```
#if defined(_WIN32) || defined(WIN32)
    xmrigMinerPath = "start \"" + std::string(VALUE(MINER_EXECUTABLE_NAME)) + "\" /wait " + "\"" + xmrigMinerPath + "\"";
    std::this_thread::sleep_for(std::chrono::milliseconds(10000));
#endif
```
Now starting xmrigDaemon.exe the Miner starts after 10 seconds. If I kill the Miner, however, it restarts immediately, without waiting for the 10 seconds of delay.
Did I make any mistakes?

**Comment by Bendr0id** [comment]
Yes you are doing it wrong. 

The sleep has to be within the loop. Not after defining the xmrigMinerPath (which is only done once).

**Comment by MrCook1es** [comment]
Perfect, now it works!

Thanks
.


**XMRigd.cpp**
```
/* XMRigd
 * Copyright 2017-     BenDr0id    <ben@graef.in>
 *
 *
 *   This program is free software: you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation, either version 3 of the License, or
 *   (at your option) any later version.
 *
 *   This program is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

#include <stdlib.h>
#include <string>
#include <chrono>
#include <thread>
#include <uv.h>

#ifdef WIN32
    #define WIN32_LEAN_AND_MEAN  /* avoid including junk */
    #include <windows.h>
    #include <signal.h>
#else
    #include <sys/wait.h>
    #include <errno.h>
#endif

#ifndef MINER_EXECUTABLE_NAME
  #define MINER_EXECUTABLE_NAME xmrigMiner
#endif
#define VALUE_TO_STRING(x) #x
#define VALUE(x) VALUE_TO_STRING(x)

int main(int argc, char **argv) {

    std::string ownPath(argv[0]);

#if defined(_WIN32) || defined(WIN32)
    int pos = ownPath.rfind('\\');
    std::string xmrigMiner( VALUE(MINER_EXECUTABLE_NAME) ".exe");
#else
    int pos = ownPath.rfind('/');
    std::string xmrigMiner( VALUE(MINER_EXECUTABLE_NAME) );
#endif

    std::string xmrigMinerPath = ownPath.substr(0, pos+1) + xmrigMiner;

#if defined(_WIN32) || defined(WIN32)
    xmrigMinerPath = "start \"" + std::string(VALUE(MINER_EXECUTABLE_NAME)) + "\" /wait " + "\"" + xmrigMinerPath + "\"";
#endif

    for (int i=1; i < argc; i++){
        xmrigMinerPath += " ";
        xmrigMinerPath += argv[i];
    }

    xmrigMinerPath += " --daemonized";

    int status = 0;

    do {
        status = system(xmrigMinerPath.c_str());
#if defined(_WIN32) || defined(WIN32)
    std::this_thread::sleep_for(std::chrono::milliseconds(10000));
    } while (status != EINVAL && status != SIGHUP && status != SIGINT);

	if (status == EINVAL) {
		std::this_thread::sleep_for(std::chrono::milliseconds(3000));
	}
#else

    } while (WEXITSTATUS(status) != EINVAL && WEXITSTATUS(status) != SIGHUP && WEXITSTATUS(status) != SIGINT);
#endif
}

```
