### ISSUE TITLE
questions about parameter reloading and nvidia version

### ISSUE THREAD

**Issue by aleqx** [Bendr0id/xmrigCC#109]
Does your fork support reloading parameters such as `threads` and `blocks` without restarting the xmrig miner?

If yes, any plans to port your changes to the `xmrig-nvidia` branch as well? Would be pretty cool.

**Comment by Bendr0id** [comment]
Hey @aleqx,

no its not implemented yet. I'm currently finishing the support of the latest algo variants (xao/xtl) and my plan was to focus on numa support. After that the plan is to look into nvidia/amd gpu support.
