### ISSUE TITLE
Something weired happened with "xmrigMiner" between 1.1.1 and 1.2.0

### ISSUE THREAD

**Issue by advholder** [Bendr0id/xmrigCC#11]
Problem: xmrigDaemon.exe won't start miner on some computers (Win7x64). Just did not show anything in console (nor error neither warnings appeared and logfile is empty) until "xmrigMiner.exe" was downgraded to v.1.1.1
I've looked over all versions of the last release (mvc/gcc, x84/x64) with no success.
p.s. All MS Visual C++ libraries are installed, both x86 and x64 versions (afaik it has no matter with "gcc" version of miner).
p.p.s. I've tested a few last releases of xmrig  - it works fine on the same computers.

**Comment by Bendr0id** [comment]
You're right. Every version 1.2.0+ is effected. Currently don't know the reason, there is no error. It just dont start. Could be related to the memory management changes or the double hash mode changes. No real clue so far. Hope to fix this soon.

**Comment by Bendr0id** [comment]
I think it wasn't related to Windows 7. The problem was in AV=3 and AV=4 mode. 

Could it be that you tried to run on a CPU which doesnt have AES-NI support?

Should be fixed now. Could you please try it out and give feedback?

https://ci.appveyor.com/project/Bendr0id/xmrigcc/build/artifacts

Thanks in advance,

**Comment by advholder** [comment]
Just tested fresh build on 2 PCs (Core2Duo E7300 and Core i7 2600k) - no any signs of malfunction.
I am very grateful to you for your quick and efficient work.

**Comment by Bendr0id** [comment]
Thanks, will put that fix the the next official release aswell.
