### ISSUE TITLE
xmrigCCServer occasionally shows "HTTP_METHOD_NOT_ALOWED"

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#111]
hello, about every 15 or 20 minutes, the "xmrigCCServer.exe" program shows the message "HTTP_METHOD_NOT_ALOWED".

what does it mean?

note:
- I have 20 miner's
- I'm using lateste version: xmrigCCServer 1.6.2

![http_method_not_alowed](https://user-images.githubusercontent.com/38523505/39858792-e8603020-5437-11e8-9aee-4065e9f541f3.jpg)

**Comment by Bendr0id** [comment]
Are you running cc server on a common port? 80, 443 or something like that? Could be that it is a network scan. I also have that several times a day. Nothing to worry about.

Am 10.05.2018 13:12 schrieb MrCook1es <notifications@github.com>:

hello, about every 15 or 20 minutes, the "xmrigCCServer.exe" program shows the message "HTTP_METHOD_NOT_ALOWED".

what does it mean?

[http_method_not_alowed]<https://user-images.githubusercontent.com/38523505/39858792-e8603020-5437-11e8-9aee-4065e9f541f3.jpg>

**Comment by Bendr0id** [comment]
I think its more related to some network scans. Nothing to worry about.
