### ISSUE TITLE
Web interfcae not loading any miners!

### ISSUE THREAD

**Issue by Abulhallaj** [Bendr0id/xmrigCC#113]
Hey guys

I am testing your version and no miner loaded in web interface, is there any way to check that?

**Comment by Bendr0id** [comment]
Do you maybe opened the index.html file instead of browsing to you xmrigCCServer?

Am 20.05.2018 08:32 schrieb Abulhallaj <notifications@github.com>:

Hey guys

I am testing your version and no miner loaded in web interface, is there any way to check that?

**Comment by Abulhallaj** [comment]
Yes, it's my mistake _(or lake of documentation!)_

Thanks, it's working well by browsing CC address.

**Comment by Bendr0id** [comment]
Just for your info. The whole documentation is available in the wiki.

For example:

https://github.com/Bendr0id/xmrigCC/wiki/XMRigCCServer-Dashboard

Best,
Ben

Am 20.05.2018 19:14 schrieb Abulhallaj <notifications@github.com>:

Closed #113<https://github.com/Bendr0id/xmrigCC/issues/113>.
