### ISSUE TITLE
(Feature request) Display xmrigMiner version of workers on http

### ISSUE THREAD

**Issue by bobbieltd** [Bendr0id/xmrigCC#115]
Because the config can evolve (for example force pow or cryptonight-light-ipbc will be deprecated) and new algos can be added. It will be useful if we can know what version workers are running so we don’t push wrong config or we know that we need to update which workers’ software to mine new algos.

**Comment by Bendr0id** [comment]
Just hover over the client id, the Popup contains the version of the miner.
