### ISSUE TITLE
Show POW in dashboard

### ISSUE THREAD

**Issue by djfinch** [Bendr0id/xmrigCC#116]
Not issue but improvement.

Image is more than thousand words...
![image](https://user-images.githubusercontent.com/13107713/40555616-faaa60ca-6049-11e8-9818-9cd92d7b2a2e.png)

**Comment by Bendr0id** [comment]
Good point. Will do it

Am 25.05.2018 18:33 schrieb djfinch <notifications@github.com>:

Not issue but improvement.

Image is more than thousand words...
[image]<https://user-images.githubusercontent.com/13107713/40555616-faaa60ca-6049-11e8-9818-9cd92d7b2a2e.png>

**Comment by Bendr0id** [comment]
Integrated in master with #130
