### ISSUE TITLE
Vs 2017  compile error

### ISSUE THREAD

**Issue by echotxl** [Bendr0id/xmrigCC#117]
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(82): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(87): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(88): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(89): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(91): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(92): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(93): warning C4267: “参数”: 从“size_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\cpp-httplib\httplib.h(1188): warning C4244: “参数”: 从“socket_t”转换到“int”，可能丢失数据
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\cpp-httplib\httplib.h(1279): note: 参见对正在编译的函数 模板 实例化“bool httplib::detail::read_and_close_socket_ssl<int(__cdecl *)(SSL *),httplib::SSLServer::read_and_close_socket::<lambda_a033f2a4f5017a25ae083f4966b00ef9>,httplib::SSLServer::read_and_close_socket::<lambda_029f34d03494b23856466666805e1a1d>>(socket_t,SSL_CTX *,U,V,T)”的引用
11>        with
11>        [
11>            U=int (__cdecl *)(SSL *),
11>            V=httplib::SSLServer::read_and_close_socket::<lambda_a033f2a4f5017a25ae083f4966b00ef9>,
11>            T=httplib::SSLServer::read_and_close_socket::<lambda_029f34d03494b23856466666805e1a1d>
11>        ]
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\prettywriter.h(225): warning C4390: “;”: 找到空的受控语句；这是否是有意的?
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\prettywriter.h(190): note: 编译 类 模板 成员函数 "void rapidjson::PrettyWriter<rapidjson::StringBuffer,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>::PrettyPrefix(rapidjson::Type)" 时
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\prettywriter.h(144): note: 参见对正在编译的函数 模板 实例化“void rapidjson::PrettyWriter<rapidjson::StringBuffer,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>::PrettyPrefix(rapidjson::Type)”的引用
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\cc\ccclient.cpp(204): note: 参见对正在编译的 类 模板 实例化 "rapidjson::PrettyWriter<rapidjson::StringBuffer,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>" 的引用
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\writer.h(448): warning C4390: “;”: 找到空的受控语句；这是否是有意的?
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\writer.h(437): note: 编译 类 模板 成员函数 "void rapidjson::Writer<rapidjson::StringBuffer,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>::Prefix(rapidjson::Type)" 时
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\writer.h(221): note: 参见对正在编译的函数 模板 实例化“void rapidjson::Writer<rapidjson::StringBuffer,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>::Prefix(rapidjson::Type)”的引用
11>c:\users\administrator\desktop\xmrigcc-1.6.3\src\3rdparty\rapidjson\writer.h(478): note: 参见对正在编译的 类 模板 实例化 "rapidjson::Writer<rapidjson::StringBuffer,rapidjson::UTF8<char>,rapidjson::UTF8<char>,rapidjson::CrtAllocator,0>" 的引用
11>cl : 命令行 warning D9002: 忽略未知选项“-fexceptions”
11>c_keccak.c
11>c_groestl.c
11>c_blake256.c
11>c_jh.c
11>c_skein.c
11>NetworkState.obj : 找到 MSIL .netmodule 或使用 /GL 编译的模块；正在使用 /LTCG 重新启动链接；将 /LTCG 添加到链接命令行以改进链接器性能
11>LINK : fatal error C1007: 无法识别的标志“-Ot”(在“p2”中)
11>LINK : fatal error LNK1257: 代码生成失败
11>已完成生成项目“xmrigMiner.vcxproj”的操作 - 失败。
12>------ 已启动生成: 项目: ALL_BUILD, 配置: Release x64 ------
12>Building Custom Rule C:/Users/Administrator/Desktop/xmrigCC-1.6.3/CMakeLists.txt
12>CMake does not need to re-run because C:/Users/Administrator/Desktop/xmrigCC-1.6.3/CMakeFiles/generate.stamp is up-to-date.
========== 生成: 成功 10 个，失败 2 个，最新 0 个，跳过 0 个 ==========
`
VS 2017 link errr

11>LINK : fatal error C1007: 无法识别的标志“-Ot”(在“p2”中)
11>LINK : fatal error LNK1257: 代码生成失败

how to ? thank s

**Comment by Bendr0id** [comment]
This is not an issue, seems that you don't follow the guide.

https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows#microsoft-visual-studio-2017

"Make sure you have the latest CMake (3.11+) and a clean builder and make sure you use the latest xmrigCC-deps (v2)

If you have compile issues saying that the any of the used libraries is incompatible, either update your Visual Studio or use the xmrigCC-deps (v1)."

**Comment by echotxl** [comment]
maybe my Vs2017 is not the lastest ,now i am update my vs2017,then build it again..i will back soon

**Comment by echotxl** [comment]
i use xmrigCC-deps (v2),but vs2017 is not the lastest

**Comment by Bendr0id** [comment]
When you're using the latest vs2017you need to use the deps-v2 package. Otherwise you need the deps-v1 package. They are not compatible.

Am 25.05.2018 20:37 schrieb echotxl <notifications@github.com>:

maybe my Vs2017 is not the lastest ,now i am update my vs2017,then build it again..i will back soon

**Comment by Bendr0id** [comment]
Yeah then this is the issue.

Am 25.05.2018 20:39 schrieb echotxl <notifications@github.com>:

i use xmrigCC-deps (v2),but vs2017 is not the lastest

**Comment by echotxl** [comment]
errors have been killed ,thanks

**Comment by Bendr0id** [comment]
You're most welcome. Thanks for donating.

Am 25.05.2018 20:47 schrieb echotxl <notifications@github.com>:

errors have been killed ,thanks

**Comment by echotxl** [comment]
hi,my friend ,this is you XMR  account?: 4BEn3sSa2SsHBcwa9dNdKnGvvbyHPABr2JzoY7omn7DA2hPv84pVFvwDrcwMCWgz3dQVcrkw3gE9aTC9Mi5HxzkfF9ev1eH

i will send you some xmr coin ,the wallet is syn ing..

**Comment by Bendr0id** [comment]
Yes it is. Appreciate!

Am 25.05.2018 21:08 schrieb echotxl <notifications@github.com>:

hi,my friend ,this is you XMR account?: 4BEn3sSa2SsHBcwa9dNdKnGvvbyHPABr2JzoY7omn7DA2hPv84pVFvwDrcwMCWgz3dQVcrkw3gE9aTC9Mi5HxzkfF9ev1eH

i will send you some xmr coin ,the wallet is syn ing..
