### ISSUE TITLE
Multi Miner with same Miner ID

### ISSUE THREAD

**Issue by queenofwhales** [Bendr0id/xmrigCC#118]
If I have 10 PC with same Miner ID then the dashboard only show the last hash from one of those miner.
Is it possible to show total hash of all miner that use same Miner ID ?

**Comment by queenofwhales** [comment]
Hi, thank you.

I found the way to make random id for each miner.

**Comment by SecKiller** [comment]
i have suggest for you already tested with xmrig miner if you use one line command line 
you can fetch some parameter from the set Variable Environment of the system 

Like :  

xmrigxCCMiner.exe -a cryptonight -o stratum+tcp://Pool:Port -u $(echo -u (%COMPUTERNAME%)-(CPU:%NUMBER_OF_PROCESSORS%) -p x 

Already tested but if you use one line cmd it wont work on the jason.conf 

Good Luk
