### ISSUE TITLE
xmrigMiner Multi Name

### ISSUE THREAD

**Issue by SecKiller** [Bendr0id/xmrigCC#120]
Hi
First thank you for this big job, really it's amazing Project

My question is how i can change the xmrigMiner.exe  name, because when i change it the xmrigDaemon.exe  don't recognize the new miner name and the mining wont start 

Sincerely,

**Comment by djfinch** [comment]
@SecKiller https://github.com/Bendr0id/xmrigCC/blob/master/CMakeLists.txt#L14

**Comment by SecKiller** [comment]
@djfinch   Yes i already changed all the variable named xmrigMiner  on the as mentioned,

but can you just tell me how i can compile the all code for windows platform from my ubuntu PC please

i'm just beginner on this area :$  

Thank you in advance Dude

**Comment by SecKiller** [comment]
i'm using the CmakeGui for windows but i got this errors when i try to compile the code 

CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find UV (missing: UV_LIBRARY UV_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.11/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindUV.cmake:8 (find_package_handle_standard_args)
  CMakeLists.txt:121 (find_package)

Any idea Please ?

**Comment by djfinch** [comment]
Missing dependencies. Download them here : https://github.com/Bendr0id/xmrigCC-deps and follow instructions here : https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows. Are you trying to compile Win version on Linux? This will not work. In case you're running Ubuntu, then you have to follow Ubuntu instructions...

**Comment by SecKiller** [comment]
Thank you for response no now i just setup the CmakeGui on windows to compile my windows version i read that on some forum thank you for confirming this :)

i will follow the Instruction you sent to me , 

Thank you again Dude for your Valued Help

**Comment by Bendr0id** [comment]
@SecKiller also when changing the CMakeList.txt file, always make sure that you delete the CMakeCache.txt file every time. Otherwise it could contain outdated configurations.

**Comment by SecKiller** [comment]
@Bendr0id  

Thank you for Pointing me on this , sure i will 

Thank you again

**Comment by SecKiller** [comment]
Hi again 

i made all as explained but when i'm on the steps make -j i got this error 

NB: i got the to exe compiled on my XmrigCC directory 

xmrigCCServer.exe
xmrigDaemon.exe

But not the xmrigminer 

`[ 87%] Linking CXX executable xmrigCCServer.exe
[ 89%] Building CXX object CMakeFiles/xmrigMiner.dir/src/xmrig.cpp.obj
[ 89%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_keccak.c.obj
[ 91%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_blake256.c.obj
[ 92%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_jh.c.obj
[ 93%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_groestl.c.obj
[ 94%] Building CXX object CMakeFiles/xmrigMiner.dir/src/cc/CCClient.cpp.obj
make[2]: *** No rule to make target 'C:\local\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a', needed by 'xmrigMiner.exe'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 96%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_skein.c.obj
[ 97%] Building CXX object CMakeFiles/xmrigMiner.dir/src/crypto/CryptoNight.cpp.obj
[ 98%] Building RC object CMakeFiles/xmrigMiner.dir/res/app.rc.obj
In file included from C:/Xmrig/src/cc/CCClient.h:33:0,
                 from C:/Xmrig/src/workers/Workers.cpp:26:
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h: In instantiation of 'socket_t httplib::detail::create_socket(const char*, int, Fn, int) [with Fn = httplib::detail::create_server_socket(const char*, int, int)::<lambda(socket_t, addrinfo&)>; socket_t = int]':
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:390:20:   required from here
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:352:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        if (sock == -1) {
            ~~~~~^~~~~
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h: In instantiation of 'socket_t httplib::detail::create_socket(const char*, int, Fn, int) [with Fn = httplib::detail::create_client_socket(const char*, int)::<lambda(socket_t, addrinfo&)>; socket_t = int]':
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:400:6:   required from here
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:352:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
[ 98%] Built target xmrigCCServer
In file included from C:/Xmrig/src/cc/CCClient.h:33:0,
                 from C:/Xmrig/src/cc/CCClient.cpp:32:
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h: In instantiation of 'socket_t httplib::detail::create_socket(const char*, int, Fn, int) [with Fn = httplib::detail::create_server_socket(const char*, int, int)::<lambda(socket_t, addrinfo&)>; socket_t = int]':
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:390:20:   required from here
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:352:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
        if (sock == -1) {
            ~~~~~^~~~~
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h: In instantiation of 'socket_t httplib::detail::create_socket(const char*, int, Fn, int) [with Fn = httplib::detail::create_client_socket(const char*, int)::<lambda(socket_t, addrinfo&)>; socket_t = int]':
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:400:6:   required from here
C:/Xmrig/src/3rdparty/cpp-httplib/httplib.h:352:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

root@ns3094859 MINGW32 /c/Xmrig
`

**Comment by Bendr0id** [comment]
^ This log doesn't contain the error, only the result.

But it seems that it has problems to find the boost libraries.

```
make[2]: *** No rule to make target 'C:\local\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a', needed by 'xmrigMiner.exe'. Stop.
make[2]: *** Waiting for unfinished jobs....
```

**Comment by SecKiller** [comment]
Hi @Bendr0id   

👯‍♂️    i was stupid i put the wrong path, sorry 48h without sleep it's the reason lol :D

Now it's very ok i got the finally exe with the custom name i need thank you hundred time Dude

Hope for you nice day

**Comment by Bendr0id** [comment]
No worries, keep donating ;-)
