### ISSUE TITLE
integrate the jason.cong line to the XmrigCC source

### ISSUE THREAD

**Issue by SecKiller** [Bendr0id/xmrigCC#122]
Hi

Hope you have good day :)

i have question about if we can add the jason.conf line to the miner source code 

Sincerley,
Seckiller

**Comment by Bendr0id** [comment]
I don't understand what you mean. There is no jason.conf. If you mean the config, you can already run the daemon without a config file, you just need to add the config parameters to the command line.

And ofcouse you can hardcode them aswell, so what is the question?

**Comment by SecKiller** [comment]
hi 
sorry i think my question was not well formatted 

the idea is getting  the the final exe with those value integrated on it 

 "pools": [
        {
            "url": "Pool",
            "user": "Wallet",
            "pass": "x",

cc-client": {
        "url": "Address to the cc server ",
        "access-token": "acess token key",

i don't wont those info be on clear on command line or any other clear file :(

So if it's possible just tell me where i can edit Please

Thank you in Advance

**Comment by SecKiller** [comment]
i just found the line where i can insert the pool walet and pasword 

m_pools.push_back(new Url("pool.example.com", 3333, "WALLET", "PASSWORD"));

but the cc client i don't know where :s

**Comment by Bendr0id** [comment]
Just put it into options.cpp

Am 31.05.2018 15:26 schrieb SecKiller <notifications@github.com>:

hi
sorry i think my question was not well formatted

the idea is getting the the final exe with those value integrated on it

"pools": [
{
"url": "Pool",
"user": "Wallet",
"pass": "x",

cc-client": {
"url": "Address to the cc server ",
"access-token": "acess token key",

i don't wont those info be on clear on command line or any other clear file :(

So if it's possible just tell me where i can edit Please

Thank you in Advance

**Comment by SecKiller** [comment]
Thank you For your Valued help 

Have great Day  :)

**Comment by Bendr0id** [comment]
same way, in options.cpp

```
{
    m_pools.push_back(new Url("pool.example.com", 3333, "WALLET", "PASSWORD"));
    m_ccPort = 3344; // the port
    m_ccHost = "the host";
    m_ccToken = "the token";

   .... 
  
```

**Comment by SecKiller** [comment]
OMG i was just typing to ask about the line format :D you saved me Dude 

Really i don't know how to thank you 

Thank you again hundred time 

Respect
