### ISSUE TITLE
Please make xmrig-proxyCC

### ISSUE THREAD

**Issue by snipeTR** [Bendr0id/xmrigCC#123]
Nice idea. Right?

**Comment by ORGaniZMo** [comment]
for what?

**Comment by snipeTR** [comment]
Worker tracking.
I do not want to use xmrigcc. and for people using a proxy.

**Comment by djfinch** [comment]
I'm using xmrigCC togerher with XNP MoneroOcean version without any
problems. What's the advantage od this?

Dne ne 3. 6. 2018 12:35 uživatel snipeTR <notifications@github.com> napsal:

**Comment by ORGaniZMo** [comment]
> I do not want to use xmrigcc

use xmrig-proxy

**Comment by Bendr0id** [comment]
There will be an integration of the *ses-proxy* created by @sebastianstolzenberg 
It includes:

* Dynamic balancing between coins/pools based on weight
* Dynamic coin/job allocation based on miner capabilities on the same PORT
* Dynamic DIFF and share validation
* Full XMRigCC dashboard integration including features like remote proxy config changes
* Full SSL/TLS
* Much more
