### ISSUE TITLE
CMake Error at CMakeLists.txt:21 (include):   include could not find load file:      cmake/cpu.cmake

### ISSUE THREAD

**Issue by lost-bro** [Bendr0id/xmrigCC#125]
Good day,
I have included the output from VS console.  I have checked all paths and instruction sets, everything seems to be in it's correct place.  Just to double check my system, I compiled from source the Xmrig 2.6.2 from source off of Github.  It worked fine......... no fatal errors only some warnings as usual.

I tried this 3 times now and get the exact same results.  The commands are exactly the same as you used @ https://ci.appveyor.com/project/Bendr0id/xmrigcc/build/1.6.3.

I set cmake w/ "set CMAKE_PREFIX_PATH=c:\xmrigCC-deps\msvc2017\libuv\x64\;c:\xmrigCC-deps\msvc2017\libmicrohttpd\x64\;c:\xmrigCC-deps\msvc2017\openssl\x64\"

"C:\xmrigCC-deps" is the correct location on my C drive.

I would appreciate help, I am probably overlooking something simple here, but I can't see it.

Here is the CMakeOutput.log
[CMakeOutput.log](https://github.com/Bendr0id/xmrigCC/files/2070152/CMakeOutput.log)

Thanks in advance.  mjd

***********************************************************************************
C:\xmrigCC\build>set CMAKE_PREFIX_PATH=c:\xmrigCC-deps\msvc2017\libuv\x64\;c:\xmrigCC-
deps\msvc2017\libmicrohttpd\x64\;c:\xmrigCC-deps\msvc2017\openssl\x64\

C:\xmrigCC\build>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DBOOST_ROOT=
C:\Boost\boost_1_67_0-msvc-14.1-64.exe
-- The C compiler identification is MSVC 19.14.26430.0
-- The CXX compiler identification is MSVC 19.14.26430.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/C
ommunity/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/C
ommunity/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017
/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017
/Community/VC/Tools/MSVC/14.14.26428/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:21 (include):
  include could not find load file:

    cmake/cpu.cmake

CMake Error at CMakeLists.txt:121 (find_package):
  By not providing "FindUV.cmake" in CMAKE_MODULE_PATH this project has asked
  CMake to find a package configuration file provided by "UV", but CMake did
  not find one.

  Could not find a package configuration file provided by "UV" with any of
  the following names:

    UVConfig.cmake
    uv-config.cmake

  Add the installation prefix of "UV" to CMAKE_PREFIX_PATH or set "UV_DIR" to
  a directory containing one of the above files.  If "UV" provides a separate
  development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "C:/xmrigCC/build/CMakeFiles/CMakeOutput.log".
*********************************************************************************

**Comment by Bendr0id** [comment]
Second thing is, seems that you removed the `cmake` folder within the xmrigCC folder. Because CMake is not able to find the files.

**Comment by lost-bro** [comment]
Good day Bendr0id
Thanks for the fast reply:  Yes, I caught the mistake w/ the Boost lib./ Boost Binary.  No, I did not remove the Cmake folder from root of xmrigCC folder.  It was there the entire time, that's what made wonder what was really happening. I will try the MSVC build again tomorrow when I get back home.  I managed to compile the x64 version w/ GCC/MSYS2....... it worked fine.  Now I want to compile the x86 version, so will give that a try next.  I will let you know how I make out with this. Thanks again, keep up the great work. Take care, peace lost_bro

**Comment by Bendr0id** [comment]
You need to build boost for 32 bit, like you did with 64bit.

Am 07.06.2018 07:22 schrieb lost-bro <notifications@github.com>:

Good day Bendr0id.
Well, just attempted to compile the x86 version w/ GccMSYS2 again. Here is the failed output:

Determining if the include file syslog.h exists failed with the following output:
Change Dir: C:/xmrigCC-master/CMakeFiles/CMakeTmp

Run Build Command:"C:/msys64/usr/bin/make.exe" "cmTC_2a93b/fast"
/usr/bin/make -f CMakeFiles/cmTC_2a93b.dir/build.make CMakeFiles/cmTC_2a93b.dir/build
make[1]: Entering directory '/c/xmrigCC-master/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2a93b.dir/CheckIncludeFile.c.obj

C:/msys64/mingw32/bin/cc.exe -Wall -Wno-strict-aliasing -maes -o CMakeFiles/cmTC_2a93b.dir/CheckIncludeFile.c.obj -c C:/xmrigCC-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c
C:/xmrigCC-master/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:10: fatal error: syslog.h: No such file or directory

#include <syslog.h>

      ^~~~~~~~~~


compilation terminated.

make[1]: *** [CMakeFiles/cmTC_2a93b.dir/build.make:66: CMakeFiles/cmTC_2a93b.dir/CheckIncludeFile.c.obj] Error 1
make[1]: Leaving directory '/c/xmrigCC-master/CMakeFiles/CMakeTmp'
make: *** [Makefile:126: cmTC_2a93b/fast] Error 2
.....................................................................................................

Ran it three times trying to find the error. Seems that it gets to the very end, ie: [100%] Linking CXX executable xmrigminer.exe, and then fails w/ 2 errors. The compiler outputs the CCserver.exe & the Daemon.exe. Only the miner is not completed.

________________________________

c:\msys64\home\lost_bro\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a(error_code.o):error_code.cpp:(.text+0xb7): undefined reference to __gxx_personality_sj0' c:\msys64\home\lost_bro\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a(error_code.o):error_code.cpp:(.text+0xcd): undefined reference to_Unwind_SjLj_Register'
c:\msys64\home\lost_bro\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a(error_code.o):error_code.cpp:(.text+0x161): undefined reference to _Unwind_SjLj_Unregister' c:\msys64\home\lost_bro\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a(error_code.o):error_code.cpp:(.text+0x31f): undefined reference to_Unwind_SjLj_Resume'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/xmrigminer.dir/build.make:497: xmrigminer.exe] Error 1
make[1]: *** [CMakeFiles/Makefile2:374: CMakeFiles/xmrigminer.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

________________________________

Checked and re-installed Boost again also, and got the same results.
Maybe you can recommend something.
Thanks in advance.
take care, peace

**Comment by lost-bro** [comment]
Good day Bendriod
Yes, I did build boost w/ MYSY2 using the MinGW 32bit.
I built w/o any problems.
I used the code directly off of your Github page to do the Boost 32bit build.
***************************
cmake . -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libuv\x86\include" -DUV_LIBRARY="c:\xmrigCC-deps\gcc\libuv\x86\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libmicrohttpd\x86\include" -DMHD_LIBRARY="c:\xmrigCC-deps\gcc\libmicrohttpd\x86\lib\libmicrohttpd.a" -DOPENSSL_INCLUDE_DIR="c:\xmrigCC-deps\gcc\openssl\x86\include" -DOPENSSL_ROOT_DIR="c:\xmrigCC-deps\gcc\openssl\x86\lib" -DBOOST_ROOT="c:\msys64\home\lost_bro\boost_1_67_0" -DBoost_SYSTEM_LIBRARY="c:\msys64\home\lost_bro\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a"

******************************************************

This command is identical to the x64 version command that I used which worked for the x64 build.
I don't see an issue w/ the 32bit command.
I am open to any sugguestions.
Thanks in advance.
mjd

**Comment by Bendr0id** [comment]
Does this problem persist?
