### ISSUE TITLE
delete button to remove from list disconnected miner's

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#129]
It will be great if you add a button that can delete an offline miner.
If I rename a miner, old name remains in the web page.

it is inconvenient to have to restart the program every time you want to clean up the miner database :(

**Comment by djfinch** [comment]
You can remove "minername.json" from CCServer basedir by hand...

**Comment by Bendr0id** [comment]
@djfinch i think you misunderstood the feature request. @MrCook1es will be in one of the next releases.

**Comment by Bendr0id** [comment]
Integrated into master

**Comment by realopty** [comment]
<3 thanks
