### ISSUE TITLE
x86 app

### ISSUE THREAD

**Issue by snipeTR** [Bendr0id/xmrigCC#13]
Hello there.
I like your product very much but I do not have 32 bit release. 32 bit release required. The computers I run are 32 bit. could you help with this?

**Comment by rekonnected** [comment]
The latest version (1.2.2) includes Win32 (x86) Binaries.

**Comment by Bendr0id** [comment]
@rekonnected that's right there is a x86 build. But that one is broken for CPU without AES-NI, which is I think the 99% use case for 32bit CPUs.

@snipeTR there will be a new release later today, containing a working 32bit Windows release.

**Comment by Bendr0id** [comment]
Release is out:
https://github.com/Bendr0id/xmrigCC/releases/download/1.3.0/xmrigCC-1.3.0-gcc-win32.zip
