### ISSUE TITLE
How to implement a non English version of the dashboard

### ISSUE THREAD

**Issue by strayapple** [Bendr0id/xmrigCC#135]
After i edit the text in index.html with non english characters,restarted xmrigCCServer,there will be some gibberish on the dashboard,these characters cannot be displayed normally.Index.html file is the utf8 format

**Comment by Bendr0id** [comment]
I know that there is an russian/cyrilic version of the Dashboard out there. 

You can find it here:
https://xmr.ru/threads/247/

So it must be a problem on your side, maybe you can use the russian one as a start.
