### ISSUE TITLE
Unable to compile on ARMV7

### ISSUE THREAD

**Issue by DarrenRainey** [Bendr0id/xmrigCC#136]
Here is the output log looks like a problem with the boost library but I have seen some errors relating to the xmrig source code. Any help trying to compile would be appreciated:

root@nanopineo-node-1:~/xmrigCC/new/xmrigCC-1.6.4# cmake . -DBOOST_ROOT=/root/xmrigCC/src/boost_1_67_0 -DWITH_HTTPD=OFF -DCMAKE_SYSTEM_PROCESSOR=armv7l -DWITH_CC_SERVER=OFF -DWITH_TLS=OFF
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found UV: /usr/local/lib/libuv.so
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmrigCC/new/xmrigCC-1.6.4
root@nanopineo-node-1:~/xmrigCC/new/xmrigCC-1.6.4# make -j 8
Scanning dependencies of target xmrig_os_dependencies
Scanning dependencies of target xmrig_common
Scanning dependencies of target xmrig_cc_common
Scanning dependencies of target xmrig_cpuid
Scanning dependencies of target xmrigDaemon
[  2%] [  6%] [  8%] [  8%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_arm.cpp.o
Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.o
Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
[ 13%] [ 15%] [ 17%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.o
Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.o
Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.o
Linking CXX static library libxmrig_cpuid.a
[ 19%] Built target xmrig_cpuid
[ 21%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.o
[ 23%] [ 26%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_unix.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.o
Linking CXX executable xmrigDaemon
[ 30%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o
[ 30%] Built target xmrigDaemon
[ 32%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_unix.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/log/SysLog.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/RemoteLog.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.o
Linking CXX static library libxmrig_os_dependencies.a
[ 45%] Built target xmrig_os_dependencies
Linking CXX static library libxmrig_cc_common.a
[ 45%] Built target xmrig_cc_common
Linking CXX static library libxmrig_common.a
[ 45%] Built target xmrig_common
Scanning dependencies of target xmrigMiner
[ 47%] [ 50%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.o
[ 52%] [ 54%] [ 56%] [ 58%] [ 60%] [ 63%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/BoostTcpConnection.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Job.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Connection.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/DonateStrategy.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Client.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Network.cpp.o
In file included from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/Client.cpp:38:0:
/root/xmrigCC/new/xmrigCC-1.6.4/src/net/JobResult.h: In member function 'uint64_t JobResult::actualDiff() const':
/root/xmrigCC/new/xmrigCC-1.6.4/src/net/JobResult.h:69:71: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
In file included from /root/xmrigCC/new/xmrigCC-1.6.4/src/workers/Workers.h:34:0,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/App.cpp:42:
/root/xmrigCC/new/xmrigCC-1.6.4/src/net/JobResult.h: In member function 'uint64_t JobResult::actualDiff() const':
/root/xmrigCC/new/xmrigCC-1.6.4/src/net/JobResult.h:69:71: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 67%] [ 67%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/SinglePoolStrategy.cpp.o
Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/SubmitResult.cpp.o
In file included from /root/xmrigCC/new/xmrigCC-1.6.4/src/workers/Workers.h:34:0,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/Network.cpp:46:
/root/xmrigCC/new/xmrigCC-1.6.4/src/net/JobResult.h: In member function 'uint64_t JobResult::actualDiff() const':
/root/xmrigCC/new/xmrigCC-1.6.4/src/net/JobResult.h:69:71: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
[ 71%] Building CXX object CMakeFiles/xmrigMiner.dir/src/Summary.cpp.o
/root/xmrigCC/new/xmrigCC-1.6.4/src/App.cpp: In static member function 'static void App::onCommandReceived(uv_async_t*)':
/root/xmrigCC/new/xmrigCC-1.6.4/src/App.cpp:272:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
c++: internal compiler error: Killed (program cc1plus)
libbacktrace could not find executable to open
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
CMakeFiles/xmrigMiner.dir/build.make:192: recipe for target 'CMakeFiles/xmrigMiner.dir/src/net/Network.cpp.o' failed
make[2]: *** [CMakeFiles/xmrigMiner.dir/src/net/Network.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In function 'void boost::asio::detail::promise_invoke_and_set(std::promise<T>&, F&, Args&& ...)':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:49:21: error: 'current_exception' is not a member of 'std'
     p.set_exception(std::current_exception());
                     ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In function 'void boost::asio::detail::promise_invoke_and_set(std::promise<void>&, F&, Args&& ...)':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:63:6: error: invalid use of incomplete type 'class std::promise<void>'
     p.set_value();
      ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:68:6: error: invalid use of incomplete type 'class std::promise<void>'
     p.set_exception(std::current_exception());
      ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:68:21: error: 'current_exception' is not a member of 'std'
     p.set_exception(std::current_exception());
                     ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In member function 'void boost::asio::detail::promise_invoker<T, F>::operator()()':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:193:25: error: 'current_exception' is not a member of 'std'
       p_->set_exception(std::current_exception());
                         ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In member function 'void boost::asio::detail::promise_handler_0::operator()()':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:295:13: error: invalid use of incomplete type 'class std::promise<void>'
     this->p_->set_value();
             ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In member function 'void boost::asio::detail::promise_handler_ec_0::operator()(const boost::system::error_code&)':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:308:15: error: invalid use of incomplete type 'class std::promise<void>'
       this->p_->set_exception(
               ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:309:11: error: 'make_exception_ptr' is not a member of 'std'
           std::make_exception_ptr(
           ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:314:15: error: invalid use of incomplete type 'class std::promise<void>'
       this->p_->set_value();
               ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: At global scope:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:324:30: error: 'exception_ptr' in namespace 'std' does not name a type
   void operator()(const std::exception_ptr& ex)
                              ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In member function 'void boost::asio::detail::promise_handler_ex_0::operator()(const int&)':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:328:15: error: invalid use of incomplete type 'class std::promise<void>'
       this->p_->set_exception(ex);
               ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:332:15: error: invalid use of incomplete type 'class std::promise<void>'
       this->p_->set_value();
               ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/packaged_task.hpp:23:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:101,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/usr/include/c++/4.9/future:123:11: error: declaration of 'class std::promise<void>'
     class promise;
           ^
In file included from /root/xmrigCC/src/boost_1_67_0/boost/asio/use_future.hpp:156:0,
                 from /root/xmrigCC/src/boost_1_67_0/boost/asio.hpp:131,
                 from /root/xmrigCC/new/xmrigCC-1.6.4/src/net/BoostTcpConnection.cpp:23:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In member function 'void boost::asio::detail::promise_handler_ec_1<T>::operator()(const boost::system::error_code&, Arg&&)':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:363:11: error: 'make_exception_ptr' is not a member of 'std'
           std::make_exception_ptr(
           ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: At global scope:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:378:30: error: 'exception_ptr' in namespace 'std' does not name a type
   void operator()(const std::exception_ptr& ex,
                              ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: In member function 'void boost::asio::detail::promise_handler_ec_n<T>::operator()(const boost::system::error_code&, Args&& ...)':
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:436:11: error: 'make_exception_ptr' is not a member of 'std'
           std::make_exception_ptr(
           ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp: At global scope:
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:483:30: error: 'exception_ptr' in namespace 'std' does not name a type
   void operator()(const std::exception_ptr& ex,
                              ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:532:37: error: 'exception_ptr' is not a member of 'std'
 class promise_handler_selector<void(std::exception_ptr)>
                                     ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:532:56: error: template argument 1 is invalid
 class promise_handler_selector<void(std::exception_ptr)>
                                                        ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:544:37: error: 'exception_ptr' is not a member of 'std'
 class promise_handler_selector<void(std::exception_ptr, Arg)>
                                     ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:544:61: error: template argument 1 is invalid
 class promise_handler_selector<void(std::exception_ptr, Arg)>
                                                             ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:558:37: error: 'exception_ptr' is not a member of 'std'
 class promise_handler_selector<void(std::exception_ptr, Arg...)>
                                     ^
/root/xmrigCC/src/boost_1_67_0/boost/asio/impl/use_future.hpp:558:64: error: template argument 1 is invalid
 class promise_handler_selector<void(std::exception_ptr, Arg...)>
                                                                ^
CMakeFiles/xmrigMiner.dir/build.make:100: recipe for target 'CMakeFiles/xmrigMiner.dir/src/net/BoostTcpConnection.cpp.o' failed
make[2]: *** [CMakeFiles/xmrigMiner.dir/src/net/BoostTcpConnection.cpp.o] Error 1
CMakeFiles/Makefile2:98: recipe for target 'CMakeFiles/xmrigMiner.dir/all' failed
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Bendr0id** [comment]
Hard for me to reproduce.. need to setup my rpi3.

**Comment by DarrenRainey** [comment]
Ok. I'm not sure what the problem is but looking around online this line "c++: internal compiler error: Killed (program cc1plus)" apparently means that the system ran out of memory (RAM) although I will need to test this on my more powerfully pi with 2GB of RAM

**Comment by Bendr0id** [comment]
Why not just add swap?

**Comment by DarrenRainey** [comment]
I've read somewhere that swap wasn't working for some reason but I'll have to test it out later

**Comment by Bendr0id** [comment]
Is there any new info? Otherwise it will be closed soon.
