### ISSUE TITLE
Compil Error on ubuntu Ubuntu 13.04

### ISSUE THREAD

**Issue by SecKiller** [Bendr0id/xmrigCC#137]
Hi 
Can you please tell me if you have any idea about the error below 
Thank you in advance 

`root@ns3292309:/sbin/sys/xmrigCC# cmake . -DBOOST_ROOT=/sbin/sys/boost_1_67_0
-- The C compiler identification is GNU 4.8.1
-- The CXX compiler identification is GNU 4.8.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/local/lib/libuv.so
CMake Warning at /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:801 (message):
  New Boost version may have incorrect or missing dependencies and imported
  targets
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:128 (find_package)

-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1c")
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found mhd: /usr/include
-- Configuring done
-- Generating done
-- Build files have been written to: /sbin/sys/xmrigCC
root@ns3292309:/sbin/sys/xmrigCC# make
Scanning dependencies of target xmrig_common
[  1%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
/sbin/sys/xmrigCC/src/log/FileLog.cpp: In member function ‘virtual void FileLog::message(int, const char*, __va_list_tag*)’:
/sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: error: no matching function for call to ‘regex_replace(std::string, std::regex, const char [1])’
     std::string row = std::regex_replace(std::string(buf, size+1), std::regex("\x1B\\[[0-9;]*[a-zA-Z]"), "");
                                                                                                            ^
/sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: note: candidates are:
In file included from /usr/include/c++/4.8/regex:62:0,
                 from /sbin/sys/xmrigCC/src/log/FileLog.cpp:25:
/usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
/sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
     std::string row = std::regex_replace(std::string(buf, size+1), std::regex("\x1B\\[[0-9;]*[a-zA-Z]"), "");
                                                                                                            ^
In file included from /usr/include/c++/4.8/regex:62:0,
                 from /sbin/sys/xmrigCC/src/log/FileLog.cpp:25:
/usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
/sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’
     std::string row = std::regex_replace(std::string(buf, size+1), std::regex("\x1B\\[[0-9;]*[a-zA-Z]"), "");
                                                                                                            ^
make[2]: *** [CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig_common.dir/all] Error 2
make: *** [all] Error 2
root@ns3292309:/sbin/sys/xmrigCC#

`

**Comment by Bendr0id** [comment]
Try to use newer gcc

Am 19.06.2018 02:16 schrieb SecKiller <notifications@github.com>:

Hi
Can you please tell me if you have any idea about the error below
Thank you in advance

/sbin/sys/xmrigCC/src/log/FileLog.cpp: In member function ‘virtual void FileLog::message(int, const char*, __va_list_tag*)’: /sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: error: no matching function for call to ‘regex_replace(std::string, std::regex, const char [1])’ std::string row = std::regex_replace(std::string(buf, size+1), std::regex("\x1B\\[[0-9;]*[a-zA-Z]"), ""); ^ /sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: note: candidates are: In file included from /usr/include/c++/4.8/regex:62:0, from /sbin/sys/xmrigCC/src/log/FileLog.cpp:25: /usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type) regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last, ^ /usr/include/c++/4.8/bits/regex.h:2162:5: note: template argument deduction/substitution failed: /sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: note: deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’) std::string row = std::regex_replace(std::string(buf, size+1), std::regex("\x1B\\[[0-9;]*[a-zA-Z]"), ""); ^ In file included from /usr/include/c++/4.8/regex:62:0, from /sbin/sys/xmrigCC/src/log/FileLog.cpp:25: /usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type) regex_replace(const basic_string<_Ch_type>& __s, ^ /usr/include/c++/4.8/bits/regex.h:2182:5: note: template argument deduction/substitution failed: /sbin/sys/xmrigCC/src/log/FileLog.cpp:71:108: note: mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [1]’ std::string row = std::regex_replace(std::string(buf, size+1), std::regex("\x1B\\[[0-9;]*[a-zA-Z]"), ""); ^ make[2]: *** [CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o] Error 1 make[1]: *** [CMakeFiles/xmrig_common.dir/all] Error 2 make: *** [all] Error 2

**Comment by Bendr0id** [comment]
Can this be closed?

**Comment by Bendr0id** [comment]
Is there any new info? Otherwise it will be closed soon.
