### ISSUE TITLE
Test Build OSX of branch mem_allocation_refactoring

### ISSUE THREAD

**Issue by Bendr0id** [Bendr0id/xmrigCC#138]
@djfinch Could you please make a OSX test build of the branch `mem_allocation_refactoring`.

I changed some stuff in the os dependend layer, but i don't have the possibility to test on OSX.

Appreciate your help.

**Comment by djfinch** [comment]
Hello Ben,

https://github.com/Bendr0id/xmrigCC/blob/mem_allocation_refactoring/src/Cpu_mac.cpp#L44
out-of-line definition of 'setAffinity' does not match any declaration in 'CpuImpl'
Fixed... #139 

Successfully compiled on:
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G19009

Thanks!

**Comment by Bendr0id** [comment]
Thank you very much!

**Comment by djfinch** [comment]
Hi Ben,

Just for the record. I have two testing instances running 1.6.5 for almost 3 days without any problems. Everything looks stable including failover switching.

![image](https://user-images.githubusercontent.com/13107713/41872232-80be8c88-78c1-11e8-9c42-06282fe13f94.png)
