### ISSUE TITLE
load default json

### ISSUE THREAD

**Issue by maxisvk** [Bendr0id/xmrigCC#14]
allow to start daemon with only cc options like this:
xmrigDaemon --cc-url=IP_OF_CC_SERVER:PORT --cc-access-token=SECRET_TOKEN_TO_ACCESS_CC_SERVER
and then download the default_config.json

**Comment by advholder** [comment]
It enough to use only "--cc-url=..." command line switch. When it starts on the first time xmrigDaemon reads "config.json" (NOT "default_config.json") file from directory where it resides, then duplicates all settings to "[worker-id]-config.json" file to use it afterwards.

**Comment by maxisvk** [comment]
Ok, but if I don't have any config.json in folder first time run deamon It exit becouse no pool set.
Maybe a switch to pass to daemon to force download config from server. Like --cc-dowload-config. Also if I setup deamon to start when pc boot it always use update config file from server.
Thanks

**Comment by Bendr0id** [comment]
Good idea. Have to think about it and howto integrate.

**Comment by advholder** [comment]
Well, now I understood you.
I'm using shared folders in my LAN to avoid deploying apps when it's possible, so I didn't encounter such difficulties as "how to aquire config file" and "how to upgrade app".

**Comment by rekonnected** [comment]
![dlconf](https://user-images.githubusercontent.com/31298266/34421198-e8e29624-ebdb-11e7-89d5-bfed0f803423.jpg)
The data flow would look something like this. You could possibly use it to get the latest Miner EXE as well, but that's a different idea.

**Comment by maxisvk** [comment]
Exactly!

**Comment by realopty** [comment]
Ive been thinking of the same thing. Would really like to see this feature.

**Comment by Bendr0id** [comment]
Implemented that already some days ago. Will be in my next commit.

Syntax is:

```
./xmrigDaemon --cc-url=localhost:3344 --cc-access-token=mySecret
```

It will connect to xmrigCCServer and will be visible in the dashboard. 
Yyou just need to edit the config on the dashboard (editor will be prefilled with content of default_config.json) and push it to the miner.

**Comment by rekonnected** [comment]
Maybe add a little indicator of sorts to show that it doesn't have config? Unless it's running on the default on startup.

**Comment by Bendr0id** [comment]
Is already merged to master. For the ones which compile on there own, just pull and make again. 
Windows and linux binaries will be compiled tomorow and i'll create release.
