### ISSUE TITLE
Send only Deltas of the log to the Server

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#143]
It seems like now cc server fetches last N rows of log every update regardless of log changes. And with very big N of rows that can eat considerable network bandwidth.

I think better solution is to fetch log data on demand and let user specify quantity of rows to fetch in webui. Or just fetch only new rows on log data update.

**Comment by Bendr0id** [comment]
The user can already define that.

See the wiki:

https://github.com/Bendr0id/xmrigCC/wiki/Config-XMRigDaemon

```
"cc-client": {
   ...
        "use-remote-logging" : true,                // enable remote logging on CC Server
        "remote-logging-max-rows" : 20          // maximum last n-log rows to send CC Server
   ...
}
```

**Comment by Bendr0id** [comment]
But thats not how it is designed or made for. It's a debugging tool for now. I'll think of a re-desing when i add persistance to the XMRigCCServer. Because right now when you would restart the server all logs would be gone.

**Comment by Bendr0id** [comment]
I'll put it on the roadmap. Good point!
