### ISSUE TITLE
1.6.5 Disregard

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#144]
Miner disregards cpu load limit.

PS: Pressed enter accidently

**Comment by Bendr0id** [comment]
Miner doesn't disregard the CPU limit. The CPU limit only works in auto mode. When you f.e. define threads on your own, you disable the auto configuration.

The CPU limit is not capping the % on each core.

See the documentation:

```
"max-cpu-usage": 100,                       // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.
```

**Comment by uz-spark** [comment]
"algo": "cryptonight",                      // cryptonight (default), cryptonight-lite or cryptonight-heavy
    "aesni": 0,                                 // selection of AES-NI mode (0 auto, 1 on, 2 off)
    "threads": 0,                               // number of miner threads (not set or 0 enables automatic selection of optimal thread count)
    "multihash-factor": 0,                      // number of hash blocks to process at a time (not set or 0 enables automatic selection of optimal number of hash blocks)
    "multihash-thread-mask" : null,             // for multihash-factors>0 only, limits multihash to given threads (mask), mask "0x3" means run multihash on thread 0 and 1 only (default: all threads)
    "pow-variant" : "auto",                     // specificy the PoW variat to use: -> auto (default), 0 (v0), 1 (v1, aka monerov7, aeonv7), ipbc (tube), alloy, xtl (including autodetect for v5)
                                                // for further help see: https://github.com/Bendr0id/xmrigCC/wiki/Coin-configurations
    "background": true,                        // true to run the miner in the background (Windows only, for *nix plase use screen/tmux or systemd service instead)
    "colors": true,                             // false to disable colored output
    "cpu-affinity": null,                       // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": 0,                       // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 1,                          // donate level, mininum 1%
    "log-file": null,                           // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 5,                       // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.
    "print-time": 600,                           // print hashrate report every N seconds
    "retries": 5,                               // number of times to retry before switch to backup server
    "retry-pause": 1,                           // time to pause between retries
    "safe": false,                              // true to safe adjust threads and av settings for current CPU
    "syslog": false,                            // use system log for output messages

**Comment by uz-spark** [comment]
Miner runs with that config, still 25% cpu load

**Comment by Bendr0id** [comment]
As I already said, this option doesn't cap the cpu load. It reduces the threads. 

Let's say you have a 4 core machine. If you put the max-cpu-usage to five it will run on 25%  because it's the next possible value. It will cap the process to run only on one of the 4 cores (25%) in this case. 

It's not possible to run on less cores than 1.

On a 10 core the minimum would be 10%, on a 20core 5%.

The minimum is always one thread.
