### ISSUE TITLE
Cannot build miner with API support

### ISSUE THREAD

**Issue by borodamd** [Bendr0id/xmrigCC#145]
I am trying to build on windows miner and daemon and get an error what api has not been declared:
Building without httpd support goes well.

Scanning dependencies of target xmrigMiner
[ 57%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.ob                                                                                                                                                                                               j
[ 58%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.obj
C:/msys64/home/user/xmrigCC/src/App.cpp: In member function 'int App::start()':
C:/msys64/home/user/xmrigCC/src/App.cpp:168:5: error: 'Api' has not been declar                                                                                                                                                                                               ed
     Api::start();
     ^~~
C:/msys64/home/user/xmrigCC/src/App.cpp: In static member function 'static void                                                                                                                                                                                                App::onCommandReceived(uv_async_t*)':
C:/msys64/home/user/xmrigCC/src/App.cpp:285:76: warning: dereferencing type-pun                                                                                                                                                                                               ned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
make[2]: *** [CMakeFiles/xmrigMiner.dir/build.make:78: CMakeFiles/xmrigMiner.dir                                                                                                                                                                                               /src/App.cpp.obj] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:258: CMakeFiles/xmrigMiner.dir/all] Ошибка 2
make: *** [Makefile:84: all] Ошибка 2

**Comment by borodamd** [comment]
Resolved.
I add to App.cpp string:
#include "api/Api.h"

and everything build well

**Comment by Bendr0id** [comment]
I added it in master as well. Thx
