### ISSUE TITLE
Invalid payment address provided when using supportxmr pool

### ISSUE THREAD

**Issue by fentensoft** [Bendr0id/xmrigCC#147]
The daemon keep showing "Invalid payment address provided". I've checked my wallet address and its right. This error only shows on supportxmr.com pool.

**Comment by Bendr0id** [comment]
This is not a miner issue. 

The error comes from the pool. Do you use payment Id and/or static diff? I'm using this pool aswell without a problem.

**Comment by fentensoft** [comment]
Well, I found what's wrong with my configuration.

I copied the wallet address from another terminal, so there's a hard wrap after this line, although they looks the same.

Thanks for your help. :+1:
