### ISSUE TITLE
xmrigCC-1.6.5 - huge pages status error

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#149]
the miners logs writes correctly:
```
[2018-07-18 12:34:50] Starting thread 1/2 affined to core: #0 -> huge pages: 1/1 scratchpad: 2.0 MB
[2018-07-18 12:34:50] Starting thread 2/2 affined to core: #2 -> huge pages: 1/1 scratchpad: 2.0 MB
```

but on http dasboard it says "Huge Pages: avalible, disabled"

![bug](https://user-images.githubusercontent.com/38523505/42877760-0210a142-8a8b-11e8-8244-ece20a2bb8fd.jpg)

I have done other tests and I don't have this problem with previous version: 1.6.2

**Comment by Bendr0id** [comment]
Known issue, fixed in master

**Comment by Bendr0id** [comment]
Will also be improved in 1.6.6

**Comment by MrCook1es** [comment]
great work @Bendr0id thanks for all your work!

**Comment by Bendr0id** [comment]
Your welcome! Hope to see donations from "XMRigDeviceManager" soon :D

**Comment by Bendr0id** [comment]
Finished on master. Shows now "available, enabled (n/m)"
