### ISSUE TITLE
pc serialno use clientID

### ISSUE THREAD

**Issue by snipeTR** [Bendr0id/xmrigCC#15]
Hello there
I guess the computer name is used in clientID.

Is it possible to use motherboard serial number instead of ClientID?
"cmd >>> wmic bios get serialnumber"

**Comment by Bendr0id** [comment]
Not that hard to implement. But what is the benefit? So that when you clone a machine, it stays unique because hostname would be the same?

Makes sense.

**Comment by Bendr0id** [comment]
with the closing of #300 you can easily set that as a env variable and use it in as workerId.
