### ISSUE TITLE
Question about C&C Server

### ISSUE THREAD

**Issue by userid2018** [Bendr0id/xmrigCC#150]
Hello,

I am trying to use xmrigCC . I have  following questions
1) Can C&C Server be considered as proxy where all miners connect to server and server only connects to pool?
2) Can i install C&C Server as standalone server on a separate machine?

**Comment by userid2018** [comment]
as far as i understand XMRig Proxy does not support SSL. Is there any way I can have a Secure communication between XMrig proxy and xmrigCC  miner ?

**Comment by djfinch** [comment]
Hello,

Well, there is one option which you can try (I'm using the same way)... SSH tunnel from miner machine to proxy machine. This is something I wrote in crontab... Assuming Linux/macOS
`@reboot         /usr/local/bin/autossh -M 13333 -f -C -q -N -L localhost:3333:localhost:3333 user@ip_of_proxy_machine`
Or I can recommend you [XNP](https://github.com/MoneroOcean/xmr-node-proxy) which working with TLS from scratch.

**Comment by Bendr0id** [comment]
Or you can install an haproxy in front of the xmrig-proxy. Assuming you are on linux.. I use the same setup. You can find my config within this bugtracker..

Am 19.07.2018 20:15 schrieb djfinch <notifications@github.com>:

Hello,

Well, there is one option which you can try (I'm using the same way)... SSH tunnel from miner machine to proxy machine. This is something I wrote in crontab... Assuming Linux/macOS
@reboot /usr/local/bin/autossh -M 13333 -f -C -q -N -L localhost:3333:localhost:3333 user@ip_of_proxy_machine
Or I can recommend you XNP<https://github.com/MoneroOcean/xmr-node-proxy> which working with TLS from scratch.

**Comment by Bendr0id** [comment]
No response
