### ISSUE TITLE
Its support Crytptonight-Fast?

### ISSUE THREAD

**Issue by AndikaTanpaH** [Bendr0id/xmrigCC#151]
hi its support Crytptonight-Fast algo for Masari?

**Comment by Bendr0id** [comment]
Sure check the coin configuration guide:

https://github.com/Bendr0id/xmrigCC/wiki/Coin-configurations#masari-msr

Am 20.07.2018 05:43 schrieb Andika Hermansyah <notifications@github.com>:

hi its support Crytptonight-Fast algo for Masari?
