### ISSUE TITLE
Send update command immediately

### ISSUE THREAD

**Issue by Pawcio6** [Bendr0id/xmrigCC#152]
Hi
I plan a realy big ammount of miners and want to decrease traffic by removing automatic status update of client. Is a way to send command from server to client just once and immediately process that command instead of making strong unnecessary status update traffic? Something like when getClientStatusList is used than send a packet to client and response to server with setClientStatus to procces that on website. I just want to know is it possible to do that with actual handlePost handleGet functions and dont add new communication system?

**Comment by Bendr0id** [comment]
Why do you deleted the post? Feel free to join our discord channel https://discord.gg/r3rCKTB or message me on telegram @bendroid

**Comment by menoro92** [comment]
Dont expected that you will respond so fast ^_^ I removed post becouse it isnt even issue just some change that is not even make much difference for most users. i thout that you can listen on client for packets, same as it is builded on game engines to send packet directly from server to client. I wanted to make it immediately becouse i merge miner with other project and trying to add on same server some extra commands for updater, running processes and when i set interval for a bigger value ( binded it to accepted jobs so every 30-60 sec) user need to wait that minute to run a simple procces. But in a first place the type of communication should be in other way, what is a point to update 1k-100k clients for 24/7 if only 5 users will want to saw stats in the same time. Builded like that would make much difference

send get from opened website to server
    server send get to client
        client return actual status to server
    server return response from client to website
website show response status from server

but than i thout about how works proxy and it have smillar traffic usage so if proxy dont have any problems it should be same with miners thats why i removed that and closed
