### ISSUE TITLE
Compiling OK on ARMv7 but getting "Illegal instruction"

### ISSUE THREAD

**Issue by marcosligero** [Bendr0id/xmrigCC#155]
Hi everyone!

I guess this might be more a question than an issue but I don't know. I have been trying to compile the software in a ArmV7 computer with a success (the binaries were generated) but when I run the xmrigMiner I get the "Illegal instruction" error.

It might be because the processor does not support AES?

Thank you very much in advance!

**Comment by Bendr0id** [comment]
Yes its due to the lack of AES, on ARM processors the miner can't detect it automatically.
Try to set either "aesni": 2 in the config or via command parameter. Then it should work, but don't expect high hashrates...

**Comment by marcosligero** [comment]
Hi @Bendr0id! Many thanks for your very quick reply, sorry I could not reply you back before :)

My guess it must some something to do when I compiled the software, just tried with the flag and config parameters but didn't work, even with --aesni=2 and putting --version flag. When running the Daemon I'm getting those "Illegal instruction" errors in a loop, most probably because they are coming while looping the main thread.

Might have it something to do with the boost library? Sorry for being so noob :D

I know about the hashrate, just wanted to make it work for fun in a Scaleway ARMv7 bare-metal machine I use for development. I have read it's kind of complex to make it work in those systems because of limitations of Cryptonight v7 (https://github.com/xmrig/xmrig/issues/322, ARM without NEON instructions not supported.).

Many thanks for everything, and keep up the good work!
