### ISSUE TITLE
xmrigMiner blank process name 

### ISSUE THREAD

**Issue by mihlaz89** [Bendr0id/xmrigCC#156]
Good day, first of all sorry for my bad english.
I've changed these lines in CMakeLists.txt

from:

set(MINER_EXECUTABLE_NAME "xmrigMiner" CACHE STRING "Miner executable file name")
set(DAEMON_EXECUTABLE_NAME "xmrigDaemon" CACHE STRING "Daemon executable file name")

to

set(MINER_EXECUTABLE_NAME "miner" CACHE STRING "Miner executable file name")
set(DAEMON_EXECUTABLE_NAME "daemon" CACHE STRING "Daemon executable file name")

all files was compiled succesfully, but when i'm running daemon, there is a blank process name in the task manager. What I have to do to change it's name?

![image](https://user-images.githubusercontent.com/40289684/44208312-b29b6800-a168-11e8-99c1-ec0cc475dd7f.png)

P.S: miner has this blank process name, not daemon.

**Comment by Bendr0id** [comment]
Don't know. Could be due to a special character within the name...When you keep the original names everything is fine?

**Comment by mihlaz89** [comment]
Yes, all is fine, XMRigCC CPU Miner or something like that. I'm not using any special characters, only "qwerty" US english keyboard.

**Comment by Bendr0id** [comment]
Maybe remove CMakeCache.txt and do a rebuild

**Comment by mihlaz89** [comment]
Yes, i've deleted CMakeCache.txt and compiled miner again. All is working good now.

Thank you!
