### ISSUE TITLE
The number of threads does not change through the command line

### ISSUE THREAD

**Issue by Renemen64** [Bendr0id/xmrigCC#157]
The new version of the program stopped working with the command line parameter -t, --threads=N
in version 1.5.2 - it works
in the newer versions no longer works

**Comment by Bendr0id** [comment]
Which platform?
 1.6.5 or 1.7.0_beta1?

**Comment by Renemen64** [comment]
Ah, sorry foregot to say:
Windows x64, gcc version
last chacked in 1.6.5

**Comment by Renemen64** [comment]
just checked version 1.7.0 - same problem
I'm using the Windows scheduler, so it's easier for me to set the parameters in the command line than in the configuration file.

**Comment by Bendr0id** [comment]
Ok. So there is no config file at all? Because it could overrule when there is one..

**Comment by Renemen64** [comment]
The configuration file is there, but I use it as a template. In the command line, I change basically the number of threads and affinity to CPU.

**Comment by Bendr0id** [comment]
Ok check if threads is set there.. if so, remove it

**Comment by Renemen64** [comment]
OK I understood. If I delete the "threads" parameter in the configuration file, then I can switch the number of threads.
But, as I said in earlier versions, the command-line option had a higher priority, and this is more logical.

**Comment by Renemen64** [comment]
Any way, thanks for a tip. I will use this method as woraround.

**Comment by Bendr0id** [comment]
Do you build on your own? If so, please check latest 1.7.0 branch

**Comment by Bendr0id** [comment]
Fixed in master. Will be in release 1.7.0
