### ISSUE TITLE
server silently fails to pull the config if the client folder does not exist

### ISSUE THREAD

**Issue by untoreh** [Bendr0id/xmrigCC#158]
it should either throw an error or simply create the folder

**Comment by Bendr0id** [comment]
Be more precise. What is not working?

When you press "pull" on the dashboard the server will send async a command to the miner to push the config to the server. So the server cant show a failure in this case. It will print out an error to the server log.

If you mean when you press "edit" and there is no miner config, it will try to fetch the default_config.json, if that doesn't work the dashboard will print out an error on top in a read box.

So whats the problem?

**Comment by untoreh** [comment]
maybe it's just an edge case not really important

**Comment by djfinch** [comment]
Hi Ben,

I think untoreh talking about situation where config_cc.json file contain:
```"client-config-folder" : "./folder_which_does_not_exist_yet"```
So server is running but is not able to fetch config from miner cause target folder __where_to_store_configs__ is not accessible... I found this as well a long time ago so you have to create this folder before... Not an issue IMHO.

Regards,
finch...
