### ISSUE TITLE
Possible AMD & CPU together 

### ISSUE THREAD

**Issue by TheBudda** [Bendr0id/xmrigCC#159]
I have XMRigCC AMD working fine! I also have XMRigCC CPU working fine! How can I get both to work from the same folder? I look forward to your reply

Kind regards
TheBudda

**Comment by Bendr0id** [comment]
Just copy all binaries into one folder. Then copy xmrigCC-amd/config.json into that folder and rename it it config_amd.json. After that copy xmrigCC/config.json there and rename it to config_cpu.json. 

Now start them with parameter:

xmrigDaemon -c config_cpu.json
xmrigDaemon-amd -c config_amd.json

Ofc you only need to rename one but you can do both.

**Comment by TheBudda** [comment]
@Bendr0id  Thank you for your reply. I got everything working fine but when I go to the web front-end it only shows one miner. What am I doing wrong?

Kind regards
TheBudda

**Comment by Bendr0id** [comment]
Most propably you have the same workerid (default is hostname) it has to be unique. So either define one or both manually.

Am 20.08.2018 11:56 schrieb Budda <notifications@github.com>:

@Bendr0id<https://github.com/Bendr0id> Thank you for your reply. I got everything working fine but when I go to the web front-end it only shows one miner. What am I doing wrong?

Kind regards
TheBudda

**Comment by TheBudda** [comment]
I have tried everything to get this web front-end to work. Please see below

"worker-id": null,          // custom worker-id for CC Server (otherwise hostname is used) works fine!

"worker-id": Krypton,         // custom worker-id for CC Server (otherwise hostname is used) OR
"worker-id": krypton,         // custom worker-id for CC Server (otherwise hostname is used) FAIL!

xmrigDaemon.exe -c config_cpu.json
config_cpu.json:3360: Invalid value.
unable to open C:\Users\budda\xmrigCC-AMD-1.7.0_beta1\config.json: no such file or directory
Neither pool nor CCServer URL supplied. Exiting.

if I take out Krypton and put back null, it works>> "worker-id": null,         // custom worker-id for CC Server (otherwise hostname is used) WORKS! I have attached mu config_cpu

[config_cpu.txt](https://github.com/Bendr0id/xmrigCC/files/2302158/config_cpu.txt)

Sorry to be a pain. Its hard work for this 60 year old 

Kind regards
TheBudda

**Comment by Bendr0id** [comment]
No problem. Its just a syntax issue. You need to put strings in "", and you need to keep the , at the end.

So it should be:

"worker-id": "Krypton",

**Comment by TheBudda** [comment]
@Bendr0id  Yes Yes YES!! Thank you so much!!

Kind regards
TheBudda
