### ISSUE TITLE
Cannot compile on OSX

### ISSUE THREAD

**Issue by eschaettin** [Bendr0id/xmrigCC#165]
[  3%] Built target xmrigDaemon
[  5%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/GPUInfo.cpp.o
In file included from ../xmrigCC/src/cc/GPUInfo.cpp:18:
In file included from ../xmrigCC/src/cc/GPUInfo.h:22:
../src/3rdparty/rapidjson/document.h:1259:22: **error: call to constructor of 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >' is ambiguous**
        GenericValue v(value);
                     ^ ~~~~~
../xmrigCC/src/3rdparty/rapidjson/document.h:1330:16: note: in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
        return AddMember(n, value, allocator);
               ^
../xmrigCC/src/cc/GPUInfo.cpp:43:13: note: in instantiation of function template specialization 'rapidjson::GenericValue<rapidjson::UTF8<char>,
      rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::AddMember<unsigned long>' requested here
    gpuInfo.AddMember("device_idx", m_deviceIdx, allocator);
            ^
../xmrigCC/src/3rdparty/rapidjson/document.h:634:14: note: candidate constructor
    explicit GenericValue(int i) RAPIDJSON_NOEXCEPT : data_() {
             ^
../xmrigCC/src/3rdparty/rapidjson/document.h:640:14: note: candidate constructor
    explicit GenericValue(unsigned u) RAPIDJSON_NOEXCEPT : data_() {
             ^
../xmrigCC/src/3rdparty/rapidjson/document.h:646:14: note: candidate constructor
    explicit GenericValue(int64_t i64) RAPIDJSON_NOEXCEPT : data_() {
             ^
../xmrigCC/src/3rdparty/rapidjson/document.h:661:14: note: candidate constructor
    explicit GenericValue(uint64_t u64) RAPIDJSON_NOEXCEPT : data_() {
             ^
../xmrigCC/src/3rdparty/rapidjson/document.h:673:14: note: candidate constructor
    explicit GenericValue(double d) RAPIDJSON_NOEXCEPT : data_() { data_.n.d = d; data_.f.flags = kNumberDoubleFlag; }
             ^
1 error generated.
make[2]: *** [CMakeFiles/xmrig_cc_common.dir/src/cc/GPUInfo.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig_cc_common.dir/all] Error 2
make: *** [all] Error 2

**Comment by Bendr0id** [comment]
Please try again building master. 
@djfinch fixed it
