### ISSUE TITLE
build static for old libc

### ISSUE THREAD

**Issue by llavaud** [Bendr0id/xmrigCC#17]
with the following cmake:
`cmake . -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a -DWITH_CC_SERVER=OFF -DWITH_HTTPD=OFF`

on a debian wheezy, i got:
`./xmrigMiner: /lib/x86_64-linux-gnu/libc.so.6: version 'GLIBC_2.14' not found (required by ./xmrigMiner)`

how do you compile your linux-static-old_libc version ?

**Comment by Bendr0id** [comment]
Isn't my static build working for you?

It's a little more todo.. You need to compile/install cmake3 and gcc7 first.

Then you need to build latest libuv. 

And then you have to tell cmake path to your libuv.a, and gcc7. 

Then just make ;-)

**Comment by llavaud** [comment]
yes your static build works, it is just to be able to compile if i want to edit some code !
thanks for the response
