### ISSUE TITLE
News about upcoming "Cryptonight variant 2"

### ISSUE THREAD

**Issue by FranzDE** [Bendr0id/xmrigCC#172]
Any news about upcoming "Cryptonight variant 2" update?
https://github.com/monero-project/monero/pull/4218

Is xmrigCC 1.7.0 ready for the change?
Can we update only the proxy like xmrig-proxy? https://github.com/xmrig/xmrig/issues/753

**Comment by djfinch** [comment]
...
https://github.com/Bendr0id/xmrigCC/tree/monerov8_aka_cn2

**Comment by Bendr0id** [comment]
XMRigCC 1.7.0 is not ready for v2. But it's in progress.
You need to upgrade xmrig-proxy AND the XMRigCC. Same counts for xmrig btw.

**Comment by FranzDE** [comment]
thanks for the reply.
