### ISSUE TITLE
Linux Server

### ISSUE THREAD

**Issue by mike2246** [Bendr0id/xmrigCC#174]
Can/How do I run just the server on a Linux VPS Server? It's very simple on windows, edit the config and run. Does the same apply for Linux?

**Comment by djfinch** [comment]
Yes, but you have to compile CC-server part from source because static compile is not possible ATM (that's why release page contain just miners only. Just follow [wiki guide](https://github.com/Bendr0id/xmrigCC/wiki/Build-Debian%5CUbuntu)...
