### ISSUE TITLE
Nvidia/CCMiner

### ISSUE THREAD

**Issue by mike2246** [Bendr0id/xmrigCC#175]
This Program is Amazing for all my Ryzen's, if you could make an Nvidia version that can do all the popular algorithm's in CCMiner, I will either make a donation or let my cards run for you for a few days.

**Comment by the-white-light** [comment]
Considering there's already an [NVIDIA miner](https://github.com/xmrig/xmrig-nvidia) that's based on the same base as this, I would say it shouldn't be too difficult to fork, though Ben has a lot on his plate already.

**Comment by distributorofpain** [comment]
Bump for support :)

**Comment by Bendr0id** [comment]
finally released 3.0.0
