### ISSUE TITLE
[Feature request] Algo switching

### ISSUE THREAD

**Issue by bobbieltd** [Bendr0id/xmrigCC#176]
It seems your miner doesn’t switch algo nor take algo parameter from the pool.
Can you implememt MO’s feature https://github.com/xmrig/xmrig/pull/721 ?

**Comment by djfinch** [comment]
That's not true. Miner switching algo as per job extended info/as usual... I'm using this on daily basis.
I suppose you're talking about feature where miner reports algo performance back to pool and then pool select most profit algo/job based on this reported performance (I guess, maybe I missed something). That's MO-only feature. I can't find any other multi-algo pool... Is this worth to implement?

**Comment by bobbieltd** [comment]
@djfinch Sorry, I’m wrong. You are right. It is just like xmrig and do switch variant. However, it doesn’t switch algo (cn, cn-lite, cn-heavy).
Use case is not much worthy but I like MoneroOcean’s idea and think it is better to be implemented with current very low mining profitability.

**Comment by untoreh** [comment]
@Bendr0id any plans?

**Comment by Bendr0id** [comment]
Don't know if its really worth to look into that. Since variant changing is already supported you can simply switch between coins with a proxy. Next bigger feature is remote upgrade of the miner. So this has much lower prio.

**Comment by Bendr0id** [comment]
Integrated.

https://github.com/Bendr0id/xmrigCC/releases/tag/2.0.0-beta1
