### ISSUE TITLE
docker cannot start

### ISSUE THREAD

**Issue by ese105** [Bendr0id/xmrigCC#178]
hi..

i using centos 6.9

after run docker run bendr0id/xmrigcc i got this error

Error response from daemon: Cannot start container 4d0a1a5af7f4da67cdf98ad122e68dcb7aff61fc0fd0e66e881f272c33ea6944: no such file or directory

why?

**Comment by Bendr0id** [comment]
I just tested it, it works. So most propably youre doing something wrong.

```
docker run bendr0id/xmrigcc -a cryptonight -o donate2.graef.in:443 --use-tls -u YOUR_WALLET_ID -p x -k --cc-url=IP_OF_CC_SERVER:PORT --cc-access-token=SECRET_TOKEN_TO_ACCESS_CC_SERVER
```

**Comment by Bendr0id** [comment]
```
Error response from daemon: Cannot start container 4d0a1a5af7f4da67cdf98ad122e68dcb7aff61fc0fd0e66e881f272c33ea6944: no such file or directory
```

Looks like that for whatever reason docker isn't able to create the docker container...

**Comment by Bendr0id** [comment]
Is that a question?

**Comment by ese105** [comment]
can it run on centos 6.9?
sorry
