### ISSUE TITLE
can't compile miner

### ISSUE THREAD

**Issue by Achilles29** [Bendr0id/xmrigCC#179]
[ 79%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/SubmitResult.cpp.obj
[ 80%] Building CXX object CMakeFiles/xmrigMiner.dir/src/Summary.cpp.obj
[ 81%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/MultiWorker.cpp.obj
[ 82%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Handle.cpp.obj
[ 83%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Worker.cpp.obj
[ 85%] Building CXX object CMakeFiles/xmrigMiner.dir/src/xmrig.cpp.obj
**make[2]: *** No rule to make target 'C:\msys64\home\fuadm\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x32-1_67.a', needed by 'xmrigMiner.exe'.  Stop.
make[2]: *** Waiting for unfinished jobs....**
[ 87%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Hashrate.cpp.ob

please help me, cant compile the miner.

**Comment by Bendr0id** [comment]
You're linking against a boost lib which doesn't exist or isn't able to find. Make sure the file exists in the path.

**Comment by Achilles29** [comment]
i did, put my path, and build boost. but there is no file named "libboost_system-mgw73-mt-x64-1_67.a" in boost

**Comment by Bendr0id** [comment]
so thats the issue. either u used a newer version of gcc f.e. 8 then make sure you use the right lib name there or downgrade gcc to version 7.x
