### ISSUE TITLE
Offline miners

### ISSUE THREAD

**Issue by m1911** [Bendr0id/xmrigCC#18]
Can offline miners configure mail notifications?

**Comment by Bendr0id** [comment]
Not yet

**Comment by m1911** [comment]
Will the next version be added?

**Comment by Bendr0id** [comment]
I don't think so. It's not trivial. Dashboard is designed as a single-page-app which contains all the logic in JavaScript, the xmrigccserver is only the api. Without any logic. To provide a feature like this, a lot of work has to be done on server side. For example adding a thread for checking and detecting offline miners, integrating a platform independent mail system and a lot of refactoring to make this all configurable.

**Comment by m1911** [comment]
I know, thank you.
