### ISSUE TITLE
VS compile eror

### ISSUE THREAD

**Issue by Achilles29** [Bendr0id/xmrigCC#180]
D:\_Mining\_build\xmrigCC>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DBOOST_ROOT=C:\local\boost_1_67_0 .
CMake Error at CMakeLists.txt:2 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.

-- Configuring incomplete, errors occurred!
See also "D:/_Mining/_build/xmrigCC/CMakeFiles/CMakeOutput.log".

**Comment by djfinch** [comment]
You need this for your "Hidden Miner Project", right? Not sure if we want to help you...
This error message is clear...
Is VS2017 installed? Was generate command ran from VS CLI?
https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows#microsoft-visual-studio-2017

**Comment by bobbieltd** [comment]
Sorry to hijack this issue.
Haha “hidden miner project”, I’m also working on my “hidden mining”.
@djfinch It seems you have very large knowledge on mining. Could you suggest me a path to evade antivirus detection. I’m lost in antivirus battle.

**Comment by R0ckNRolla** [comment]
> D:_Mining_build\xmrigCC>cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 -DBOOST_ROOT=C:\local\boost_1_67_0 .
> CMake Error at CMakeLists.txt:2 (project):
> Generator
> 
> ```
> Visual Studio 15 2017 Win64
> ```
> could not find any instance of Visual Studio.
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/_Mining/_build/xmrigCC/CMakeFiles/CMakeOutput.log".

upgrade your VS 2017 to the latest version, and the build problem will disappear.
