### ISSUE TITLE
auto restart miner if hashing drop

### ISSUE THREAD

**Issue by ese105** [Bendr0id/xmrigCC#181]
hi...

some my gpu stopped after few day hashing... so i need to restart miner to mining again.. 
can we make it auto restart if hasing drop or some gpu not hashing?

**Comment by Bendr0id** [comment]
Is it sufficient to only restart the miner? I heard that its need to reboot the PC.

**Comment by ese105** [comment]
i just close miner then open it back... the hashing become normal.

can i ask? what function for restart button? when i click on restart button, on cc-client received command: Restart received -> restart ... then it hanging there until i close then open it back.

**Comment by Bendr0id** [comment]
Restart button should exactly do that. Seems that somehow the whole miner got stucked and it cant execute the command. Do you have a log of that?

**Comment by ese105** [comment]
i dont know where to find log. i`m using xmrigCC-amd-1.7.0-with_tls-mvc-win64.

**Comment by Bendr0id** [comment]
Implemented since XMRigCC-AMD 1.8.6
