### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by AlexGoodDay** [Bendr0id/xmrigCC#186]
When i try to build xmrigcc after writing -make j
There is that kind of issue
make[2]: *** No rule to build target «D:\msys64\home\alexp\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x64-1_67.a», required for «xmrigMiner.exe».

**Comment by AlexGoodDay** [comment]
And at the end make[1]: *** [CMakeFiles/Makefile2:153: CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Bendr0id** [comment]
You need to build boost. If you did, make sure the filename is correct (version) could be that you are using a newer gcc, then the file names a slighlty different. Or downgrade to gcc 7.3

**Comment by AlexGoodDay** [comment]
Thanks for your answer. Can you give me please the command to download gcc
7.3. I use msys2 to build th xmrigcc

вт, 16 окт. 2018 г., 2:00 Ben Gräf <notifications@github.com>:
