### ISSUE TITLE
compile XMRigCC 1.8.0 on linux x86

### ISSUE THREAD

**Issue by yellow1234** [Bendr0id/xmrigCC#187]
hello,

i'm trying to compile to linux x86 and get a lot of errors about sse2 functions in file CryptoNight_x86.h

example:
xmrigCC/src/crypto/CryptoNight_x86.h:554:70: error: ‘_mm_cvtsi64_si128’ was not declared in this scope
 __m128d x = _mm_castsi128_pd(_mm_add_epi64(_mm_cvtsi64_si128(n0 >> 12), _mm_set_epi64x(0, 1023ULL << 52)));

i tried to add to the c/c++ flags this"
-mfpmath=sse -march=pentium-m -msse2avx
and also a few others, but nothing works

thanks

**Comment by Bendr0id** [comment]
Please pull. Should be fixed now

**Comment by yellow1234** [comment]
working great
thanks
