### ISSUE TITLE
Error compile XMRigCC 1.8.0 on debian x64

### ISSUE THREAD

**Issue by eschaettin** [Bendr0id/xmrigCC#189]
Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
xmrigCC/src/api/ApiState.cpp: In function ‘double normalize(double)’:
xmrigCC/src/api/ApiState.cpp:56:20: error: ‘isnormal’ was not declared in this scope
     if (!isnormal(d)) {
                    ^
xmrigCC/src/api/ApiState.cpp:56:20: note: suggested alternative:
In file included from /usr/include/c++/4.9/random:38:0,
                 from /usr/include/c++/4.9/bits/stl_algo.h:66,
                 from /usr/include/c++/4.9/algorithm:62,
                 from xmrigCC/src/AsmOptimization.h:23,
                 from xmrigCC/src/Options.h:37,
                 from xmrigCC/src/Cpu.h:29,
                 from /xmrigCC/src/api/ApiState.cpp:36:
/usr/include/c++/4.9/cmath:650:5: note:   ‘std::isnormal’
     isnormal(_Tp __x)
     ^
CMakeFiles/xmrig_os_dependencies.dir/build.make:77: recipe for target 'CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o' failed
make[2]: *** [CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o] Error 1
CMakeFiles/Makefile2:275: recipe for target 'CMakeFiles/xmrig_os_dependencies.dir/all' failed
make[1]: *** [CMakeFiles/xmrig_os_dependencies.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Bendr0id** [comment]
Hmm seems that you are using a very old version of gcc. Try to use gcc5+

**Comment by eschaettin** [comment]
> Hmm seems that you are using a very old version of gcc. Try to use gcc5+

I am using gcc (Debian 4.9.2-10+deb8u1) 4.9.2 on Debian jessie (8.11). It worked well for all xmrigCC-Releases before. How can I install/upgrade to gcc5 or above?

**Comment by Bendr0id** [comment]
Hmm..

I removed some unnecessary import. Could you please pull and try again?

**Comment by eschaettin** [comment]
> Hmm..
> 
> I removed some unnecessary import. Could you please pull and try again?

Great, now it works again :+1: 

But there are a lot of warnings during compilation, for example like this:
src/crypto/CryptoNight_x86.h: In instantiation of ‘static void CryptoNightMultiHash<ITERATIONS, INDEX_SHIFT, MEM, MASK, SOFT_AES, 1ul>::hashLiteTube(const uint8_t*, size_t, uint8_t*, ScratchPad**) [with long unsigned int ITERATIONS = 262144ul; long unsigned int INDEX_SHIFT = 3ul; long unsigned int MEM = 1048576ul; long unsigned int MASK = 1048560ul; bool SOFT_AES = true; uint8_t = unsigned char; size_t = long unsigned int]’:
/src/crypto/CryptoNight.cpp:158:154:   required from ‘void cryptonight_lite_softaes(AsmOptimization, PowVariant, const uint8_t*, size_t, uint8_t*, ScratchPad**) [with long unsigned int NUM_HASH_BLOCKS = 1ul; uint8_t = unsigned char; size_t = long unsigned int]’
src/crypto/CryptoNight.cpp:223:57:   recursively required from ‘void setCryptoNightHashMethods(Options::Algo, bool) [with long unsigned int HASH_FACTOR = 4ul]’
src/crypto/CryptoNight.cpp:223:57:   required from ‘void setCryptoNightHashMethods(Options::Algo, bool) [with long unsigned int HASH_FACTOR = 5ul]’
src/crypto/CryptoNight.cpp:243:91:   required from here
src/crypto/CryptoNight_x86.h:1563:111: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         uint64_t tweak1_2 = (*reinterpret_cast<const uint64_t*>(reinterpret_cast<const uint8_t*>(input) + 35)

**Comment by Bendr0id** [comment]
Thats ok. It's a very old compiler and these are "only" warnings. Please try to start and see if the self check works.
