### ISSUE TITLE
Build Error (not sure if problematic)

### ISSUE THREAD

**Issue by tknecht** [Bendr0id/xmrigCC#19]
Hi, trying to put together an alpine docker image at the moment and stumbled upon this error. 

```
/root/xmrigccserver/tmp/src/App.cpp: In static member function 'static void App::onCommandReceived(uv_async_t*)':
/root/xmrigccserver/tmp/src/App.cpp:250:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
```
Running: cmake -DCMAKE_BUILD_TYPE=Release -DWITH_AEON=OFF .
Version:  XMRigCC/1.3.0 (based on XMRig 2.4.3) libuv/1.11.0 gcc/6.3.0

It seems there is no problem. In case this is not resulting in "Please configure a Dashboard" error.

If this is no problem,  just close it. 

Thanks and great work :)

**Comment by Bendr0id** [comment]
That's not a problem,  just a warning. No worried. But please consider to use gcc7. It will potentially give you a boost. Btw. If you check the latest release, it already contains static binaries compiled with gcc7.
