### ISSUE TITLE
Paused/Resumed via CMD/CC_Server

### ISSUE THREAD

**Issue by pr0vieh** [Bendr0id/xmrigCC#191]
If i Paused the Miner via cmd with "p" the CC Server will every "Update Cycle" Resume Mining
i think this is not very Useful that the CC Server automatically inverse the setting.
Just do it at Trigger the Button at Web Interface!

**Comment by Bendr0id** [comment]
This is the designed behavior. The server doesn't know if someone presses pause on the miner side, and since the miner is requesting a command from the server every n-seconds the server always answers with the last command. Just don't use the cli interface of the miner. You can do all the command via the web frontend. XMRigCC is made for farms with more then a single miner.

**Comment by pr0vieh** [comment]
how can i Trigger the Web Interface via a Bash Script ? in my case a CPU/Load Watcher to Start Stop the Miner if other things ToDo!
and by the way i have more than enough miners...

I understand but I think it would be possible to send the command only once and if there was no trigger there was a null command or something and if you trigger something at next request you could check if command was successful...

Thank you for your prompt reply 👍

**Comment by djfinch** [comment]
https://github.com/Bendr0id/xmrigCC/wiki/XMRigCCServer-API

**Comment by Bendr0id** [comment]
@pr0vieh 

Its much easier then injecting key presses into a running shell app. Via the API.

To pause:

```
curl -H "Content-Type: application/json" -X POST -d '{"control_command":{"command":"STOP"}}' http://admin:pass@127.0.0.1:3344/admin/setClientCommand?clientId=TestClient
```

To Resume:

```
curl -H "Content-Type: application/json" -X POST -d '{"control_command":{"command":"QUIT"}}' http://admin:pass@127.0.0.1:3344/admin/setClientCommand?clientId=TestClient
```

Ofcourse you need to put you're server and credentials there.

**Comment by pr0vieh** [comment]
hmm easier to ship commands to other Servers only to get it back locally ?
i think 
```
screen -dmS miner ./xmrig
screen -S miner -X stuff "p"
screen -S miner -X stuff "r"
```
is much easier to manage the workload for the Server himself :wink:
i will see what's the way to go for me tanks for the hints and ideas 

greets Pr0vieH

**Comment by Bendr0id** [comment]
On one single server it is, i fully agree. But if you have a monitoring for multiple servers, the way via the XMRigCC server is much easier..
