### ISSUE TITLE
Cannot compile 1.8.0 on OSX

### ISSUE THREAD

**Issue by eschaettin** [Bendr0id/xmrigCC#195]
What does this mean? Why I cannot compile the new release
Error message:

> xmrigCC/src/crypto/asm/cnv2_main_loop_ivybridge.inc:112:5: error: unknown token in expression
>  je $sqrt_fixup_ivybridge
> xmrigCC/src/crypto/asm/cnv2_main_loop_ivybridge.inc:150:6: error: unknown token in expression
>  jne $main_loop_ivybridge

**Comment by djfinch** [comment]
Please tell us : MacOS version, XCode version, post whole output to pastebin (incl. cmake stage).
OSX build passing ... https://travis-ci.com/Bendr0id/xmrigCC

**Comment by djfinch** [comment]
Seems there is no compiler for assembly. I have whole XCode on my mac machine. Travis-CI testing env contain XCode, too. See lines 2009+2010 here: https://travis-ci.com/djfinch/xmrigCC/builds/88463744

What's in your cmake* output? Is ASM compiler stated there?

**Comment by eschaettin** [comment]
cmake output:
cmake . -DUV_LIBRARY=/usr/local/lib/libuv.a  -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.a -DBOOST_ROOT=/usr/local/lib
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
-- The ASM compiler identification is unknown
-- Found assembler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Warning: Did not find file Compiler/-ASM
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/eschattin/mining/xmrigCC/build

**Comment by Bendr0id** [comment]
Thats the issue:

-- The ASM compiler identification is unknown
-- Warning: Did not find file Compiler/-ASM

**Comment by eschaettin** [comment]
How to fix without full install of XCode?

**Comment by djfinch** [comment]
That's kinda weird because ASM part should be compiled using GCC... :( I cannot uninstall it on my Mac to test some solutions. Maybe it's expecting Clang which is not there...

Xcode's compilers are probably in /usr/bin, Homebrew's are in /usr/local/bin. So...
`/usr/bin/gcc --version` and `/usr/bin/g++ --version` should fail and `/usr/local/bin/gcc-8 --version` and `/usr/local/bin/g++-8 --version` should pass.

Can you test it using absolute paths to compilers?
something like:
```cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.a -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.a -DBOOST_ROOT=/usr/local/lib -DCMAKE_C_COMPILER=/usr/local/bin/gcc-8 -DCMAKE_CXX_COMPILER=/usr/local/bin/g++-8```

**Comment by eschaettin** [comment]
This is working now, but then I get the error:

[ 31%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
In file included from src/Mem_unix.cpp:28:
src/crypto/CryptoNight.h:53:28: warning: 'variant_xtl_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
src/crypto/CryptoNight.h:52:28: warning: 'variant1_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
[ 32%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_mac.cpp.o
src/Platform_mac.cpp: In function 'char* createUserAgent()':
src/Platform_mac.cpp:49:129: error: '__clang_major__' was not declared in this scope
     snprintf(buf, max, "%s/%s (Macintosh; Intel Mac OS X) libuv/%s clang/%d.%d.%d", APP_NAME, APP_VERSION, uv_version_string(), __clang_major__, __clang_minor__, __clang_patchlevel__);
                                                                                                                                 ^~~~~~~~~~~~~~~
src/Platform_mac.cpp:49:146: error: '__clang_minor__' was not declared in this scope
     snprintf(buf, max, "%s/%s (Macintosh; Intel Mac OS X) libuv/%s clang/%d.%d.%d", APP_NAME, APP_VERSION, uv_version_string(), __clang_major__, __clang_minor__, __clang_patchlevel__);
                                                                                                                                                  ^~~~~~~~~~~~~~~
src/Platform_mac.cpp:49:163: error: '__clang_patchlevel__' was not declared in this scope
     snprintf(buf, max, "%s/%s (Macintosh; Intel Mac OS X) libuv/%s clang/%d.%d.%d", APP_NAME, APP_VERSION, uv_version_string(), __clang_major__, __clang_minor__, __clang_patchlevel__);
                                                                                                                                                                   ^~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmrig_os_dependencies.dir/src/Platform_mac.cpp.o] Error 1
make[1]: *** [CMakeFiles/xmrig_os_dependencies.dir/all] Error 2
make: *** [all] Error 2

**Comment by djfinch** [comment]
Damn, looks like Clang is mandatory, yes? @Bendr0id 
You can either disable ASM using `-DWITH_ASM=off`, install XCode, or build Clang from source because tap/formula for homebrew is not available yet. And this may take hours...
If you are brave enough, then:
`brew install --with-toolchain llvm` - download sources and run compiler
`PATH="/usr/local/opt/llvm/bin:$PATH"`
`LDFLAGS='-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib'`
 then cmake as usual (remove CMake* files before to clear cache)

**Comment by eschaettin** [comment]
> UPDATE:
> I forgot... You can disable ASM using -DWITH_ASM=off but...

Disable ASM using -DWITH_ASM=off is working, but what does it mean, what are the consequences or restrictions?

**Comment by Bendr0id** [comment]
Slower hash rates on cnv2 and no hashrate improve on cnv1 single hash mode

**Comment by Bendr0id** [comment]
On some CPUs up to 10% hashrate improve with ASM

**Comment by djfinch** [comment]
@Bendr0id What about something like this in CMakeList:
```
enable_language(C ASM)
SET(ASM_OPTIONS "-x assembler-with-cpp")
SET(CMAKE_ASM_FLAGS "${CFLAGS} ${ASM_OPTIONS}" )
```

**Comment by Bendr0id** [comment]
I think this is outdated.

**Comment by djfinch** [comment]
Hi Ben,

It is. I am not able to test each xmrigCC and Xcode combination but now (at least for latest) I am using Homebrew's llvm7 (can't install newer) as compiler and everything works well (incl. ASM).
Maybe below info helps if someone want it...

```
brew list --versions llvm
llvm 6.0.0 7.0.0
```
Compiled using:
```
cmake .. -DUV_LIBRARY=/usr/local/lib/libuv.a -DOPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.a -DOPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.a -DCMAKE_C_COMPILER=/usr/local/Cellar/llvm/7.0.0/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/Cellar/llvm/7.0.0/bin/clang++
```

**Comment by Bendr0id** [comment]
Thx. Appreciate your support!
