### ISSUE TITLE
Issue with 1.8.0 on RPi, hash test failed

### ISSUE THREAD

**Issue by cheltamel** [Bendr0id/xmrigCC#196]
Hi,
I'm having an issue with 1.8.0. It seems to compile & make ok, and xmrigcc works fine also, but when I try and run xmrigDaemon, it fails

pi@raspberrypi:~/xmrigCC $ ./xmrigDaemon -o xmr.pool.minergate.com:45700 -u x -p x -k
unable to open /home/pi/xmrigCC/config.json: no such file or directory
[2018-10-19 13:11:28] cryptonight hash self-test
[2018-10-19 13:11:57] cryptonight hash self-test... failed.
pi@raspberrypi:~/xmrigCC $ ./xmrigDaemon -a cryptonight --pow-variant=0 -o xmr.pool.minergate.com:45700 -u x -p x -k
unable to open /home/pi/xmrigCC/config.json: no such file or directory
[2018-10-19 13:13:25] cryptonight hash self-test
[2018-10-19 13:13:54] cryptonight hash self-test... failed.
pi@raspberrypi:~/xmrigCC $ ./xmrigDaemon -a cryptonight --pow-variant=1 -o xmr.pool.minergate.com:45700 -u x -p x -k
unable to open /home/pi/xmrigCC/config.json: no such file or directory
[2018-10-19 13:15:39] cryptonight hash self-test
[2018-10-19 13:16:08] cryptonight hash self-test... failed.

Can you suggest what might be going on? Happy to provide any logging I can

Thanks!

**Comment by cheltamel** [comment]
I'm running 2 different raspberry pis and both have the same issue:

Raspberry Pi 2 Model B Rev 1.1
Raspberry Pi 3 Model B Plus Rev 1.3

I've tried with the boost mentioned in the install article and the later version (1.6.8). Both ones after compiling and making have the same error. But the CC Server functions ok.

**Comment by Bendr0id** [comment]
Has nothing Todo with boost. The crypto engine is calculating wrong hashes. Make sure asm-optimization is set to none and aesni is set to 2 within the config.

**Comment by Bendr0id** [comment]
I hope this is for educational only. Because I'm the real world it's pure waste of energy to mine on a rpi. You should try to mine the cn-lite algorithm..

**Comment by cheltamel** [comment]
Yes its just for educational purposes. I'm not planning to make a living off mining!

This is my config:
{
    "algo": "cryptonight", 
    "aesni": 2,  
    "threads": 0, 
    "multihash-factor": 0,
    "multihash-thread-mask" : null, 
    "pow-variant" : "auto", 
    "background": false, 
    "colors": true, 
    "cpu-affinity": null, 
    "cpu-priority": null,
    "donate-level": 5, 
    "log-file": null, 
    "max-cpu-usage": 100, 
    "print-time": 60,
    "retries": 5, 
    "retry-pause": 5,
    "safe": false,
    "syslog": false,
    "pools": [
        {
            "url": "xmr.pool.minergate.com:45700",
            "user": "x",  
            "pass": "x", 
            "use-tls" : false, 
            "keepalive": true,
            "nicehash": false 
        }
    ],
    "cc-client": {

    }
}

tried with aesni to 2 and still same error

**Comment by cheltamel** [comment]
I also changed the CMakeList file to turn off ASM, and same error - cryptonight hash self-test failed. Is this going to be fixed?

**Comment by Bendr0id** [comment]
You can turn off the self check and see if it still works.

Just add a "return true;" here withouth the ""

https://github.com/Bendr0id/xmrigCC/blob/eebf62cd6a2657ca92e035bbfb9bca0249d1d7ee/src/crypto/CryptoNight.cpp#L270

**Comment by Bendr0id** [comment]
Most propably its only cn-heavy or something like that which is broken. Which is useless to mine on CPU anyways

**Comment by zserno** [comment]
I could successfully compile and start the XmrigCC Daemon on a Raspberry Pi 3 B+ to mine Stellite coin, using the workaround from https://github.com/Bendr0id/xmrigCC/issues/196#issuecomment-434871772.

Here's the patch file I used against XmrigCC 1.8.10:
[xmrigcc_issue_196_rpi_hash_test_failed.patch.txt](https://github.com/Bendr0id/xmrigCC/files/2760787/xmrigcc_issue_196_rpi_hash_test_failed.patch.txt)

**Comment by Bendr0id** [comment]
This will fix wrong calculation of hashes on arm. The root cause wasnt a broken self-test, it was an failure in the hashing algorithm on ARM.

https://github.com/Bendr0id/xmrigCC/releases/tag/1.8.11
