### ISSUE TITLE
What is this software?

### ISSUE THREAD

**Issue by lordgamegenie** [Bendr0id/xmrigCC#201]
I assumed this was a miner despite no information how to configure the this to a pool, so I went with the general configuration broadly used by different miners but this app wants you to start the Daemon file.  Why?

Then that wants to do a Self-Test? Why?

Could someone lead me to the right path, can this software be used to mine to a pool or am I wasting my time here?

**Comment by Bendr0id** [comment]
This is a miner and control server base on XMRig. It is made for to control multiple miners.

https://github.com/Bendr0id/xmrigCC#about-xmrigcc
