### ISSUE TITLE
[Feature Request] never "kill" xmrigDaemon

### ISSUE THREAD

**Issue by unsivilaudio** [Bendr0id/xmrigCC#202]
I'm currently using xmrigCCServer and xmrigDaemon-amd, which I'm using a cron job to launch screen sessions of both at reboot, and for the most part it works great.  Perhaps there is a workaround, but shouldn't the daemon never die?  

The problem comes when I send the "miner shutdown" command from server, it kills the daemon process (and with it the screen session), and can't be restarted (as far as I can tell), this seems like an oversight.  I would expect the daemon to stay alive and continue to report to the panel as "IDLE" until I send the start command again.

**Comment by Bendr0id** [comment]
Thanks for the idea. Maybe there is a misunderstanding of the different commands. The only reason why there is daemon is to restart the.l miners after config change or crash. It doesn't to any communication with the cc server. That's done by the miners itself. So once it is stopped, it won't be able to communicate with the cc server.
So the shutdown button really mean shutdown of the whole process. Daemon+Miner


But, the "pause" button is exactly what you want. It stops all Mining Threads and just keeps the connection to the cc server running. Once you press "start" again on the dashboard, the Miner will start mining again.

**Comment by djfinch** [comment]
@unsivilaudio I'm using simple bash script to check if daemon running. If not --> run it, if yes --> do nothing... And running this script via cron every x minutes.

start_miner.sh
```
#!/bin/bash
if [[ ! $(ps axo pid,command | grep "[x]mrigDaemon") ]]; then
        nohup /path/to/miner/xmrigDaemon >/dev/null 2>&1 &
fi
```

**Comment by unsivilaudio** [comment]
Oh, the misunderstanding is my own then, I thought it was the daemon that passed information along to the server, and the miner itself was essentially the same as xmrig's.  Great, appreciate the prompt reply.
