### ISSUE TITLE
Slower hash rate using 1.8.2 then from 1.8.0 release

### ISSUE THREAD

**Issue by lost-bro** [Bendr0id/xmrigCC#203]
I have compiled both the 1.8.0 and 1.8.2 using MYSY2 by the exact same protocol.  When using i5 6500 intel quad core I get 200H/s on cn/2 with 1.8.0 version.  On the same i5 6500 machines the 1.8.2 version will only give between 95-126H/s on cn/2.

One item I noticed is that the Huge Page memory shows 'unavailable / disabled' on the ServerCC HTML page.
All machines installed with the 1.8.0 version instantly 'found' the available Huge page memory and displayed it correctly on the HTML page.

I will recheck tomorrow the Huge Page memory setup, but I find it odd that ALL machines installed w/ ver. 1.8.0 ran flawlessly (Hugh pages and normal hash rate) and the machines w/ ver. 1.8.2  'seem' to be more difficult to get set up correctly and run with a reduce hash rate out of the box.

I would appreciate any advice .
Thanks in advance.
mjd

**Comment by Bendr0id** [comment]
Check for the changes from 1.8 to 1.8.2. It's dashboard and stratum communication. So this is really funny. Fix your hugpages and your speed is back.

**Comment by lost-bro** [comment]
Good point, I don't think that I changed out the HTML index when I upgraded to the 1.8.2 miners.
I will replace that now in the proxy machine so that tomorrow when the workers come online all will be ready.  I will report back with the outcome.  Thanks for the advice. 
mjd

**Comment by Bendr0id** [comment]
I doublecheckt. Everything is fine with the Hugepages. All my miners running 1.8.2 and have exactly the same hashrate then with 1.8.0. Which makes sense then NOTHING has changed.

So it has todo with your miners. Make sure hugepages are setup and no other instance is running it the same time, that could also result to HP errors.

https://i.imgur.com/42eqr4A.png

**Comment by Bendr0id** [comment]
Any new info?

**Comment by lost-bro** [comment]
Hi Bendri0d
We resolved the issue with the huge pages. Apparently we had some internet problems that were interfering with the CCserver.  After sorting out the server/internet problems all seems to be as it should be.  This time of the year we have very bad internet service due to the tropical rain storm/hurricanes.
I would this close this non-issue.  I do not believe it to be related to XmrigCC.
Thanks for the support.
Take care,
peace
mjd
