### ISSUE TITLE
Server-side miner config templates

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#206]
Feature suggestion : Server-side miner config templates

On the CC server there's default template with all default settings as with current default miner config. Settings of that template are assigned to all connected miners.

You can edit that template to assign common settings to all miners and create new templates with specific settings and apply conditions.

Template settings are the all the same as in miner config. 

Default template have all individual settings disabled so it doesn't apply anything. Additionally there's setting to disable mining on miners assigned to that template. Templates can be disabled.

Every settings can me enabled, and will be assigned to miners according to conditions ...

As follows : OS (Windows, Linux\Unix), CPU packages count (i think the case with multiple different cpus is out of question), CPU manufacturer (Intel\AMD\ARM\Undefined), number of physical cores, number of threads, LLC size, is portable\has battery, override assign to specific miner IDs (with mask), exclude specific miner IDs (with mask).

Templates have priority ladder so multiple templates that fall into the same conditions are further sorted by priority.

Usecases :

1) Mass changing pools or algo with single edit of CC server config.
2) Automatically assigning low cache demanding algo (CN-Light) and appropriate pools to CPUs with low LLC size (like 2-3MB of Celerons, Pentiums and i3s) instead of default settings.
3) Easy algo hopping with multiple unconditional templates just by moving them up and down in priority ladder (or just editing default config).

**Comment by MrCook1es** [comment]
>     1. Mass changing pools or algo with single edit of CC server config.

You have the "multi miner editor" for that.

**Comment by Bendr0id** [comment]
Like @MrCook1es already mentioned. For 1. There is the mass config edit function.

A basic template/default config selection for multiple miners  is plannes for a future releases.

F.e. to simple switch between cn/cn-lite/heavy or working hour/night switches.

Everything else you mentioned is a really custom and a lot of effort. I don't have time for that and until nobody is willing to pay for that I won't do it.

**Comment by Bendr0id** [comment]
@uz-spark is this feature resolved with the new template editor?

**Comment by uz-spark** [comment]
> @uz-spark is this feature resolved with the new template editor?

Kinda, better than nothing in any way.

Make it to overwrite only these lines that were specified in the template and it will be almost perfect :)

You know, now you must write complete config in the template or it won't even work, and it will completely overwrite miner's config on assign, except for miner's id.

Instead, if you write only partial config, say, only threads and multihash options, or only pools config - it will overwrite only these options on assign. That way it will be a lot more flexible without too much work on coding more robust system like i described in OP.

**Comment by MrCook1es** [comment]
good point! @uz-spark
