### ISSUE TITLE
How to use xmrigCC

### ISSUE THREAD

**Issue by mk148a** [Bendr0id/xmrigCC#207]
Hi, i am read wiki and not understant complety. I am use is for windows(miner) and maybe i use server on ubuntu or maybe windows. 
xmrigCCServer - its xmrig miner server, all miners connect this server
xmrigMiner.exe - its miner connect server and collect mining conf. data
xmrigDaemon - its necessary for connecting xmrig server ? (i dont understand here)

I have diffirent 2 pc, i want 1 pc is only server and other pc is miner. How to configure it?
And xmrigDaemon is it necessary ?

**Comment by thinkpol2** [comment]
You don't run xmrigMiner directly. On the client, you run xmrigDaemon which reads your config, talks to the CC server, etc. xmrigDaemon controls xmrigMiner. Both are required on every client.

xmrigCCServer is only required on your server.
