### ISSUE TITLE
Can you help me make a version that runs on Linux X86?

### ISSUE THREAD

**Issue by 1756816846** [Bendr0id/xmrigCC#21]
System info:
Linux MAYTINHSOCSON.VN 3.18.21-ZS #1 SMP Fri Sep 11 06:10:49 CEST 2015 i686 GenuineIntel unknown GNU/Linux

**Comment by Bendr0id** [comment]
Should be possible. But dont expect high hashrates.

Could you please send output of "cat /proc/cpuinfo"

**Comment by 1756816846** [comment]
This:
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz
stepping        : 6
microcode       : 0x60b
cpu MHz         : 2526.922
cache size      : 3072 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arc
h_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr
pdcm sse4_1 lahf_lm dtherm
bugs            :
bogomips        : 5053.84
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 23
model name      : Intel(R) Core(TM)2 Duo CPU     E7200  @ 2.53GHz
stepping        : 6
microcode       : 0x60b
cpu MHz         : 2526.922
cache size      : 3072 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fdiv_bug        : no
f00f_bug        : no
coma_bug        : no
fpu             : yes
fpu_exception   : yes
cpuid level     : 10
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov
pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe nx lm constant_tsc arc
h_perfmon pebs bts aperfmperf pni dtes64 monitor ds_cpl est tm2 ssse3 cx16 xtpr
pdcm sse4_1 lahf_lm dtherm
bugs            :
bogomips        : 5053.84
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:

**Comment by 1756816846** [comment]
As long as normal operation on it

**Comment by Bendr0id** [comment]
Ok, whats the output of "ldd --version" ?

**Comment by 1756816846** [comment]
ldd --version
ldd (GNU libc) 2.20
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

**Comment by Bendr0id** [comment]
[xmrigCC-1.3.1-gcc4.8-linux-static-old_libc-miner_only-x86.tar.gz](https://github.com/Bendr0id/xmrigCC/files/1614913/xmrigCC-1.3.1-gcc4.8-linux-static-old_libc-miner_only-x86.tar.gz)

Could you please try that?

**Comment by 1756816846** [comment]
Already run, thank you

**Comment by Bendr0id** [comment]
Will add it to the release cycle.
