### ISSUE TITLE
Pushover push notifications for periodical status notifications shows the total hashrate including offline miners, but should only show hashrate online miners.

### ISSUE THREAD

**Issue by ORGaniZMo** [Bendr0id/xmrigCC#214]
Pushover push notifications for periodical status notifications shows the total hashrate including offline miners, but should only show hashrate online miners. Am I right?

**Comment by Bendr0id** [comment]
Yes you're right. My mistake.Will fix it in the next version and i may add telegram aswell.

**Comment by ORGaniZMo** [comment]
> and i may add telegram aswell.

Great

**Comment by Bendr0id** [comment]
Fixed in 1.8.6
