### ISSUE TITLE
1 card stop mining after hours/days

### ISSUE THREAD

**Issue by Luisjc69** [Bendr0id/xmrigCC#215]
Hello,
im mining since days with the new 1.8.5 and works fine.
Windows 10, RX580 8 giga 7 cards!
After several hours, sometimes one day, only ONE CARD goes offline....the other 6 works perfect.
The problem is, it is not every time the same card, so conclusion for me that the cards are ok....if Im mining with other software, i dont get this error.
Atm im mining Freehaven.....

any ideas? 
the next problem is, i dont get any errors, because mining works with 6 cards without any problems...but the seventh cards have 0hs.

Thank you

**Comment by Bendr0id** [comment]
Hello,
this is the CPU version of the miner. But anyways Crashing of a card can happen. Can be driver, Temperatur or something else. The next version will have a watchdog for detecting card crashs. It will restart/reboot the miner in that case to solve the issue.

This should solve the problems for your. Additionally XMRigCCServer will send out a notification when the hashrate drops to 0.

**Comment by Luisjc69** [comment]
> Hello,
> this is the CPU version of the miner. But anyways Crashing of a card can happen. Can be driver, Temperatur or something else. The next version will have a watchdog for detecting card crashs. It will restart/reboot the miner in that case to solve the issue.
> 
> This should solve the problems for your. Additionally XMRigCCServer will send out a notification when the hashrate drops to 0.

vielen Dank! :)
