### ISSUE TITLE
Dashboard not loading miners on Firefox and Brave; Opera works ?

### ISSUE THREAD

**Issue by marvin8** [Bendr0id/xmrigCC#216]
When I am loading the dashboard on Opera the miners are shown as expected.

When I load the exact same url for the dashboard on Firefox or Brave browsers, none of the miner details are shown and only "Loading ..." is shown.

What am I doing wrong?

PS: I am not loading index.html :)

Oh and thanks for sharing your work with us. Very much appreciated.

**Comment by Bendr0id** [comment]
Sound for me like you have some js blocker like noscript... The dashboard is almost pure js. Make sure you disable js blocking for the dashboard.

**Comment by marvin8** [comment]
Haven't got a JS blocker as such installed on any browser...
However I have Decentraleyes plugin and Privacy Settings plugin installed in Firefox

However I haven't got any plugins like that installed on Brave. So having issues on Brave surprises me.

Anything I can do to work out which bit is not working right?

**Comment by djfinch** [comment]
Please open Tools/Web Developer/Network page, select XHR --> Response and double-check if you receiving JSON object which is then displayed inside the table...

![image](https://user-images.githubusercontent.com/13107713/49572899-0bbc2100-f93d-11e8-8cf3-3ec0d834ef51.png)

**Comment by Bendr0id** [comment]
![screenshot_2018-12-06_09-57-58](https://user-images.githubusercontent.com/383361/49573219-c6e4ba00-f93d-11e8-9a32-d95f04941eed.png)

Works for me on FF too.

**Comment by marvin8** [comment]
Thanks @djfinch 
That part seems to be working ok... it seems like I am getting responses:
![responses](http://i.imgur.com/7hC7Ehe.png)

**Comment by djfinch** [comment]
You're welcome. That's good. At least server sending responses and browser getting them thus ajax works. So we need to figure out why datatables cannot render them... Is something shown inside console? Looks like (as Ben mentioned before) some scripts are blocked. Can you also test the behavior inside 'New Private Window'?

**Comment by marvin8** [comment]
Ok... While you were responding I poked around a bit more and found in the console that I FF couldn't load a couple of scripts:
```
https://cdnjs.cloudflare.com/ajax/libs/jquery-timeago/1.6.1/jquery.timeago.min.js
https://cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js
```

I think the reason Opera could load them is because I have opera set-up to use a SOCKS5 proxy. Neither my FF or Brave are using a proxy.

Disabling the proxy on Opera makes the list of miners not show in Opera as well.

So It's a network issue in my situation.

I guess I could download the scripts and host with on the same host where the server runs. Would have to edit the index.html page of course.
Can I have the server serve the scripts as well?

**Comment by djfinch** [comment]
Well, looks like you're in the same situation as I am... :) Behind very restrictive firewall...
Please make sure that this below is also enabled...
![image](https://user-images.githubusercontent.com/13107713/49579164-d5d26900-f94b-11e8-81eb-864f87065778.png)

**Comment by marvin8** [comment]
Actually in my case the proxy made it work... :)
But I'd like it to work without, so I am going to host the scripts my self on the server I know I can reach without a proxy...

Thanks for your help... Feel free to close this issue when it suits you. 
It is obviously nothing wrong with the software but an issue on my side that I can work around.
