### ISSUE TITLE
 Optimize Epyc 7551p

### ISSUE THREAD

**Issue by kekojeda** [Bendr0id/xmrigCC#221]
I Configure xmrig cc with cryptonight-lite on my Epyc 7551p. but I can not get more than 700hs. what I think is too little for that micro, since with an i7 4770k I get the same power. What can I do to optimize this?
Use Windows Server 2016, I attach the configuration of the deamon

{
  "algo": "cryptonight-lite",
  "aesni": 0,
  "threads": 0,
  "multihash-factor": 0,
  "multihash-thread-mask": null,
  "pow-variant": "1",
  "asm-optimization": "auto",
  "background": false,
  "colors": true,
  "cpu-affinity": null,
  "cpu-priority": null,
  "donate-level": 1,
  "log-file": null,
  "max-cpu-usage": 90,
  "print-time": 60,
  "retries": 5,
  "retry-pause": 5,
  "safe": false,
  "syslog": false,
  "reboot-cmd": "",
  "pools": [
    {
      "url": "pool.trtl.ninja:7777",
      "user": "TRTLuztDAkWBeM.........................................",
      "pass": "x",
      "use-tls": false,
      "keepalive": true,
      "nicehash": false
    }
  ],
  "cc-client": {
    "url": "localhost:3344",
    "use-tls": false,
    "access-token": "test",
    "worker-id": null,
    "update-interval-s": 10,
    "use-remote-logging": true,
    "upload-config-on-startup": true
  }
}

thanks!!!

**Comment by Bendr0id** [comment]
send me the startup of the application, then i have more info to optimize

**Comment by kekojeda** [comment]
You mean this?
![aa](https://user-images.githubusercontent.com/31479202/50289538-ec96b680-0447-11e9-9ddc-c5479c338238.png)

**Comment by kekojeda** [comment]
Perfect! I improve enough with your configurations. Now I get 980 hs... but I'm still far from the 5000 + hs.. any other settings I can try?

thanks for your help!
![b](https://user-images.githubusercontent.com/31479202/50291367-30d88580-044d-11e9-9889-80feee5a69e1.png)
![c](https://user-images.githubusercontent.com/31479202/50291375-3635d000-044d-11e9-9b00-466688a181ae.png)

**Comment by Bendr0id** [comment]
On your screenshot youre using 64 cores, can you please try this:

```
{
"algo": "cryptonight-lite",
"aesni": 0,
"threads": 0,
"multihash-factor": 0,
"multihash-thread-mask": null,
"pow-variant": "1",
"asm-optimization": "auto",
"background": false,
"colors": true,
"cpu-affinity": null,
"cpu-priority": null,
"donate-level": 1,
"log-file": null,
"max-cpu-usage": 100,
"print-time": 60,
"retries": 5,
"retry-pause": 5,
"safe": false,
"syslog": false,
"reboot-cmd": "",
```

**Comment by kekojeda** [comment]
much worse. only 200hs. This is my current configuration with your tips
{
  "algo": "cryptonight-lite",
  "aesni": 0,
  "threads": 0,
  "multihash-factor": 0,
  "multihash-thread-mask": null,
  "pow-variant": "1",
  "asm-optimization": "auto",
  "background": false,
  "colors": true,
  "cpu-affinity": null,
  "cpu-priority": null,
  "donate-level": 1,
  "log-file": null,
  "max-cpu-usage": 100,
  "print-time": 60,
  "retries": 5,
  "retry-pause": 5,
  "safe": false,
  "syslog": false,
  "reboot-cmd": "",
  "pools": [

}
![e](https://user-images.githubusercontent.com/31479202/50292562-37b4c780-0450-11e9-984a-08a611a1c17c.png)

**Comment by kekojeda** [comment]
Yes very strange, more than a month ago I am doing tests and I can not get the hs up.
no, I do not have another miner or process in execution .. :(
Will it be windows server?

**Comment by Bendr0id** [comment]
Hmm could be to an upgrade of windows, which patches some microkernel stuff maybe.. But these hashrates are WAYS to low for that cpu

**Comment by Bendr0id** [comment]
even multiple restarts with the same settings seem to effect the hashrate.. Compare your screenshots, they are using exactly the same settings. One time its 900h/s other time 399 h/s. That doesnt make sense

**Comment by kekojeda** [comment]
I will try with a live linux to see what results I have

**Comment by kekojeda** [comment]
Hi! any update about that?
with this configuration I managed to reach 10 khz, but I'm still far from what I should have.

```
{
    "algo": "cryptonight-ultralite",                      // cryptonight (default), cryptonight-lite, cryptonight-ultralite, cryptonight-extremelite or cryptonight-heavy
    "aesni": 1,                                 // selection of AES-NI mode (0 auto, 1 on, 2 off)
    "threads": 20,                               // number of miner threads (not set or 0 enables automatic selection of optimal thread count)
    "multihash-factor": 3,                      // number of hash blocks to process at a time (not set or 0 enables automatic selection of optimal number of hash blocks)
    "multihash-thread-mask" : null,             // for multihash-factors>0 only, limits multihash to given threads (mask), mask "0x3" means run multihash on thread 0 and 1 only (default: all threads)
    "pow-variant" : "1",                     // specificy the PoW variat to use: -> auto (default), '0', '1', '2', 'ipbc', 'xao', 'xtl', 'rto', 'xfh', 'upx', 'turtle', 'hosp', 'r', 'wow', 'double (xcash)', 'zls' (zelerius), 'rwz' (graft), 'upx2'
                                                // for further help see: https://github.com/Bendr0id/xmrigCC/wiki/Coin-configurations
    "asm-optimization" : "ryzen",                // specificy the ASM optimization to use: -> auto (default), intel, ryzen, bulldozer, off
    "background": false,                        // true to run the miner in the background (Windows only, for *nix plase use screen/tmux or systemd service instead)
    "colors": true,                             // false to disable colored output
    "cpu-affinity": null,                       // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
    "cpu-priority": null,                       // set process priority (0 idle, 2 normal to 5 highest)
    "donate-level": 5,                          // donate level, mininum 1%
    "log-file": null,                           // log all output to a file, example: "c:/some/path/xmrig.log"
    "max-cpu-usage": 100,                       // maximum CPU usage for automatic mode, usually limiting factor is CPU cache not this option.
    "print-time": 60,                           // print hashrate report every N seconds
    "retries": 5,                               // number of times to retry before switch to backup server
    "retry-pause": 5,                           // time to pause between retries
    "safe": false,                              // true to safe adjust threads and av settings for current CPU
    "syslog": false,                            // use system log for output messages
    "reboot-cmd" : "",                          // command to execute to reboot the OS
    "force-pow-variant" : false,                // force pow variant, dont parse pow/variant from pool job
    "skip-self-check" : false,                  // skip the self check on startup
    "pools": [
        {
            "url": "Pool.TRTL.CryptoPool.Space:5555",       // URL of mining server
            "user": "TRTLuztDAkWBeMyjMeBJomKUo9.....",           // username for mining server
            "pass": "x",                        // password for mining server
            "use-tls" : false,                  // enable tls for pool communication (need pool support)
            "keepalive": true,                  // send keepalived for prevent timeout (need pool support)
            "nicehash": false                   // enable nicehash/xmrig-proxy support
        }
    ],
    "cc-client": {
        "url": "xxxx:3344",                // url of the CC Server (ip:port)
        "use-tls" : false,                      // enable tls for CC communication (needs to be enabled on CC Server too)
        "access-token": "pass",             // access token for CC Server (has to be the same in config_cc.json)
        "worker-id": null,                      // custom worker-id for CC Server (otherwise hostname is used)
        "update-interval-s": 10,                // status update interval in seconds (default: 10 min: 1)
        "use-remote-logging" : true,            // enable remote logging on CC Server
        "upload-config-on-startup" : true       // upload current miner config to CC Server on startup
    }
}
```
Does anyone think that configurations change?

**Comment by Bendr0id** [comment]
"multihash-factor": 3,  change to 2.

Maximum performance on that algo you have with hashfactor 2.

**Comment by Bendr0id** [comment]
Numa support is now intregrated. Should be fixed now.

https://github.com/Bendr0id/xmrigCC/releases/tag/2.0.0-beta1
