### ISSUE TITLE
How to use the Template Editor?

### ISSUE THREAD

**Issue by ORGaniZMo** [Bendr0id/xmrigCC#223]
Can a simple usage example?

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/wiki/Template-Editor

**Comment by ORGaniZMo** [comment]
Ok, thx. But if we extend such a config to a certain number of clients, then all of them will be with the same name (worker-id).

**Comment by Bendr0id** [comment]
That's not true. The workerid is the only value which is not overwrite. It will stay.

**Comment by ORGaniZMo** [comment]
> That's not true. The workerid is the only value which is not overwrite. It will stay.

Yes, You're right. But how to be, for example, with `"user": "",                         // username for mining server`? Is this value also not changed?

**Comment by Bendr0id** [comment]
"user" : "" will result in sending the hostname to the cc-server. When you use the template the "user" : "" will be replaced with the value it was sending to the cc-server. 

Sample:

config -> "user" : "" will send  something like "WIN1234-abc123" to the cc server. When the template is applied, it will put "user" : "WIN1234-abc123" in the new config.

**Comment by Bendr0id** [comment]
So it will stay the same as before the template was applied.

**Comment by ORGaniZMo** [comment]
it seems I can not understand the logic of work.
I am currently creating a template:
{
  "algo": "cryptonight-lite",
  "aesni": 0,
  "threads": 0,
  "multihash-factor": 0,
  "multihash-thread-mask": null,
  "pow-variant": "auto",
  "asm-optimization": "auto",
  "background": false,
  "colors": true,
  "cpu-affinity": null,
  "cpu-priority": 0,
  "donate-level": 1,
  "log-file": null,
  "max-cpu-usage": 100,
  "print-time": 60,
  "retries": 5,
  "retry-pause": 5,
  "safe": false,
  "syslog": false,
  "pools": [
    {
      "url": "bla.bla.bla:1234",
      "user": "",
      "pass": "x",
      "use-tls": false,
      "keepalive": true,
      "nicehash": true
    }
  ],
  "api": {
    "port": null,
    "access-token": null,
    "worker-id": null
  },
  "cc-client": {
    "url": "bla.bla.bla:3344",
    "use-tls": false,
    "access-token": "bla.bla.bla",
    "worker-id": null,
    "update-interval-s": 10,
    "use-remote-logging": true,
    "remote-logging-max-rows": 20
  }
}
Then applied it to several clients. According to your description, "user" should not have changed, or it should have substituted the name of the host / workID, right? But I just have a nameless worker on my proxy.

**Comment by Bendr0id** [comment]
No, you maybe misunderstood. The worker-id (in the cc-section) is not overwritten, the user in the pool section is (makes sense if you dont use a proxy). But i'll add an option to "keep the pool user" in the next release.

**Comment by Bendr0id** [comment]
Turns out thats a little more effort. Can't promise that it will be in the next release (tonight)

**Comment by hashyg0d** [comment]
@Bendr0id how can I delete templates?

**Comment by Bendr0id** [comment]
Right now only on the server via filesystem

**Comment by hashyg0d** [comment]
@Bendr0id jeez, you're fast! Ok, I'll dig on the server. If you know the path that they're stored in, let me know - I'll add it to the Wiki.

**Comment by djfinch** [comment]
Inside  folder specified in config_cc.json [(L14)](https://github.com/Bendr0id/xmrigCC/blob/master/src/config_cc.json#L14) or app basedir if 'null'.
