### ISSUE TITLE
Stellite - incorrect variant detection

### ISSUE THREAD

**Issue by bobbieltd** [Bendr0id/xmrigCC#227]
xmrigCC version 1.8.9
config.json algo : cn, pow-variant : xtl
pools tested : semipool, cryptopool, hashvault

xmrigCC mines with "xtlv9" not "xtl". (pool send variant as xtl). Of course bad / rejected shares.

**Comment by bobbieltd** [comment]
With "force-pow-variant" : true, it still mines with PoW xtlv9

**Comment by Bendr0id** [comment]
Fixed in master. Sorry about that was a stupid thing which somehow did it in the release. Will create a 1.8.10 tomorrow.

**Comment by bobbieltd** [comment]
Thanks alot.

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/releases/tag/1.8.10
