### ISSUE TITLE
Failover CC-servers for CC-clients

### ISSUE THREAD

**Issue by ORGaniZMo** [Bendr0id/xmrigCC#229]
What about failover CC-servers for CC-clients?

 "cc-client": [
{
    "url": "url1:3344",
    "use-tls": false,
    "access-token": "qwerty",
    "update-interval-s": 10,
    "use-remote-logging": true,
    "upload-config-on-startup": true,
    "worker-id": "bla"
  },
{
    "url": "url2:3344",
    "use-tls": false,
    "access-token": "qwerty",
    "update-interval-s": 10,
    "use-remote-logging": true,
    "upload-config-on-startup": true,
    "worker-id": "bla"
  }
...
]

**Comment by Bendr0id** [comment]
Should be possible. Need to check the efforts

**Comment by Bendr0id** [comment]
Released

**Comment by Bendr0id** [comment]
Format is like this:

```
"cc-client": {
        "enabled": true,
        "servers": [
            {
                "url": "localhost:3344",
                "access-token": "mySecret",
                "use-tls": false
            },
            {
                "url": "localhost:4455",
                "access-token": "mySecret",
                "use-tls": false
            }
        ],
        "use-remote-logging": true,
        "upload-config-on-start": true,
        "worker-id": null,
        "reboot-cmd": null,
        "update-interval-s": 10,
        "retries-to-failover": 5
    },
```

**Comment by BrendaAtchley** [comment]
This feature is finally implemented
  I have been looking forward to it for many years
