### ISSUE TITLE
unable to performRequest POST

### ISSUE THREAD

**Issue by j4mm1n** [Bendr0id/xmrigCC#23]
Hey guys,

First of all thanks for the great work you have put together here. It is a great way to keep track of the different workers. I've been able to set up the Server and the daemons on a couple servers. Their status is updated every x seconds as set-up in the config. However I can't seem to find the problem with the last servers.

I keep getting this error

`[2018-01-13 18:35:33] [CC-Client] error: unable to performRequest POST -> http://exampleServer.domain.com:3434/client/setClientStatus?clientId=exampleWorker.domain.com`

The workers are installed on CentOS 7.

If someone could point me in the right direction that would be great.

Thanks !

**Comment by Bendr0id** [comment]
Hey man, sorry can't get a lot out of your log. Please make sure that the port and ip of the server is reachable from the miner. If it's on another network, make sure that the port is forwarded in a case of nat. Also double check if the port is correct defined in the config. currently it looks like you changed it from the default 3344 to 3434, hope that's what you want. So you have already some working miners which are able to.communicat with the server?

**Comment by j4mm1n** [comment]
Thanks for the quick reply Bendr0id, 

I'm sure the port is forwarded correctly. I am hosting the CC Server on a VPS. I'm able to reach the server locally ( daemon --> localhost ) and from a remote destination Linux Ubuntu machine ( through IP and port ). The information is being updated consistently during the last hours.

However I have a couple of CentOS 7 servers that I would like to use as well. I am certain that the ports and IP are correct. I've just changed the information in the initial post. 

The workers are all mining correctly, it seems that they are unable to perform the http POST request. Could this be due to a dependency is missing? 

Hoping this clears up the problem a bit. I would gladly offer more information however the CC-Client only shows the initial error message over and over again.

**Comment by j4mm1n** [comment]
Bendr0id,

I have found the problem. It was a firewall issue on the server side. Everything works great now !

**Comment by Bendr0id** [comment]
Ok, cool. If you need further information or help, just contact me via telegram. @bendr0id

Am 13.01.2018 20:03 schrieb j4mm1n <notifications@github.com>:

Closed #23<https://github.com/Bendr0id/xmrigCC/issues/23>.
