### ISSUE TITLE
How do I write the pool url & cc-server url information directly in the miner?

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#230]
Hi, is it possible to write inside the source code the pool url and the cc-server url?
I had a look on the "Options.cpp" source, and I tried to make some changes, but I only made mistakes.

**old-test:**
change from:
m_pools.push_back(new Url());

to
m_pools.push_back(Pool("mypool.com", 3333, "username", "password"));

does not work. Error during compile.

_______________________

New way...

https://github.com/Bendr0id/xmrigCC/blob/master/src/Options.cpp#L249

```
static struct option const pool_options[] = {
    { "url",           1, nullptr, 'o'  },
    { "pass",          1, nullptr, 'p'  },
    { "user",          1, nullptr, 'u'  },
    { "userpass",      1, nullptr, 'O'  },
    { "keepalive",     0, nullptr ,'k'  },
    { "nicehash",      0, nullptr, 1006 },
    { "use-tls",       0, nullptr, 1015 },
    { "pow-variant",   1, nullptr, 1017 },
    { "variant",       1, nullptr, 1017 },
    { nullptr, 0, nullptr, 0 }
};
```

https://github.com/Bendr0id/xmrigCC/blob/master/src/Options.cpp#L270

```
static struct option const cc_client_options[] = {
    { "url",                    1, nullptr, 4003 },
    { "access-token",           1, nullptr, 4004 },
    { "worker-id",              1, nullptr, 4005 },
    { "update-interval-s",      1, nullptr, 4012 },
    { "use-tls",                0, nullptr, 4016 },
    { "use-remote-logging",     0, nullptr, 4017 },
    { "upload-config-on-startup",  0, nullptr, 4019 },
    { "reboot-cmd",             1, nullptr, 4021 },
    { nullptr, 0, nullptr, 0 }
};
```

If it's possibile I want to put only pool _url:port_ & xmrigCC-server _url:port_ I want to setup everything else manually inside the config.json file.

pool: mypool.com:3333
xmrigCC-server: server.com:3344

**Comment by MrCook1es** [comment]
@djfinch tested and not working...

"Please configure CC-Url andrestart. CC feature is now deactivated."

the pool is taken into consideration and works.
I've also tried starting the miner without the pool related part to the config file. (same result))
```
    "pools": [
        {
            "url": "donate2.graef.in:80",
            "user": "YOUR_WALLET_ID",
            "pass": "x",
            "use-tls" : false,
            "keepalive": true,
            "nicehash": false
        }
    ],
```

**Comment by djfinch** [comment]
Above example is just for hardcoring pool into source code. Not for CC server itself. I did a test of freshly compiled xmrigCC without config.json inside the folder and it works.

**Comment by Bendr0id** [comment]
I should get xmr for doing stupid/trivial stuff like that.

```
    m_ccToken = "your_token";
    m_ccPort = 3344;
    m_ccHost "your.server.com";
```

before this block:

```
if (!m_pools[0]->isValid() && (!m_ccHost || m_ccPort == 0)) {
        fprintf(stderr, "Neither pool nor CCServer URL supplied. Exiting.\n");
        return;
    }
```

Then just remove the whole cc-client { } block from the config.

Here is my xmr wallet:

4BEn3sSa2SsHBcwa9dNdKnGvvbyHPABr2JzoY7omn7DA2hPv84pVFvwDrcwMCWgz3dQVcrkw3gE9aTC9Mi5HxzkfF9ev1eH

**Comment by djfinch** [comment]
To avoid any questions here... See this example...
https://github.com/djfinch/xmrigCC/commit/0a6509cc5734f454bfc371d6b49d2ae60f5c8eee
... and ignore warnings about C++ standards...
![image](https://user-images.githubusercontent.com/13107713/52296637-2d5a7880-297f-11e9-8a7a-8bbb94841ef0.png)

**Comment by MrCook1es** [comment]
thanks for your advice .. but I asked something different..
If it is possible, I need to put inside the miner only pool-url and xmrigCCserver-url.
I need to be able to set other values manually on the config.json file.

Because I would like to keep the possibility of setting these values in the config.json file:

	"pools": [
        {
            "user": "x",
            "pass": "NAME",
            "use-tls" : false,
            "keepalive": true,
            "nicehash": true
        }


    "cc-client": {
        "worker-id": "NAME",
        "update-interval-s": 10,
        "use-remote-logging" : true,
        "upload-config-on-startup" : true
    }

**Comment by MrCook1es** [comment]
it would be nice if you could enter only these variables

```
    // Config for pool
    char poolUrl[64] = "pool-url";
    int poolPort = 3333;

    // Config for CC server
    m_ccHost = "xmrigcc-server-url";
    m_ccPort = 3344;
    m_ccToken = "token";

    m_pools.push_back(new Url(poolUrl, poolPort, poolWallet, poolPassword));
```
but if you set the Options.cpp file this way, the source compile is not completed.
mysys asks for poolwallet and poolpasword..

```
C:/source/src/Options.cpp:430:50: error: 'poolWallet' was not declared in this scope
     m_pools.push_back(new Url(poolUrl, poolPort, poolWallet, poolPassword));
                                                  ^~~~~~~~~~
C:/source/src/Options.cpp:430:50: note: suggested alternative: 'poolPort'
     m_pools.push_back(new Url(poolUrl, poolPort, poolWallet, poolPassword));
                                                  ^~~~~~~~~~
                                                  poolPort
C:/source/src/Options.cpp:430:62: error: 'poolPassword' was not declared in this scope
     m_pools.push_back(new Url(poolUrl, poolPort, poolWallet, poolPassword));
                                                              ^~~~~~~~~~~~
C:/source/src/Options.cpp:430:62: note: suggested alternative: 'poolPort'
     m_pools.push_back(new Url(poolUrl, poolPort, poolWallet, poolPassword));

```

It is essential to be able to set these 2 fields manually:
"pass": "NAME",
"worker-id": "NAME",


in order to have a config.json file similar to this:
```
	"pools": [
        {
            "pass": "NAME",
            "use-tls" : false,
            "keepalive": true,
            "nicehash": true
        }
    ],
    "cc-client": {
        "worker-id": "NAME",
    }

```

**Comment by djfinch** [comment]
Oh c'mon, you cannot remove declared string and leave it elsewhere.
You can try to investigate... This below is the last advise.
`pool_options` array holding things you need. 
https://github.com/bendr0id/xmrigCC/blob/master/src/Options.cpp#L248

**Comment by MrCook1es** [comment]
@djfinch sorry for my mistake! and thanks for the reply.
```
    // Config for pool
    char poolUrl[64] = "pool-url";
    int poolPort = 3333;

    // Config for CC server
    m_ccHost = "xmrigcc-server-url";
    m_ccPort = 3344;
    m_ccToken = "token";

    m_pools.push_back(new Url(poolUrl, poolPort));
```

the basic part works fine.
the problem is set "pool pass" & "worker-id" in the config.
Whatever I do, the hostname is always shown to me: (//note)
`"worker-id": "TEST",                      // custom worker-id for CC Server (otherwise hostname is used)`


```
static struct option const api_options[] = {
    { "port",          1, nullptr, 4000 },
    { "access-token",  1, nullptr, 4001 },
    { "worker-id",     1, nullptr, 4002 },
    { nullptr, 0, nullptr, 0 }
};
```

How does this format work?
example:
```
static struct option const cc_client_options[] = {
    { "url",                    1, nullptr, 4003 },
    { "access-token",           1, nullptr, 4004 },
    { "worker-id",              1, nullptr, 4005 },
```

How does this format work?
I'm doing some testing modifying the file, but I do not get results.
the parts in my config.json file `"worker-id": "TEST" & "pool pass" they are always ignored :'(
I do not know if I could explain myself. I do not know where to bump my head...

**Comment by MrCook1es** [comment]
any change I make to the Options.cpp file works, but makes values in the config.json file useless.
I cant undestand how it works.

After I use the code:
```
    char poolUrl[64] = "pool";
    int poolPort = port;
	
    m_pools.push_back(new Url(poolUrl, poolPort));
```
whatever is written in the Option.cpp file is not considered

**Comment by Bendr0id** [comment]
Man, this is a trivial thing. And this is a bug tracker, not a 1x1 c/c++ training camp.

Try to get some c/c++ knowledge first.

Then:

-> Parse the config file (its already done in the code), if it doesn't contain a valid pool configuration, add a new Pool with the hardcoded values. Same for CC Server. 

The code is almost there which does similar checks, for example it is printing out an error that neither a pool nor a valid a cc configuration was found. 

Send me some xmr and i'll do the code if you're not able.

**Comment by MrCook1es** [comment]
the point is this: -> https://github.com/Bendr0id/xmrigCC/issues/230#issuecomment-461041984

I'm a student, I'm starting to approach programming and I find it very stimulating. Since the project is public on github, I thought the spirit was that of supporting ideas and knowledge.

You are making me realize that I am asking a lot ..
I did not want to ask someone else to do it, but if possible, explain to me and help me understand that the data is related.
