### ISSUE TITLE
Dashboard not connect to server

### ISSUE THREAD

**Issue by DEATHMAN3452** [Bendr0id/xmrigCC#231]
Server starting
Miner starting
miner connect to server fine!
Dashboard empty.
Windows 10
local net
how Fix?

**Comment by Bendr0id** [comment]
I'm pretty sure you just opened the index.html file. Right?

There is a guide:

https://github.com/Bendr0id/xmrigCC/wiki/XMRigCCServer-Dashboard

**Comment by DEATHMAN3452** [comment]
thanks for the help! did not finish reading the wiki ((
