### ISSUE TITLE
support the new algorithm of March 9?

### ISSUE THREAD

**Issue by fakeptolemei** [Bendr0id/xmrigCC#233]
Will xmrigCC support the new algorithm of March 9?

**Comment by Bendr0id** [comment]
Most probably yes.

**Comment by ruptse** [comment]
Any idea when? So miners like us can prepare.

**Comment by Bendr0id** [comment]
GPU is done. For CPU Everything except the asm optimization is done. Need to finish that, but I think on monday/to.

**Comment by Bendr0id** [comment]
ASM optimizations done. Needs testing and a fix for ARM. Will be most propably finished tomorrow. So Release tomorrow or on Tuesday.

**Comment by Bendr0id** [comment]
additionally: XCASH and Zelerius both with ASM optimizations

**Comment by Bendr0id** [comment]
Merged
