### ISSUE TITLE
Please add support for new custom algorithm CryptoNight Heavy X 

### ISSUE THREAD

**Issue by AnimusXCASH** [Bendr0id/xmrigCC#234]
Greetings,
I am from X-Cash team. I would like to kindly ask you if you can add our new custom algorithm to your mining software.
Proof Of Work algorithm was changed from Cryptonight V8 to modified Cryptonight HeavyX, to try to prevent ASICs and or FPGAs from mining on the network. This means as well that we are now nicehash resistant.

Daemon: https://github.com/X-CASH-official/X-CASH/releases/tag/1.5.0

You can reach us through the Discord community if any further information required:
https://discord.gg/sr5G3ch

Thank you for your time.
brg

Lovro
Marketing and Community Manager
X-Cash Team

**Comment by Bendr0id** [comment]
Will be integrated in the next release.

**Comment by AnimusXCASH** [comment]
thank you very much. any ETA?

**Comment by Bendr0id** [comment]
Monday/Tuesday

**Comment by Bendr0id** [comment]
Merged
