### ISSUE TITLE
xmrigCCServer Push Service : Disable

### ISSUE THREAD

**Issue by roel-co** [Bendr0id/xmrigCC#235]
Hi
My xmrigCCServer push service always disable, hot to enable it?

linux@miner:~/xmrigCC$ ./xmrigCCServer
 * VERSIONS:     XMRigCC/1.8.13 (based on XMRig) libuv/1.8.0 gcc/5.4.0 (RELEASE with TLS)
 * **PUSHSERVICE:  Disabled**
 * COMMANDS:     quit
[2019-03-04 00:37:00] XMRigCC Server started on Port: 3344

**Comment by djfinch** [comment]
Yo have to configure it before. Use WIKI.
Everything works well...
``` 
 * VERSIONS:     XMRigCC/1.8.13 (based on XMRig) libuv/1.18.0 gcc/7.3.0 (RELEASE with TLS)     
 * PUSHSERVICE:  Telegram  
```

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/wiki

There is a how-to for pushover and telegram
