### ISSUE TITLE
CCX support

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#238]
Does the new version 1.9.0 support conceal/ccx algo?

**Comment by Bendr0id** [comment]
No, will look into it for the next release.

**Comment by Miner1305** [comment]
any workaround ?

**Comment by Miner1305** [comment]
any update regarding ccx algo support ?

**Comment by Miner1305** [comment]
please support ccx algo

**Comment by Bendr0id** [comment]
CCX seems to be very inactive. dont know if its worth. Even their own implementation/miner is pure crap.

**Comment by Miner1305** [comment]
fomo :)
would be really helpful if you could add support for this in coming release

**Comment by Bendr0id** [comment]
Done. But its not ASM optimized since the original miner and xmr-stak haven't done that aswell.
