### ISSUE TITLE
Auto-Updates

### ISSUE THREAD

**Issue by mike2246** [Bendr0id/xmrigCC#239]
Is there anyway to incorporate Auto-Updates or Updating from Dashboard? When you have 15-20 PC's it's tedious to login to all of them to update.

**Comment by Bendr0id** [comment]
Its in development since a while, but since every few days a coin decided to do its unique algo i'm busy with implementing them.

**Comment by uz-spark** [comment]
That would be killer feature. Crossing fingers for Ben to implement it some day.

**Comment by boli** [comment]
If we can't have autoupdates yet - could we have unchanging links to the 'latest' binaries?

At the moment we have URLs like 

https://github.com/Bendr0id/xmrigCC/releases/download/2.9.5/xmrigCC-2.9.5-gcc-win64.zip
or
https://github.com/Bendr0id/xmrigCC/releases/download/2.9.5/xmrigCC-2.9.5-linux-generic-amd64.tar.gz

and its easily understandable, so thats good, but maybe we could also have a redirect like

https://github.com/Bendr0id/xmrigCC/releases/download/latest/xmrigCC-latest-gcc-win64.zip
or
https://github.com/Bendr0id/xmrigCC/releases/download/latest/xmrigCC-latest-linux-generic-amd64.tar.gz

...it would make it easier to script updates.
