### ISSUE TITLE
Cannot build with with api support at MSYS2 and GCC 8.3

### ISSUE THREAD

**Issue by borodamd** [Bendr0id/xmrigCC#244]
**Was try to build latest version on windows, but it failed with:**
[ 50%] Linking CXX executable xmrigDaemon.exe
[ 50%] Built target cpuid
[ 51%] Building CXX object CMakeFiles/xmrig_tls.dir/src/net/BoostTlsConnection.cpp.obj
[ 51%] Built target xmrigDaemon
[ 52%] Linking CXX static library libxmrig_cc_common.a
[ 52%] Built target xmrig_cc_common
[ 53%] Linking CXX static library libxmrig_os_dependencies.a
[ 53%] Built target xmrig_os_dependencies
[ 54%] Linking CXX static library libxmrig_common.a
[ 54%] Built target xmrig_common
[ 55%] Linking CXX static library libxmrig_common_cc.a
[ 55%] Built target xmrig_common_cc
[ 56%] Linking CXX static library libxmrig_tls.a
[ 56%] Built target xmrig_tls
make: *** [Makefile:84: all] Error 2

**If i disable TLS, it failed with:**
[ 42%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.obj
[ 44%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.obj
[ 45%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Cpu.cpp.obj
[ 46%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.obj
[ 47%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Platform.cpp.obj
[ 48%] Linking CXX static library libxmrig_cpuid.a
In file included from C:/msys64/home/Administrator/xmrigCC/src/Mem_win.cpp:31:
C:/msys64/home/Administrator/xmrigCC/src/crypto/CryptoNight.h:79:28: warning: 'variant_xtl_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
C:/msys64/home/Administrator/xmrigCC/src/crypto/CryptoNight.h:78:28: warning: 'variant1_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
[ 50%] Linking C static library libcpuid.a
[ 51%] Linking CXX executable xmrigDaemon.exe
[ 52%] Linking CXX static library libxmrig_cc_common.a
[ 52%] Built target xmrig_cpuid
[ 52%] Built target cpuid
[ 52%] Built target xmrigDaemon
[ 52%] Built target xmrig_cc_common
[ 53%] Linking CXX static library libxmrig_os_dependencies.a
[ 53%] Built target xmrig_os_dependencies
[ 54%] Linking CXX static library libxmrig_common_cc.a
[ 54%] Built target xmrig_common_cc
[ 55%] Linking CXX static library libxmrig_common.a
[ 55%] Built target xmrig_common
make: *** [Makefile:84: all] Error 2

**String what i use for build is:**

 cmake .. -G "Unix Makefiles" -DWITH_HTTPD=ON -DWITH_TLS=OFF -DWITH_CC_SERVER=OFF -DUV_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libuv\x64\include" -DUV_LIBRARY="c:\xmrigCC-deps\gcc\libuv\x64\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\lib\libmicrohttpd.a" -DBOOST_ROOT="c:\msys64\home\Administrator\boost_1_67_0" -DBoost_SYSTEM_LIBRARY="c:\msys64\home\Administrator\boost_1_67_0\stage\lib\libboost_system-mgw82-mt-x64-1_67.a"

**Help, please with this issue**

**Comment by Bendr0id** [comment]
Your post doesn't contain the error. To help I need to see the error, you just sended the result.

**Comment by borodamd** [comment]
Sorry, but i don't clear understand where i can get error self. I just need start make with VERBOSE=1 -j flag and give output or i need to post content of some other file?

**Comment by Bendr0id** [comment]
No the error should be already above the lines you pasted..

**Comment by borodamd** [comment]
**Here is all output:**

Administrator@MAILS MINGW64 ~/xmrigCC/build
# make -j
Scanning dependencies of target xmrigDaemon
Scanning dependencies of target xmrig_cpuid
Scanning dependencies of target xmrig_asm
Scanning dependencies of target cpuid
Scanning dependencies of target xmrig_cc_common
[  1%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.obj
[  3%] Building RC object CMakeFiles/xmrigDaemon.dir/res/app.rc.obj
[  4%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_cpuid.cpp.obj
Scanning dependencies of target xmrig_common
Scanning dependencies of target xmrig_os_dependencies
[  6%] Building ASM object CMakeFiles/xmrig_asm.dir/src/crypto/asm/win/cn_main_loop_win_gcc.S.obj
[  7%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.obj
[  9%] Building ASM object CMakeFiles/xmrig_asm.dir/src/crypto/asm/win/CryptonightR_template.S.obj
[ 12%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.obj
[ 12%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.obj
[ 13%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.obj
[ 15%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.obj
C:/msys64/home/Administrator/xmrigCC/src/crypto/asm/win/cn_main_loop_win_gcc.S:54:11: fatal error: ../cnv1_main_loop_sandybridge.inc: No such file or directory
  #include "../cnv1_main_loop_sandybridge.inc"
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[ 18%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.obj
[ 18%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.obj
make[2]: *** [CMakeFiles/xmrig_asm.dir/build.make:63: CMakeFiles/xmrig_asm.dir/src/crypto/asm/win/cn_main_loop_win_gcc.S.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 19%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/GPUInfo.cpp.obj
[ 21%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.obj
[ 22%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.obj
[ 25%] Building RC object CMakeFiles/xmrig_os_dependencies.dir/res/app.rc.obj
[ 24%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.obj
[ 27%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.obj
[ 30%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.obj
[ 28%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.obj
[ 31%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.obj
[ 33%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_win.cpp.obj
[ 34%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_win.cpp.obj
make[1]: *** [CMakeFiles/Makefile2:221: CMakeFiles/xmrig_asm.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_win.cpp.obj
[ 37%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.obj
[ 40%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/RemoteLog.cpp.obj
[ 39%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_win.cpp.obj
C:/msys64/home/Administrator/xmrigCC/src/Cpu_cpuid.cpp: In member function 'void CpuImpl::initCommon()':
C:/msys64/home/Administrator/xmrigCC/src/Cpu_cpuid.cpp:45:12: warning: 'char* strncpy(char*, const char*, size_t)' output may be truncated copying 63 bytes from a string of length 63 [-Wstringop-truncation]
     strncpy(m_brand, data.brand_str, sizeof(m_brand) - 1);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from C:/msys64/home/Administrator/xmrigCC/src/Mem.cpp:28:
C:/msys64/home/Administrator/xmrigCC/src/crypto/CryptoNight.h:79:28: warning: 'variant_xtl_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
C:/msys64/home/Administrator/xmrigCC/src/crypto/CryptoNight.h:78:28: warning: 'variant1_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
[ 42%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.obj
[ 43%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.obj
[ 45%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.obj
[ 46%] Linking CXX static library libxmrig_cpuid.a
[ 48%] Linking C static library libcpuid.a
In file included from C:/msys64/home/Administrator/xmrigCC/src/Mem_win.cpp:31:
C:/msys64/home/Administrator/xmrigCC/src/crypto/CryptoNight.h:79:28: warning: 'variant_xtl_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
C:/msys64/home/Administrator/xmrigCC/src/crypto/CryptoNight.h:78:28: warning: 'variant1_table' defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
[ 50%] Linking CXX executable xmrigDaemon.exe
[ 50%] Built target xmrig_cpuid
[ 50%] Built target cpuid
[ 50%] Built target xmrigDaemon
[ 51%] Linking CXX static library libxmrig_cc_common.a
[ 51%] Built target xmrig_cc_common
[ 53%] Linking CXX static library libxmrig_os_dependencies.a
[ 53%] Built target xmrig_os_dependencies
[ 54%] Linking CXX static library libxmrig_common.a
[ 54%] Built target xmrig_common
make: *** [Makefile:84: all] Error 2

**Comment by Bendr0id** [comment]
But anyways. Please keep in mind that the API isn't maintained. 
Even if you can get it to compile it is in a very old stage (most propably from the time when i forked).

Why do you need the API? You can get all the info from the CCServer aswell. It has a REST API.

You can find the documentation here:
https://github.com/Bendr0id/xmrigCC/wiki/XMRigCCServer-API

**Comment by Bendr0id** [comment]
There is your error:

```
C:/msys64/home/Administrator/xmrigCC/src/crypto/asm/win/cn_main_loop_win_gcc.S:54:11: fatal error: ../cnv1_main_loop_sandybridge.inc: No such file or directory
#include "../cnv1_main_loop_sandybridge.inc"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by borodamd** [comment]
Thanks. I fixed it. I was trying to build from "build" directory with cmake .. 
Maybe from this it cannot found necessary libraries.

**Comment by Bendr0id** [comment]
Hmm. Out of source building should work.
It was fixed with this commit:

https://github.com/Bendr0id/xmrigCC/commit/6dfa88a391e9d830bace4c261925cc2943272ae7

Can you check if the code is in place?

**Comment by borodamd** [comment]
No. Code is not exact you provide in file asm.cmake

I have cloned by git sources before compiling

Code is:

 if (CMAKE_C_COMPILER_ID MATCHES MSVC)
135     enable_language(ASM_MASM)
136     set(XMRIG_ASM_FILE "src/crypto/asm/win/cn_main_loop.asm"
137                        "src/crypto/asm/win/CryptonightR_template.asm")
138     set_property(SOURCE ${XMRIG_ASM_FILE} PROPERTY ASM_MASM)
139     include_directories(${CMAKE_BINARY_DIR}/src/crypto/asm/win)
140 else()
141     enable_language(ASM)
142
143     if (WIN32 AND CMAKE_C_COMPILER_ID MATCHES GNU)
144         set(XMRIG_ASM_FILE "src/crypto/asm/win/cn_main_loop_win_gcc.S"
145                            "src/crypto/asm/win/CryptonightR_template.S")
146     else()
147         set(XMRIG_ASM_FILE "src/crypto/asm/cn_main_loop.S"
148                            "src/crypto/asm/CryptonightR_template.S")
149     endif()
150
151     set_property(SOURCE ${XMRIG_ASM_FILE} PROPERTY C)
152     include_directories(${CMAKE_BINARY_DIR}/src/crypto/asm/)
153 endif()
154
155 add_library(xmrig_asm STATIC ${XMRIG_ASM_FILE})
156 set_property(TARGET xmrig_asm PROPERTY LINKER_LANGUAGE C)
157
