### ISSUE TITLE
simple way to embedded config in xmrig

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#245]
this is an excellent starting point to work on: https://github.com/xmrig/xmrig/issues/957#issuecomment-468890667

> This feature added to [dev](https://github.com/xmrig/xmrig/commits/dev) branch.
> 
> How to use:
> 
>     1. Use cmake option `-DWITH_EMBEDDED_CONFIG=ON` to enable this feature.
> 
>     2. Edit/replace config sample in code https://github.com/xmrig/xmrig/blob/dev/src/core/ConfigLoader_default.h#L35
> 
>     3. Recompile the miner.
> 
> 
> Please note embedded config used only if miner fails to load external configuration from file or command line.
> Also fixed bug: `m_enabled` field was uninitialized in Pool class.

**Comment by Bendr0id** [comment]
go ahead

**Comment by MrCook1es** [comment]
in this way it becomes the simplest thing on earth
a new file "ConfigLoader_default.h" where to set everything up simply:

https://github.com/xmrig/xmrig/blob/dev/src/core/ConfigLoader_default.h#L35

**Comment by Bendr0id** [comment]
Sorry for the late response. Could you check if that works as expected..? Branch: embedded_config

**Comment by MrCook1es** [comment]
@Bendr0id it works properly.
if after executing the miner I go to modify a value and save the new config with "push miner config", the "config.json" file is correctly created and the new values from that file are read.
very good.
_________________

would be cool if at the moment when I make a subsequent change, such as changing the url pool "pass" or "worker-id", when I go to save "push miner config" instead of going to create the whole configuration, it would be cool if it went to create me only the 2 lines where I made the change.

config.json
```
{

    "pools": [
        {
            "pass": "test1",
        }
    ],
    "cc-client": {
        "worker-id": "test2",
    }
}
```

**Comment by hirdeshsaxena** [comment]
hi this solution is not working can you help. 

I have made the change in  Use cmake option `-DWITH_EMBEDDED_CONFIG=ON`

and in \src\core\config\Config_default.h  

but not working still crash have to provide external config.json

**Comment by Bendr0id** [comment]
Just verified, it works perfectly fine.

`-DWITH_EMBEDDED_CONFIG=ON` and just edit the file `src/core/config/Config_default.json`. 

Make sure you **DONT** break the json, that could be your problem.

When you set the cmake flags, make sure you delete the CMakeCache.txt before.
