### ISSUE TITLE
[windows] How to set process name on Task Manager

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#246]
Hi, is it possible to show the process / exe name in the Task Manager?

I am using precompiled build, I try to change **"background": false/true** , I also try to run xmrigMiner.exe with --daemonized option but the process name always remains "blank".

![image](https://user-images.githubusercontent.com/38523505/55413344-771fa380-5569-11e9-837b-2f457779f6ca.png)

**Comment by djfinch** [comment]
https://github.com/Bendr0id/xmrigCC/blob/master/res/app.rc ... Variables are taken from https://github.com/Bendr0id/xmrigCC/blob/master/src/version.h ... Not tested cause I don't have Win.

**Comment by Bendr0id** [comment]
I can't believe that it is with the stock XMRigCC. For me it shows both processes as xmrigDaemon and xmrigMiner with the Icon an its name. Tested on WIN7 and WIN10.

**Comment by MrCook1es** [comment]
it was my mistake.
among all the different attempts and tests I had made a bit of confusion.

In any case, I came to a point, in the file "CMakeLists.txt" there are some words that cannot be used. Probably because they are reserved by Windows. If you use them, the name of the miner disappears. Using different words the problem disappears.
