### ISSUE TITLE
Can not compile 1.9.3 on CentOS 6 with Developer Toolset 7

### ISSUE THREAD

**Issue by agisubagio** [Bendr0id/xmrigCC#249]
I have CentOS 6 with Devtoolset 7 and want to compile the latest xmrigCC, but i've got an error. What should I do?

[root@ftp build]# cmake3 .. -DBOOST_ROOT=/root/boost_1_67_0 -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
-- The C compiler identification is GNU 7.3.1
-- The CXX compiler identification is GNU 7.3.1
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/gcc
-- Check for working C compiler: /opt/rh/devtoolset-7/root/usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/g++
-- Check for working CXX compiler: /opt/rh/devtoolset-7/root/usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib64/libuv.so
CMake Warning at /usr/share/cmake3/Modules/FindBoost.cmake:743 (message):
  Imported targets not available for Boost version 106700
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindBoost.cmake:842 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake3/Modules/FindBoost.cmake:1395 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:135 (find_package)

-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
-- Found OpenSSL: /usr/lib64/libssl.so;/usr/lib64/libcrypto.so (found version "1.0.1e")
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found mhd: /usr/include
Generating ASM files
-- The ASM compiler identification is GNU
-- Found assembler: /opt/rh/devtoolset-7/root/usr/bin/gcc
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Downloads/xmrigCC/build

[root@ftp build]# make -j
Scanning dependencies of target xmrig_cpuid
Scanning dependencies of target cpuid
Scanning dependencies of target xmrigDaemon
Scanning dependencies of target xmrig_tls
Scanning dependencies of target xmrig_common
Scanning dependencies of target xmrig_cc_common
Scanning dependencies of target xmrig_os_dependencies
Scanning dependencies of target xmrig_common_cc
Scanning dependencies of target xmrig_asm
[  1%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[  2%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_cpuid.cpp.o
[  3%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[  4%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
[  6%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[  7%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.o
[  8%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.o
[  9%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 10%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Console.cpp.o
[ 13%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Mem.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/GPUInfo.cpp.o
[ 15%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
[ 17%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/net/Url.cpp.o
[ 19%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.o
[ 20%] Building ASM object CMakeFiles/xmrig_asm.dir/src/crypto/asm/cn_main_loop.S.o
[ 21%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Options.cpp.o
[ 23%] Building ASM object CMakeFiles/xmrig_asm.dir/src/crypto/asm/CryptonightR_template.S.o
[ 24%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.o
[ 26%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[ 28%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/log/ConsoleLog.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_unix.cpp.o
[ 31%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o
[ 32%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/log/FileLog.cpp.o
[ 34%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
[ 35%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
[ 36%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_unix.cpp.o
[ 37%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/log/RemoteLog.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/log/SysLog.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/log/Log.cpp.o
[ 42%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/RemoteLog.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Platform.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.o
[ 46%] Building CXX object CMakeFiles/xmrig_common_cc.dir/src/Cpu.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.o
[ 48%] Linking C static library libxmrig_asm.a
/root/Downloads/xmrigCC/src/Console.cpp: In constructor ‘Console::Console(IConsoleListener*)’:
/root/Downloads/xmrigCC/src/Console.cpp:42:29: error: ‘UV_TTY_MODE_RAW’ was not declared in this scope
     uv_tty_set_mode(&m_tty, UV_TTY_MODE_RAW);
                             ^~~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/Console.cpp: In constructor ‘Console::Console(IConsoleListener*)’:
/root/Downloads/xmrigCC/src/Console.cpp:42:29: error: ‘UV_TTY_MODE_RAW’ was not declared in this scope
     uv_tty_set_mode(&m_tty, UV_TTY_MODE_RAW);
                             ^~~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/Console.cpp:43:98: error: invalid conversion from ‘void (*)(uv_handle_t*, size_t, uv_buf_t*) {aka void (*)(uv_handle_s*, long unsigned int, uv_buf_t*)}’ to ‘uv_alloc_cb {aka uv_buf_t (*)(uv_handle_s*, long unsigned int)}’ [-fpermissive]
     uv_read_start(reinterpret_cast<uv_stream_t*>(&m_tty), Console::onAllocBuffer, Console::onRead);
                                                                                                  ^
In file included from /root/Downloads/xmrigCC/src/Console.h:28:0,
                 from /root/Downloads/xmrigCC/src/Console.cpp:25:
/usr/include/uv.h:618:15: note:   initializing argument 2 of ‘int uv_read_start(uv_stream_t*, uv_alloc_cb, uv_read_cb)’
 UV_EXTERN int uv_read_start(uv_stream_t*, uv_alloc_cb alloc_cb,
               ^~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/Console.cpp:43:98: error: invalid conversion from ‘void (*)(uv_stream_t*, ssize_t, const uv_buf_t*) {aka void (*)(uv_stream_s*, long int, const uv_buf_t*)}’ to ‘uv_read_cb {aka void (*)(uv_stream_s*, long int, uv_buf_t)}’ [-fpermissive]
     uv_read_start(reinterpret_cast<uv_stream_t*>(&m_tty), Console::onAllocBuffer, Console::onRead);
                                                                                                  ^
In file included from /root/Downloads/xmrigCC/src/Console.h:28:0,
                 from /root/Downloads/xmrigCC/src/Console.cpp:25:
/usr/include/uv.h:618:15: note:   initializing argument 3 of ‘int uv_read_start(uv_stream_t*, uv_alloc_cb, uv_read_cb)’
 UV_EXTERN int uv_read_start(uv_stream_t*, uv_alloc_cb alloc_cb,
               ^~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
/root/Downloads/xmrigCC/src/Console.cpp:43:98: error: invalid conversion from ‘void (*)(uv_handle_t*, size_t, uv_buf_t*) {aka void (*)(uv_handle_s*, long unsigned int, uv_buf_t*)}’ to ‘uv_alloc_cb {aka uv_buf_t (*)(uv_handle_s*, long unsigned int)}’ [-fpermissive]
     uv_read_start(reinterpret_cast<uv_stream_t*>(&m_tty), Console::onAllocBuffer, Console::onRead);
                                                                                                  ^
In file included from /root/Downloads/xmrigCC/src/Console.h:28:0,
                 from /root/Downloads/xmrigCC/src/Console.cpp:25:
/usr/include/uv.h:618:15: note:   initializing argument 2 of ‘int uv_read_start(uv_stream_t*, uv_alloc_cb, uv_read_cb)’
 UV_EXTERN int uv_read_start(uv_stream_t*, uv_alloc_cb alloc_cb,
               ^~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/Console.cpp:43:98: error: invalid conversion from ‘void (*)(uv_stream_t*, ssize_t, const uv_buf_t*) {aka void (*)(uv_stream_s*, long int, const uv_buf_t*)}’ to ‘uv_read_cb {aka void (*)(uv_stream_s*, long int, uv_buf_t)}’ [-fpermissive]
     uv_read_start(reinterpret_cast<uv_stream_t*>(&m_tty), Console::onAllocBuffer, Console::onRead);
                                                                                                  ^
In file included from /root/Downloads/xmrigCC/src/Console.h:28:0,
                 from /root/Downloads/xmrigCC/src/Console.cpp:25:
/usr/include/uv.h:618:15: note:   initializing argument 3 of ‘int uv_read_start(uv_stream_t*, uv_alloc_cb, uv_read_cb)’
 UV_EXTERN int uv_read_start(uv_stream_t*, uv_alloc_cb alloc_cb,
               ^~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmrig_common.dir/build.make:63: CMakeFiles/xmrig_common.dir/src/Console.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [CMakeFiles/xmrig_common_cc.dir/build.make:63: CMakeFiles/xmrig_common_cc.dir/src/Console.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 48%] Built target xmrig_asm
[ 50%] Linking C static library libcpuid.a
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp: In constructor ‘ConsoleLog::ConsoleLog(bool)’:
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:54:29: error: ‘UV_TTY_MODE_NORMAL’ was not declared in this scope
     uv_tty_set_mode(&m_tty, UV_TTY_MODE_NORMAL);
                             ^~~~~~~~~~~~~~~~~~
[ 51%] Building CXX object CMakeFiles/xmrig_tls.dir/src/net/BoostTlsConnection.cpp.o
In file included from /root/Downloads/xmrigCC/src/Mem.cpp:28:0:
/root/Downloads/xmrigCC/src/crypto/CryptoNight.h:80:28: warning: ‘variant_xtl_table’ defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/crypto/CryptoNight.h:79:28: warning: ‘variant1_table’ defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp: In constructor ‘ConsoleLog::ConsoleLog(bool)’:
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:54:29: error: ‘UV_TTY_MODE_NORMAL’ was not declared in this scope
     uv_tty_set_mode(&m_tty, UV_TTY_MODE_NORMAL);
                             ^~~~~~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:54:29: note: suggested alternative: ‘POSIX_FADV_NORMAL’
     uv_tty_set_mode(&m_tty, UV_TTY_MODE_NORMAL);
                             ^~~~~~~~~~~~~~~~~~
                             POSIX_FADV_NORMAL
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp: In member function ‘void ConsoleLog::print(__va_list_tag*)’:
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:154:9: error: ‘uv_try_write’ was not declared in this scope
         uv_try_write(m_stream, &m_uvBuf, 1);
         ^~~~~~~~~~~~
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:154:9: note: suggested alternative: ‘uv_fs_write’
         uv_try_write(m_stream, &m_uvBuf, 1);
         ^~~~~~~~~~~~
         uv_fs_write
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:54:29: note: suggested alternative: ‘POSIX_FADV_NORMAL’
     uv_tty_set_mode(&m_tty, UV_TTY_MODE_NORMAL);
                             ^~~~~~~~~~~~~~~~~~
                             POSIX_FADV_NORMAL
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp: In member function ‘void ConsoleLog::print(__va_list_tag*)’:
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:154:9: error: ‘uv_try_write’ was not declared in this scope
         uv_try_write(m_stream, &m_uvBuf, 1);
         ^~~~~~~~~~~~
/root/Downloads/xmrigCC/src/log/ConsoleLog.cpp:154:9: note: suggested alternative: ‘uv_fs_write’
         uv_try_write(m_stream, &m_uvBuf, 1);
         ^~~~~~~~~~~~
         uv_fs_write
[ 51%] Built target cpuid
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [CMakeFiles/xmrig_common.dir/build.make:159: CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [CMakeFiles/xmrig_common_cc.dir/build.make:159: CMakeFiles/xmrig_common_cc.dir/src/log/ConsoleLog.cpp.o] Error 1
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
In file included from /root/Downloads/xmrigCC/src/Mem_unix.cpp:28:0:
/root/Downloads/xmrigCC/src/crypto/CryptoNight.h:80:28: warning: ‘variant_xtl_table’ defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/crypto/CryptoNight.h:79:28: warning: ‘variant1_table’ defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
In file included from /root/Downloads/xmrigCC/src/Mem.cpp:28:0:
/root/Downloads/xmrigCC/src/crypto/CryptoNight.h:80:28: warning: ‘variant_xtl_table’ defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant_xtl_table[256];
                            ^~~~~~~~~~~~~~~~~
/root/Downloads/xmrigCC/src/crypto/CryptoNight.h:79:28: warning: ‘variant1_table’ defined but not used [-Wunused-variable]
 alignas(64) static uint8_t variant1_table[256];
                            ^~~~~~~~~~~~~~
[ 52%] Linking CXX executable xmrigDaemon
[ 53%] Linking CXX static library libxmrig_cpuid.a
[ 53%] Built target xmrig_cpuid
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
/root/Downloads/xmrigCC/src/Options.cpp: In member function ‘bool Options::getJSON(const char*, rapidjson::Document&)’:
/root/Downloads/xmrigCC/src/Options.cpp:500:76: error: could not convert ‘fd’ from ‘const int’ to ‘uv_err_t {aka uv_err_s}’
         fprintf(stderr, "unable to open %s: %s\n", fileName, uv_strerror(fd));
                                                                            ^
[ 53%] Built target xmrigDaemon
/root/Downloads/xmrigCC/src/Options.cpp: In member function ‘bool Options::getJSON(const char*, rapidjson::Document&)’:
/root/Downloads/xmrigCC/src/Options.cpp:500:76: error: could not convert ‘fd’ from ‘const int’ to ‘uv_err_t {aka uv_err_s}’
         fprintf(stderr, "unable to open %s: %s\n", fileName, uv_strerror(fd));
                                                                            ^
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [CMakeFiles/xmrig_common_cc.dir/build.make:135: CMakeFiles/xmrig_common_cc.dir/src/Options.cpp.o] Error 1
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [CMakeFiles/xmrig_common.dir/build.make:135: CMakeFiles/xmrig_common.dir/src/Options.cpp.o] Error 1
/root/Downloads/xmrigCC/src/api/ApiState.cpp: In member function ‘void ApiState::genId()’:
/root/Downloads/xmrigCC/src/api/ApiState.cpp:143:53: error: no match for ‘operator<’ (operand types are ‘uv_err_t {aka uv_err_s}’ and ‘int’)
     if (uv_interface_addresses(&interfaces, &count) < 0) {
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~
/root/Downloads/xmrigCC/src/api/ApiState.cpp:150:58: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             const size_t addrSize = sizeof(interfaces[i].phys_addr);
                                                          ^~~~~~~~~
/root/Downloads/xmrigCC/src/api/ApiState.cpp:154:41: error: ‘uv_interface_address_t {aka struct uv_interface_address_s}’ has no member named ‘phys_addr’
             memcpy(input, interfaces[i].phys_addr, addrSize);
                                         ^~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-class-memaccess’
make[2]: *** [CMakeFiles/xmrig_os_dependencies.dir/build.make:87: CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:375: CMakeFiles/xmrig_os_dependencies.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 54%] Linking CXX static library libxmrig_cc_common.a
[ 54%] Built target xmrig_cc_common
make[1]: *** [CMakeFiles/Makefile2:185: CMakeFiles/xmrig_common.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:296: CMakeFiles/xmrig_common_cc.dir/all] Error 2
[ 56%] Linking CXX static library libxmrig_tls.a
[ 56%] Built target xmrig_tls
make: *** [Makefile:84: all] Error 2

**Comment by Bendr0id** [comment]
Looks like your libuv is outdated. Please compile it yourself or try reinstalling the package with:

`yum install libuv-devel`

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/wiki/Build-RedHat%5CCentOS

**Comment by agisubagio** [comment]
> 
> 
> Looks like your libuv is outdated. Please compile it yourself or try reinstalling the package with:
> 
> `yum install libuv-devel`

problem solved... thanks...
