### ISSUE TITLE
Clicking on 'Edit minor config' button selects/deselects the respective row

### ISSUE THREAD

**Issue by sebastianstolzenberg** [Bendr0id/xmrigCC#25]

**Comment by MrCook1es** [comment]
i confirm, same issue.

**Comment by djfinch** [comment]
Actually... This is very useful...
Edited configs stays selected so you can push them after. Without this you have to figure out what needs to be selected and pushed. I want to stay with current behavior.

**Comment by Bendr0id** [comment]
This is expected behavior.
