### ISSUE TITLE
is there a proxy?

### ISSUE THREAD

**Issue by sherifomran** [Bendr0id/xmrigCC#252]
does cc have a proxy? Does the server acts as a proxy similar to XNP? or do i still need to install a XNP on the server side ? what is the benefit over xnp ! i don't see it still.

thank you

**Comment by djfinch** [comment]
https://github.com/Bendr0id/xmrigCC/issues/150

**Comment by Bendr0id** [comment]
Cc is not a proxy. It's a remote control and dashboard for your miners.
