### ISSUE TITLE
detecting Video Cards

### ISSUE THREAD

**Issue by sherifomran** [Bendr0id/xmrigCC#253]
is it possible to detect which miner has video cards and submit a sub job to those miners ?

**Comment by djfinch** [comment]
Not possible yet. xmrigCC is not all-in-one miner like xmr-stak. Anyway, many miners have OpenCL compatible videocard (including integrated Intel ones) but they are mostly worthless (CPU integrated card hash power is very low and CPU+GPU will reduce hashing speed of CPU itself).

**Comment by sherifomran** [comment]
are you aware of htcondor?your program is something similar but for miners only. If you add such checkers, you would come one step further near to the program.Think about submitting a job that can be something else than mining for example R&D calculating genetic algorithms or others.

    On Friday, June 14, 2019, 9:22:13 AM GMT+2, djfinch <notifications@github.com> wrote:  
 
 
Not possible yet. xmrigCC is not all-in-one miner like xmr-stak. Anyway, many miners have OpenCL compatible videocard (including integrated Intel ones) but they are mostly worthless (CPU integrated card hash power is very low and CPU+GPU will reduce hashing speed of CPU itself).

**Comment by Bendr0id** [comment]
finally released 3.0.0
