### ISSUE TITLE
Automatic restart if the hash rate drops to 0

### ISSUE THREAD

**Issue by distributorofpain** [Bendr0id/xmrigCC#254]
I have two amd gpu miners that keep dropping to 0.  The last time it happened, they had both done it within 5 minutes of each other.  The nvidia miner running on the same network did not stop.  When they stop, the screen output is just the hashrate output showing 0.  There are no job notifications passing back and forth.

I stop and then start the minerdaemon on both machines and they start mining again.  I can also use the control console web page to restart the miners.  I havent had to restart the computers to fix this though.  Also one of the machines using the GPU miner is also running the CPU miner.  The CPU miner is not stopping, it keeps going no issues.

When searching through the issues here on github, i found #181 which talks about an auto-restart being added to 1.8.6.  I didnt see a configuration option for it, so i am wondering if i missed something or if it should be doing it but its not working?

I was trying to look at the CC log, but it doesnt seem to rotate, so i am currently trying to dissect the 300MB log file into readable chunks.

Using the latest:  1.9.3 on all the AMD GPU and CPU miners.  ( the nvidia one is using 2.14.4 )

**Comment by Bendr0id** [comment]
First, this is the repo for the CPU miner. The auto restart feature is only available on the AMD miner. 

https://github.com/Bendr0id/xmrigCC-amd

The problem that your amd gpus are dropping to 0 hash most propably is the reason of a crash on the cards kernel/unstable driver or oc. On CPU i've never seen this issue therefor there is no watchdog.

On the AMD miner you can enable the watchdog by modifying these params in the config.json:

```
    "rig-watchdog" : true,                      // enable rig monitor/watchdog
    "reboot-on-cardcrash" : false,              // reboot the miner instead of restart on cardcrash/min rig hashrate error
    "min-rig-hashrate" : 0,                     // minimum rig hashrate for last 60s, when below miner will restart/reboot
```

**Comment by distributorofpain** [comment]
oh my bad, i did not look at the xmrigCC-amd miner configuration, only the cpu and xmrig-cc configs ( i was thinking the xmrig-cc was doing the restart ).  Makes sense the client is handling it.  Thanks!
