### ISSUE TITLE
Impossible to setup threads to cores affinity

### ISSUE THREAD

**Issue by UnclWish** [Bendr0id/xmrigCC#260]
In current threads configuration we can set
threads
multihash-factor
multihash-thread-mask

In any case in thread configuration affinity is auto and miner affines threads to CPU cores automatically.

Is it possible to disable threads affinity to cores, or manual settting this affinities?

**Comment by Bendr0id** [comment]
Ofc you can define that manually. 

There parameter is via cmd-line:
```
 --cpu-affinity                    set process affinity to CPU core(s), mask 0x3 for cores 0 and 1
```

or in the config.json:
```
 "cpu-affinity": "0x3",                       // set process affinity to CPU core(s), mask "0x3" for cores 0 and 1
```

So if you want to have a pattern like this 00110011 for four cores on a 8 core machine it is: 00110011 (binary) to hex -> "0x33"

With the upcoming release it will be simpler.

**Comment by UnclWish** [comment]
Thanks. I'll try it.
But how to disable affinity at all?

**Comment by djfinch** [comment]
You can leave `null` there. Then affinity is driven by OS. But it's always better to set it manually. For example, on macOS it's always managed by ON no matter what is set in affinity field.

**Comment by UnclWish** [comment]
Setting null - is auto and miner just set threads in order 0123 etc.

**Comment by UnclWish** [comment]
And why "safe" parameter forces miner to use only one thread? Even if setted 3 threads, with Safe=true, miner use only one thread at all...

**Comment by djfinch** [comment]
Dynamic changing of threads is not a good idea as this cost some overhead and result will be worse than proper affinity config. `safe = true` does not allow you to set more threads than cores and/or assign more threads if physical L2/L3 cache used by them is not available. E.g. 3MB L2/L3 on die --> CnR need 2MB per thread --> 2 threads are not 'safe' as there is not enough cache for it (CPU with at least 4MB needed)...

**Comment by UnclWish** [comment]
> Dynamic changing of threads is not a good idea as this cost some overhead and result will be worse than proper affinity config.
On some CPU's and systems dynamic cores usage can be usefull... And sometimes even faster.
