### ISSUE TITLE
Compilation with disabled CC_CLIENT and CC_SERVER compiles with CC

### ISSUE THREAD

**Issue by UnclWish** [Bendr0id/xmrigCC#264]
I'm try to compile via MSVS. On CMake disable both WITH_CC_CLIENT and WITH_CC_SERVER to copmpile just miner.
All goes normal, compilation completed. But when I try to start xmrigMiner.exe it wrotes
"XMRigCC is compiled with CC support, please start the daemon instead."

How to disable CC support complitely?

**Comment by djfinch** [comment]
I suppose there is no way to compile just miner because deamon part works also as watcher. This switch is probably there to disable compile for both miner and daemon and compile just CCserver. It does not works as expected though.

**Comment by UnclWish** [comment]
But I compiled 1.9.5 same way and used miner via xmgirMiner.exe not daemon...

**Comment by Bendr0id** [comment]
There is maybe a missing ifdef...

**Comment by Bendr0id** [comment]
for now you can just start xmrigMiner.exe with --daemonized parameter

**Comment by UnclWish** [comment]
Yes, it works this way, thanks!

P.S. Good name for parameter "daemonized"! :)

**Comment by Bendr0id** [comment]
I'll add the missing ifdef later aswell.
