### ISSUE TITLE
I tried to rename the file

### ISSUE THREAD

**Issue by lomas777** [Bendr0id/xmrigCC#265]
I tried to rename the file xmrigDaemon
After renaming, the miner does not start. What needs to be corrected? Or renaming is not allowed?

**Comment by yangsystem** [comment]
You have to compile the miner.

**Comment by lomas777** [comment]
Ok, what needs to be fixed? what commands do you compile?

**Comment by Bendr0id** [comment]
cmake . -DMINER_EXECUTABLE_NAME=whatever -DDAEMON_EXECUTABLE_NAME=whateverdaemon

But if don't want to build it on you own, you just can rename the miner and start it it with --daemonized parameters. The daemon is now only needed for the restart command. Remote update of the config etc. work without the daemon.

**Comment by lomas777** [comment]
Ok, managed to rename. Tell me how to apply the --daemonized parameter?
I would like to launch the miner myself, without daemon

**Comment by uz-spark** [comment]
You can also replace xmrig.exe string in miner binary with your one, no longer than original (5 chars for name) and preserving original string length with null chars at the end.

**Comment by uz-spark** [comment]
Xmrigcc.exe, my bad, 7 symbols then.

**Comment by lomas777** [comment]
Can I specify the --daemonized parameter in the config.json file?

**Comment by Bendr0id** [comment]
@sPk it's xmrigMiner.exe I guess.

Anyways the easiest ist to rename the miner to whatever you want. And start the exe/binary with the command line parameter --daemonized.

OR Put 

"daemonized": true,

 into the config.json as the first element. That should work too.

**Comment by Bendr0id** [comment]
like this:

```
{
    "daemonized": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
...

That works.
```

**Comment by lomas777** [comment]
Thank you!
