### ISSUE TITLE
C:/xmrigCC-2.0.0/src/version.h:65:10: fatal error:

### ISSUE THREAD

**Issue by lomas777** [Bendr0id/xmrigCC#266]
Hi, this is such a compilation error C:/xmrigCC-2.0.0/src/version.h:65:10: fatal error:. Previously successfully compiled. I don’t know where she came from

**Comment by Bendr0id** [comment]
This is not a compile error. This is just the result. Please send the complete compile output with the error. Did you download the release zip or latest master? If the compiler is clang you need to download the latest master, there was an issue with clang in the release.

**Comment by lomas777** [comment]
65 | #include <string>
      |          ^~~~~~~~
compilation terminated.
C:\msys64\mingw64\bin\windres.exe: ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒.
make[2]: *** [CMakeFiles/xmrigDaemon.dir/build.make:77: CMakeFiles/xmrigDaemon.dir/res/app.rc.obj] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:109: CMakeFiles/xmrigDaemon.dir/all] Ошибка 2
make: *** [Makefile:84: all] Ошибка 2

**Comment by Bendr0id** [comment]
Need more lines

**Comment by lomas777** [comment]
Performing Test FEATURE_avx512f_NOFLAG - Failed
-- Performing Test FEATURE_avx512f_FLAG
-- Performing Test FEATURE_avx512f_FLAG - Success
-- argon2: feature 'avx512f' detected!
-- Found OpenSSL: C:/xmrig-deps-3.5/gcc/x64/lib/libcrypto.a (found version "1.1.1c")
-- The ASM compiler identification is GNU
-- Found assembler: C:/msys64/mingw64/bin/cc.exe
-- Configuring done
-- Generating done
-- Build files have been written to: C:/xmrigCC-2.0.0
Scanning dependencies of target xmrig-asm
[  1%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/cn/asm/win64/cn_main_loop.S.obj
[  2%] Building ASM object CMakeFiles/xmrig-asm.dir/src/crypto/cn/asm/CryptonightR_template.S.obj
[  2%] Linking C static library libxmrig-asm.a
[  2%] Built target xmrig-asm
Scanning dependencies of target xmrigDaemon
[  3%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.obj
[  4%] Building RC object CMakeFiles/xmrigDaemon.dir/res/app.rc.obj
In file included from C:/xmrigCC-2.0.0/res/app.rc:2:
C:/xmrigCC-2.0.0/src/version.h:65:10: fatal error: string: No such file or directory
   65 | #include <string>
      |          ^~~~~~~~
compilation terminated.
C:\msys64\mingw64\bin\windres.exe: ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒.
make[2]: *** [CMakeFiles/xmrigDaemon.dir/build.make:77: CMakeFiles/xmrigDaemon.dir/res/app.rc.obj] Ошибка 1
make[1]: *** [CMakeFiles/Makefile2:109: CMakeFiles/xmrigDaemon.dir/all] Ошибка 2
make: *** [Makefile:84: all] Ошибка 2

**Comment by Bendr0id** [comment]
Use latest master not release-2.0 source.

**Comment by lomas777** [comment]
Ok, only yesterday it compiled without errors. Today fails successfully

**Comment by Bendr0id** [comment]
What did you modify compared to my original?

**Comment by lomas777** [comment]
Did not modify anything
RF@console MINGW64 /c/xmrigCC-2.0.0
# cmake . -G "Unix Makefiles" -DXMRIG_DEPS=C:/xmrig-deps-3.5/gcc/x64 && make

**Comment by Bendr0id** [comment]
Try building this:
https://github.com/Bendr0id/xmrigCC/archive/master.zip

**Comment by lomas777** [comment]
Yes, now everything is fine. Thank you)
