### ISSUE TITLE
algo support for cuckoo29s & cn-gpu

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#267]
Hello
does xmrigcc support cuckoo29s & cn-gpu & other cuckroo 
this algo is looking very profitable

**Comment by Bendr0id** [comment]
cn-gpu source is in, can be enabled in the cmake file. I just disabled it because its useless on CPU.

Cockoo29s and other cuckroo algos are perfoming on cpu well but not on CPU. So i thinks i wont add it to xmrigcc-cpu.
