### ISSUE TITLE
Built-in Config xmrigMiner

### ISSUE THREAD

**Issue by lomas777** [Bendr0id/xmrigCC#268]
Is it possible to compile xmrigMiner with an already built-in config.json file configured for a specific pool?

**Comment by Bendr0id** [comment]
https://github.com/Bendr0id/xmrigCC/blob/b395fe94f6baa5bdda0ca197e56cae3a878e9cb3/src/core/config/Config_default.h#L32

**Comment by lomas777** [comment]
More? Cannot start, what to fix

**Comment by Bendr0id** [comment]
I thought you're able to read the code.

**Comment by lomas777** [comment]
OK thanks)
