### ISSUE TITLE
[2.0.0] Incorrect detection of AVX feature under certain conditions

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#269]
With AMD CPUs (don't have access to Intel system right now, will check later) if miner is scheduled to start with the system, miner doesn't detect a presence of AVX2 feature correctly and falls back to SSSE3. I've tried to reproduce that by putting a synthetic load on the system, it only reproduces with on OS startup.

**Comment by uz-spark** [comment]
I've fixed that by delaying miner startup by 30 sec, maybe doing a repeated feature set check 30 sec after miner's startup will be an easy fix.

**Comment by Bendr0id** [comment]
I don't have a solution for that. I wasn't able to reproduce. Can we close this?

**Comment by uz-spark** [comment]
Well, i forgot to test it on Intel system, will try tomorrow, but it seems that this is AMD-exclusive behavior, maybe smth to do with GCC. I'll report later. Anyway, as i said, repeating a feature set check 30 sec after startup would be an easy 'fix'.
