### ISSUE TITLE
Fatal Error_ No such file or directory    26 | #include "win_dirent.h"

### ISSUE THREAD

**Issue by lost-bro** [Bendr0id/xmrigCC#271]
Fatal error occurs with MSYS2-mingW x64 in windows.

"[ 32%] Building CXX object CMakeFiles/xmrigMiner.dir/src/base/io/log/backends/FileLog.cpp.obj
C:/xmrigCC-dev/src/cc/Service.cpp:26:10: fatal error: win_dirent.h: No such file or directory
   26 | #include "win_dirent.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
"

![fatal error](https://user-images.githubusercontent.com/37913805/67518406-5e442000-f66a-11e9-8746-c5005f233572.png)
 I cannot locate this Header file in the source code.

I get the same error with either the _dev source or the release 2.1.0 source code.
The 2.0.0 source code complies w/o errors.
Any suggestions?
Thanks in advance.

**Comment by Bendr0id** [comment]
It's fixed in master. That folder was on .gitignore so it failed to upload.

**Comment by lost-bro** [comment]
Thanks, will try and compile Master.

**Comment by Bendr0id** [comment]
Or just redownload the last "release" its fixed in that source bundle too

**Comment by lost-bro** [comment]
OK< just compiled the master w/o problem, but I see you removed your build instructions and link >> Xmrig build instructions.......  Is Boost not used anymore in this code?

**Comment by Bendr0id** [comment]
Since version 2.x there is no additional dependencies compared to stock xmrig. Both deps work but i recommend to use the last from xmrig.

**Comment by lost-bro** [comment]
OK<  just wanted clarification.  Keep up the great work, thanks
