### ISSUE TITLE
[2.1.0] Donate mode indication

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#273]
Please put "donate" instead of algo name in dashboard when miner is in donating mode. That's distracting, i see miner using different algo for some reason, it's the right one in config, try to push it reveral times maybe it didn't update ...

**Comment by Bendr0id** [comment]
Fixed in master. When miner is in donation mode it won't update the algo/pool info anymore.

**Comment by uz-spark** [comment]
It is possible to replace hashrate with 'donation' or smth ? It's still a bit putting off when i see lower than expected hashrate.

**Comment by Bendr0id** [comment]
Hmm. Maybe putting my dev pool in the pool column?

**Comment by uz-spark** [comment]
Or that, yeah.

**Comment by Bendr0id** [comment]
Before it was showing the donate algo and pool.. then you wanted to have a change...

**Comment by uz-spark** [comment]
Well, i wasn't using pool column. But either way it's better if algo, pool and hashrate columns will display just 'donating' instead of specific data as it's offputting to see what you haven't set there.

**Comment by Bendr0id** [comment]
hashrate columns are numbers, so i could keep them to the value before the donate, and just change the pool to donate.. but thats a bit hackish

**Comment by uz-spark** [comment]
Hmm. If it's not possible to put non-numerical value in hashrate column then yep, freezing it until donation stops might do. You can even keep pool column to user defined one too then.
