### ISSUE TITLE
daemon shutting down

### ISSUE THREAD

**Issue by Stardock2018** [Bendr0id/xmrigCC#278]
The daemon shuts down no error is logs Is there a debug switch ?

**Comment by Bendr0id** [comment]
?

Which os?

What version?

Did you started it from commandline?

**Comment by Stardock2018** [comment]
windows 10 version 2.10 and 2.0.0 i have tried running in conmandline and and normal exec. both shutdown but a random times

**Comment by Bendr0id** [comment]
What do you mean by shutdown? Logs? What does the console printout?

**Comment by Stardock2018** [comment]
if i exec the daemon  the daemon program shutsdown window disappears.
if i use CMD line and exec there is no console output the daemon just stops.

**Comment by Bendr0id** [comment]
daemon + miner in same directory i hope?

**Comment by Stardock2018** [comment]
yes

**Comment by Bendr0id** [comment]
Thats very strange. What happens when you start the miner from commandline client?

xmrigMiner.exe --daemonized

**Comment by Stardock2018** [comment]
to clarify the daemon does start and runs for a random amount of time. 5 min 2 hours etc....

**Comment by Bendr0id** [comment]
which build are you using?

**Comment by Bendr0id** [comment]
sounds like a segfault

**Comment by Stardock2018** [comment]
2.1.0

**Comment by Bendr0id** [comment]
Common, learn to write meaningful issues. Otherwise nobody can help. Again WHICH version of the miner are you using? GCC / MVC? Self compiled?

**Comment by uz-spark** [comment]
Make sure you have no antivirus software running, or miner's folder is excluded.

**Comment by Stardock2018** [comment]
Sorry at the moment i am using MVC 2.1.0 version. and i have used the GCC version and it was doing the same thing. antivirus folder excluded allready.

**Comment by Bendr0id** [comment]
Hmm.. hard to say. Could have a thousand reasons. Bad memory is also possible since it happens randomly..

**Comment by Bendr0id** [comment]
Which algo do you mine? Is it a memory intensiv one or doesn't matter which algo you mine?

**Comment by Stardock2018** [comment]
loki 
ok ty anyway

**Comment by Bendr0id** [comment]
ok, loki is using ramdomx. That could be indeed a memory issue. Did you see same problems when mining a CN coin?

**Comment by uz-spark** [comment]
If that's the memory issue it should be reproduceable without a daemon. Try to run miner without daemon or run upstream miner version (XMRig) to see if it behaves the same.

**Comment by Bendr0id** [comment]
Running the miner without the daemon should have the same issue. The daemon is just a luncher.

**Comment by Stardock2018** [comment]
Xmrig works fine no problem.

**Comment by Bendr0id** [comment]
Hmm. Thats even more strange.. Did you try 3.x or 4.x version?

**Comment by Bendr0id** [comment]
The whole randomx/loki code is exactly the same as in xmrig

**Comment by Stardock2018** [comment]
4.3.1-beta mod date 2019-10-17 11:40AM

**Comment by Bendr0id** [comment]
Please test with 3.x version to see if its reproducable

**Comment by uz-spark** [comment]
See, it looks to me more like an issue with antivirus software, are you sure you've excluded it ? Is there a way to disable antivirus software temporarily ?

**Comment by Stardock2018** [comment]
I have the Xmrig running on 20 computers working fine. Just 2 windows 10 systems having this problem

**Comment by uz-spark** [comment]
Naturally, the question is what's the differences between these 2 systems and the rest ?

**Comment by Stardock2018** [comment]
2 totaly different systems i9 32 GB mem / AMD threadripper 2990wx 32 GB MEM different av i turned the av's off.

**Comment by Bendr0id** [comment]
I think it is a segmentation fault. But the daemon is there for restart the miner in that case, which is obviously not happening. I'll look into that

**Comment by Stardock2018** [comment]
thank you

**Comment by Bendr0id** [comment]
I tried to reproduce it by forcing the miner to crash. But the daemon just restarts it. When this happens the next time, a screenshot would be very helpful

**Comment by Stardock2018** [comment]
ok i will send a pic. when it happens again.

**Comment by Stardock2018** [comment]
![image](https://user-images.githubusercontent.com/37783446/68431364-417e1100-016f-11ea-8fd2-a44f6d7ce94b.png)

**Comment by Stardock2018** [comment]
![image](https://user-images.githubusercontent.com/37783446/68431454-7d18db00-016f-11ea-8115-65eac4413c81.png)

**Comment by Stardock2018** [comment]
this pic screen shot is from my i7 windows 10

**Comment by Bendr0id** [comment]
This looks like a segfaul. But is it xmrig 4.3.1 beta or xmrigcc running?

**Comment by Bendr0id** [comment]
No response... Is this problem still existing?

**Comment by Stardock2018** [comment]
Yes. I am still having the problem.
All good though I just wrote a script to restart it.

**Comment by Bendr0id** [comment]
Oh it's happening on AMD CPUs right?

Please try to disable "Opcache" in BIOS. This is a known problem with ryzen CPUs.

**Comment by Stardock2018** [comment]
Disabling the "Opcache" didn't work still the same problem
