### ISSUE TITLE
Failed on Windows VS2017 Compiling

### ISSUE THREAD

**Issue by k0mm4nd** [Bendr0id/xmrigCC#28]
It's right through the xmrig/xmrig 's build wiki until VS2017 compiling

It shows that lacking the defination of O_CREAT and other O_XXX, appearing in project xmrigMiner and CCServer in FileLog.cpp and Options.cpp.

Then I added the  `#include <fcntl.h>` into the files and fixed it.

I don't know whether it fixed in new version. My local ver is 1.3.1.

**Comment by Bendr0id** [comment]
Thx, i'll take a look.

**Comment by monerorus** [comment]
Confirm the problem and fix.
