### ISSUE TITLE
Feature request:   Is is possible to 'enable' the "--cuda --cuda-loader=C:/cuda/xmrig-cuda.dll" option?

### ISSUE THREAD

**Issue by lost-bro** [Bendr0id/xmrigCC#281]
First I want to thank you for all your hard work on this project.  Truly Awesome!   I have been experimenting with some code (using the Vanilla Xmrig 4.5.0-beta) running Nvidia gpus for testing the rx/ based algos...    the results are very encouraging, so I wanted to ask if you have any plans for adding/enabling the --cuda option in XmrigCC miner?  (I already have working wrapper code to switch between the gpus-cpus during installation automatically).  Thanks in advance.
lost_bro

**Comment by Bendr0id** [comment]
This Fork is currently based on the 3.x branch of XMRig. Once the 4.x branch becomes stable i'll start migrating XMRigCC to it.
