### ISSUE TITLE
xmrigserver issue

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#282]
unable to update the config via xmrig dashboard after updating to version 2.2.0
the rig server is not able to control the miner/client
only the statistics are updated

**Comment by Miner1305** [comment]
worker-id for the machine is not getting updated

**Comment by Bendr0id** [comment]
Can't confirm. Just successfully tested it on two different servers.

Is the server running 2.2.0?
Do you have miner logs?

Make sure you use the new config file format, the old won't work and the miner won't apply the config

**Comment by Miner1305** [comment]
issue fixed after
worker-id for the machine is not getting updated


toggled replace worker id

**Comment by Bendr0id** [comment]
Maybe you had multiple miners with the same worker-id, then they are always overwriting each other and appear as only one on the dashboard
