### ISSUE TITLE
ccx hashrate issue

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#283]
after updating from 1.9.5 to 2.2.0 the hash rate for ccx has reduced drastically
used to get 800-900 for 4 core cpu, now the max is 300.

**Comment by Bendr0id** [comment]
Try to add this to the cpu block in your config.

```
 "cpu": {
    "cn-conceal": {
      "intensity": 5
    }
...
```

**Comment by Bendr0id** [comment]
Start with that, then try to decrease the number until you find your sweetspot

**Comment by Miner1305** [comment]
given below is my config
where to add the above values

{
  "api": {
    "id": null,
    "worker-id": null
  },
  "http": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 0,
    "access-token": null,
    "restricted": true
  },
  "autosave": true,
  "version": 1,
  "background": false,
  "colors": true,
  "randomx": {
    "init": -1,
    "numa": true
  },
  "cpu": {
    "enabled": true,
    "huge-pages": true,
    "hw-aes": null,
    "priority": null,
    "asm": true,
    "argon2-impl": null,
    "argon2": [
      0,
      1,
      2,
      3
    ],
    "cn": [
      [
        5,
        0
      ],
      [
        5,
        1
      ],
      [
        5,
        2
      ],
      [
        5,
        3
      ]
    ],
    "cn-extremelite": [
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ]
    ],
    "cn-heavy": [
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ]
    ],
    "cn-lite": [
      [
        1,
        0
      ],
      [
        1,
        1
      ],
      [
        1,
        2
      ],
      [
        1,
        3
      ]
    ],
    "cn-pico": [
      [
        2,
        0
      ],
      [
        2,
        1
      ],
      [
        2,
        2
      ],
      [
        2,
        3
      ]
    ],
    "rx": [
      0,
      1,
      2,
      3
    ],
    "rx/wow": [
      0,
      1,
      2,
      3
    ],
    "cn/0": false,
    "cn-lite/0": false
  },
  "donate-level": 1,
  "donate-over-proxy": 0,
  "log-file": null,
  "pools": [
    {
      "algo": "cn/conceal",
      "url": "ca.conceal.herominers.com:10364",
      "user": "",
      "pass": "rig",
      "rig-id": null,
      "nicehash": true,
      "keepalive": true,
      "enabled": true,
      "tls": true,
      "tls-fingerprint": null,
      "daemon": false
    },
    {
      "algo": null,
      "url": "ca.conceal.herominers.com:10364",
      "user": "",
      "pass": "rig",
      "rig-id": null,
      "nicehash": true,
      "keepalive": true,
      "enabled": true,
      "tls": false,
      "tls-fingerprint": null,
      "daemon": false
    }
  ],
  "cc-client": {
    "enabled": true,
    "use-tls": true,
    "use-remote-logging": true,
    "upload-config-on-start": true,
    "url": 192.168.20.100:4443",
    "access-token": "Token54321",
    "worker-id": "",
    "reboot-cmd": null,
    "update-interval-s": 10
  },
  "print-time": 60,
  "retries": 5,
  "retry-pause": 5,
  "syslog": false,
  "user-agent": null,
  "watch": true
}

**Comment by Bendr0id** [comment]
Just like this:

```
"cn/conceal": [
[
5,
0
],
[
5,
1
],
[
5,
2
],
[
5,
3
]
],
"cn-extremelite": [
```

There are different ways of setting the parameters. You have the pre thread definition.
If you always want to run with all threads and intensity 5 you can short that up by just doing it like this:

```
 "cn/conceal": {
      "intensity": 5
    },
"cn-extremelite": [
```

**Comment by Bendr0id** [comment]
Take a look here to see the diffent ways of doing the cpu config:

https://github.com/Bendr0id/xmrigCC/blob/master/doc/CPU.md
