### ISSUE TITLE
Randomx with low ram

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#284]
Hi, 
i have few machines with 4GB or less.
hashrate is less for these machines when using randomx algo, does xmrigcc have a light mode or low memory mode, without compromising on hashrate.

**Comment by Bendr0id** [comment]
Hi, 4GB should be fine. 
RandomX need 2080MB of free RAM to use the fast mode. XMRigCC will autodetect if enough memory is available and fall back to the light mode.

Ofc the light mode is slower otherwise it wouldn't make sense to have two different modes.
