### ISSUE TITLE
New Algo request

### ISSUE THREAD

**Issue by Miner1305** [Bendr0id/xmrigCC#286]
can you please include the algo rx/sfx or if you can provide a method to add the algo and then compile please share it.

**Comment by Bendr0id** [comment]
Do you have a link?

**Comment by Miner1305** [comment]
https://github.com/safex/safex-rig

**Comment by Miner1305** [comment]
hi, is it possible to add the algo

**Comment by Bendr0id** [comment]
Think i can do it in the next days. When is fork?

**Comment by Miner1305** [comment]
fork happened few days back on dec6th.

**Comment by Bendr0id** [comment]
Implemented in #2.2.1

**Comment by Miner1305** [comment]
Thank You
