### ISSUE TITLE
update sorting "Group by Algo"

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#289]
Hi, I think it would be more useful and convenient that the "Group by Algo" sorting was done entirely by algorithm and not by the A-Z as it is now:

![immagine](https://user-images.githubusercontent.com/38523505/70909126-13f97280-200d-11ea-8d26-df5f5ca6706d.png)

a visualization of this type is more practical:
![immagine](https://user-images.githubusercontent.com/38523505/70909445-ccbfb180-200d-11ea-9186-a4e01d701ee5.png)

**Comment by Bendr0id** [comment]
Changed in master. Just fetch the latest index.html and copy to your server.

Please test if thats more the expected behavior.

**Comment by MrCook1es** [comment]
I confirm that it works correctly without errors.

**Comment by uz-spark** [comment]
So how to disable grouping now ?

**Comment by FranzDE** [comment]
> So how to disable grouping now ?

Di you mean a sort like this 
![](https://user-images.githubusercontent.com/38523505/70909445-ccbfb180-200d-11ea-9186-a4e01d701ee5.png)

Switchable to the old style like 1 year ago?

**Comment by uz-spark** [comment]
Nope, how to disable grouping altogether, there was a switch in previous version.

**Comment by MrCook1es** [comment]
> 
> 
> Nope, how to disable grouping altogether, there was a switch in previous version.

what result would you like to get? I do not understand.

if the switch is replaced.
maintained the current visualization by algo, what kind of sorting would you like?
please explain

**Comment by uz-spark** [comment]
There was a switch prior to 2.2.2, right below "Hide offline miners" and "Notify when miner went offline", flicking it disabled grouping by algo, now there's not.

**Comment by MrCook1es** [comment]
> 
> 
> There was a switch prior to 2.2.2, right below "Hide offline miners" and "Notify when miner went offline", flicking it disabled grouping by algo, now there's not.

I know that there was a switch.
I'm asking you things must happen if you press it.
what visualizations would you like to alternate?

**Comment by uz-spark** [comment]
What you think should happen if you flick "Disable algo grouping' switch ? It disables grouping.

**Comment by uz-spark** [comment]
Like, it just sorts by whatever column uses chooses, be it id or hashrate, without grouping altogether, i don't see what's so hard to grasp here. Grouping are useful sometimes, most of the time it's not, at least for me.

**Comment by Bendr0id** [comment]
Don't see the problem. The sorting still works but it only sorts within the same group which is the expected behavior for most of the users. The old grouping was just broken

**Comment by uz-spark** [comment]
Come on ... there was a way to disable grouping in previous version, now there's no way, it's always grouped by algo, which is not always convenient. New sorting withing groups are indeed better but there needs to be a way to disable grouping altogether.

**Comment by Bendr0id** [comment]
The option was there because the old mechanism was bad. With the new easy the grouping is working a enable/disable wasn't that easy and I'm not a webdev. So if you want the old behavior either use the old index.html from the history, keep the current behavior or feel free to contribute a better implementation with enable/disable feature.

**Comment by uz-spark** [comment]
That clears it, i'm no webdev either but i've already reverted to old index.htm

**Comment by Bendr0id** [comment]
That seems to work. Please check if it behaves like expected

**Comment by uz-spark** [comment]
Yep, it works, thanks !

**Comment by MrCook1es** [comment]
@Bendr0id seems legit! ;)

@uz-spark  is the exact same thing that Franz had written
> 
> 
> 
> Di you mean a sort like this
> ![](https://user-images.githubusercontent.com/38523505/70909445-ccbfb180-200d-11ea-9186-a4e01d701ee5.png)
> 
> Switchable to the old style like 1 year ago? (All together)
