### ISSUE TITLE
Miner Closes no error

### ISSUE THREAD

**Issue by mike2246** [Bendr0id/xmrigCC#290]
When I use this miner I configure the Config File, after opening the miner it crashes without error. If I run XMRStak or XMRig separate and configure it runs fine with those programs. Also is there any tweaking that can be done? I have a Ryzen 1700x and I'm only getting 1400-1600h/s. I've seen a bunch of other results of this CPU getting 3800-4100h/s

**Comment by Bendr0id** [comment]
Your post is a little bit confusing. On the one hand you say that the miner immediately crashes without an error and on the other hand you ask howto improve the hashrate.

1. Did you start miner or the daemon? Make sure you start the daemon and have the miner in the same directory.

2. If you already use the daemon then the reason for the "crash" may due to a bad config file. Did you check it for syntax issues?

3. What coin/algo are you talking about?

**Comment by mike2246** [comment]
Here is config file, and for hashrate if I use the other software it works but seems slow compared to what others are getting. 
Randomx Monero

{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "version": 1,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "asm": true,
        "argon2-impl": null,
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 1,
    "log-file": null,
    "pools": [
        {
            "algo": rx/0,
            "coin": null,
            "url": "xmr.2miners.com:2222",
            "user": "wallet",
            "pass": "x",
            "rig-id": test,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "cc-client": {
        "enabled" : true,
        "url": "localhost:3344",
        "use-tls" : false,
        "access-token": "mySecret",
        "worker-id": null,
        "update-interval-s": 10,
        "use-remote-logging" : true,
        "upload-config-on-start" : true
    },
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}

**Comment by Bendr0id** [comment]
There is your problem: `"algo": rx/0,`. 

Thats the wrong syntax. Make it like this: `"algo": "rx/0",`

**Comment by Bendr0id** [comment]
And this too:

`"rig-id": test,` to `"rig-id": "test",`

**Comment by Bendr0id** [comment]
Text always needs to be in "". Numbers, null and true/false must be without.

**Comment by Bendr0id** [comment]
Does it work now?

**Comment by mike2246** [comment]
Working now, Thanks. But still same slow speed of 1600h/s with a Ryzen 1700x. Shouldn’t speeds be closer to 4100h/s?

**Comment by Bendr0id** [comment]
Autodetect should work well. Can you send me a screenshot of the startup of the miner..? Maybe hugepages arent initialized

**Comment by mike2246** [comment]
did you get screenshot?

**Comment by Bendr0id** [comment]
nope

**Comment by mike2246** [comment]
![slow speed](https://user-images.githubusercontent.com/17620806/71121712-f82cd280-21ac-11ea-810c-8ff90f6cf123.PNG)

**Comment by Bendr0id** [comment]
Hmm looks good

**Comment by mike2246** [comment]
are those speeds normal? I thought 1700x was supposed to get closer to 4100

**Comment by Bendr0id** [comment]
Hmm looks a bit slow..

Seems like its not able to acquire the whole huge pages.

Like this:

```
[2019-12-18 21:58:00.175]  rx   init dataset algo rx/0 (4 threads) seed 9d4fe3c9677150ca...
[2019-12-18 21:58:00.176]  rx   #0 allocate 2336 MB (2080+256) for RandomX dataset & cache
[2019-12-18 21:58:00.176]  cpu  use profile  rx  (4 threads) scratchpad 2048 KB
[2019-12-18 21:58:00.787]  cpu  READY threads 4(4) huge pages 4/4 100% memory 8192 KB (611 ms)
[2019-12-18 21:58:11.727]  rx   #0 allocate done huge pages 1168/1168 100% +JIT (11551 ms)
```

**Comment by mike2246** [comment]
something I can change? is it becuase I only have 1 stick of RAM?

**Comment by Bendr0id** [comment]
How much RAM you have? 4G+ schould be fine

**Comment by mike2246** [comment]
4Gb

**Comment by Bendr0id** [comment]
Is this still valid?
