### ISSUE TITLE
xmrig does nothing after Opening

### ISSUE THREAD

**Issue by drewjsch** [Bendr0id/xmrigCC#292]
It runs a few lines on command prompt, then after a few seconds goes back to C:\>

What else do I have to do to start mining?

**Comment by drewjsch** [comment]
![IMG_20191217_173524](https://user-images.githubusercontent.com/58997442/71042794-bcd1cb80-20fa-11ea-8d71-c386ba78e39f.jpg)

**Comment by Bendr0id** [comment]
1. You are not using my mining software
2. 0 support for 0 donate

**Comment by djfinch** [comment]
It's hardcoded in their 'official miner'. They are not clowns, they are entire circus...
https://github.com/bigbangcore/miner/blob/master/src/base/net/stratum/Pools.cpp#L164

**Comment by Bendr0id** [comment]
He is not using my miner at all. I don't have cn/bbc support. So he is asking on the wrong repo.

**Comment by djfinch** [comment]
Yep, I know. I'm just raising finger on those BBC 'dev' or whatever it's called. :fu:
