### ISSUE TITLE
Config web editor - many lines

### ISSUE THREAD

**Issue by ilya7zz** [Bendr0id/xmrigCC#293]
Each parameter in the XMRig Dashboard starts on a new line.
![3EA8FA1A-A289-4FA3-9310-A22BB3D33BE7](https://user-images.githubusercontent.com/53345402/71070442-d66f2380-218b-11ea-9a1d-bf65cbb9500b.jpeg)
![64E7B9D5-43C9-4BF7-B797-7833BB329D7D](https://user-images.githubusercontent.com/53345402/71070443-d66f2380-218b-11ea-9328-a2a5ddf4616c.jpeg)

**Comment by Bendr0id** [comment]
What's the issue here? There should be a scrollbar on the right side.

**Comment by ilya7zz** [comment]
The problem is the difficulty to read and edit the text. There are many spaces before each digit. To find the desired parameter you need to scroll for a long time.
Code should look like this: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10].
And looks like this:
[
     0,
     1,
     2,
     3,
     4,
     5,
     6,
     7,
     8,
     9,
     10
]
In early versions everything was OK

**Comment by uz-spark** [comment]
You can disable autosave, snip all that wall of text and leave only what you want. It will run with defaults on algos that isn't defined by your config.

**Comment by ilya7zz** [comment]
**uz-spark**, I do not understand the meaning of the function-autosave. I don't understand your answer :)

**Comment by uz-spark** [comment]
Судя по имени ты русский ? Найди в конфиге "autosave": true, выстави на false, в разделе "cpu" удали всё после "asm" до первой закрывающей фигурной скобки, вот так : 
  "cpu": {
    "enabled": true,
    "huge-pages": true,
    "hw-aes": null,
    "priority": 0,
    "asm": true,
    }
Теперь всё будет по дефолту и майнер не будет засорять конфиг этими дефолтными настройками, если надо поменять что-то то добавляй сам.

**Comment by ilya7zz** [comment]
Русский :)
Однако, предложенный совет не решил озвученную проблему. Записанные строки кода в строку превращаются в столбик, как указывал на скриншотах и примерах. Проблема в сервере.

**Comment by uz-spark** [comment]
Попробуй другой синтаксис - https://github.com/xmrig/xmrig/blob/master/doc/CPU.md
Вот так например :
{
    "intensity": 2,
    "threads": 8,
    "affinity": -1
}

**Comment by ilya7zz** [comment]
Спасибо. Возможно я что-то не понял, не вышло.
Параметр(ы) без квадратных скобок игнорируется. Старый параметр  "threads": - также игнорируется. Писал их в разделе "cpu": {}

**Comment by uz-spark** [comment]
То что я выше написал пишется на каждый алгоритм отдельно или на всё сразу если поставишь * вместо алгоритма. В итоге у тебя блок cpu должен выглядеть вот так :
"cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "asm": true,
        "*": {
            "intensity": 2,
            "threads": 8,
            "affinity": -1
        }
    }
