### ISSUE TITLE
Make dashboard resources offline

### ISSUE THREAD

**Issue by uz-spark** [Bendr0id/xmrigCC#294]
Like, when all required resources would be stored locally on server, not loaded on demand from internet, it's very slow sometimes.

**Comment by Bendr0id** [comment]
The js files are loaded directly from cdn and is compressed texts. The only resource which comes from the web is the logo on the top. If you want to improve the loading time here, just remove the image tag from the index.html.

**Comment by uz-spark** [comment]
Isn't the CDN in the web too ? I pretty sure in my case, the logo isn't the issue since it's most likely cached, but the scripts\CSS which sometimes take a minute to load, no idea why.

**Comment by djfinch** [comment]
You can convert logo and icon to base64 format and paste them into index.html instead of remote links. Also, you can download jQuery, Datatables, Bootstrap and serve them along with with CcServer using your own webserver. I'm pretty sure Python's SimpleHTTPServer is the right candidate for this job. However, this long responses from CDNs are really weird. You can check what's happening there with 'waterfall' in Chrome Dev Tools.

**Comment by Bendr0id** [comment]
@uz-spark A CDN is mirroring static content to destinations almost everywhere on this planet. So you should have always the static resources located nearby.

So in this cases its very strange that it sometimes takes upt o a minute. The javascript and CSS is pure text which is compressed. So its very small.

A clean refresh of the whole page is 800kb. But thats only loaded once on the very first start or after browser cache clean. 

Every subsequent full reload / reopen just takes <30kb.

**Comment by Bendr0id** [comment]
XmrigServer could easy deliver these static files too, but would make the maintenance / updating much more complicated for the users.

**Comment by uz-spark** [comment]
I'm aware of it and i don't have even remotely as long load times on any other sites, no idea why it works this way here. I've tried Firefox dev tools, network tab clocked 80 seconds before bootstrap.min.css was loaded, today it works fine even after cache cleaning, might be that the closest CDN to me are struggling with traffic or there are packet loss.

**Comment by Bendr0id** [comment]
Fixed in master
