### ISSUE TITLE
[Help Wanted] run xmrigServer on RPI

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#295]
hi guys, what is the best way to run xmrigCC-Server on a raspberry?

are there any known limitations with rpi1 rpi2 rpi3 ?

I should manage about 50 miners.

**Comment by Bendr0id** [comment]
Rpi can easy do that

**Comment by MrCook1es** [comment]
I have several unused rpi1 model B.
I thought I'd reuse one of those.

Can I feel comfortable with a rpi1 B and its 512mb ram / 700MHz ARM v6 CPU?

**Comment by djfinch** [comment]
Not sure with rPi1 as ARMv6 might be a problem. I mean compile with daemon&miner because of lack of NEON on v6. But ccServer should work. Also, you have to add some swap volume to have some memory for compiler...

**Comment by Bendr0id** [comment]
Daemon and miner should compile. But if not just disable them in the cmakelists and onlybuild the xmrigServer.

**Comment by Bendr0id** [comment]
cmake . --target xmrigServer

**Comment by FranzDE** [comment]
Thank you very much for the advice!

I'm collecting the correct information before proceeding.  Tomorrow afternoon I can finally work on my old rpi1 B :)

**Comment by MrCook1es** [comment]
Thank you very much for the advice!

I'm collecting the correct information before proceeding.  In the afternoon I can finally work on my old rpi1 B :)

**Comment by MrCook1es** [comment]
I started with the latest raspbian release. Here are my steps:

```
sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
git clone https://github.com/Bendr0id/xmrigCC.git
cd xmrigCC && mkdir build && cd build
```

ADD SWAP
```
dd if=/dev/zero of=/swapfile.img bs=1024 count=4M
chmod 600 /swapfile.img
mkswap /swapfile.img
swapon /swapfile.img
```

TEST SWAP
`free -h`

cmake ..
`
pi@raspberrypi:~/xmrigCC/build $ cmake ..
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found UV: /usr/lib/arm-linux-gnueabihf/libuv.a
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/xmrigCC/build
`

make
`Scanning dependencies of target argon2
[  0%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
cc: error: unrecognized command line option ‘-maes’; did you mean ‘-mapcs’?
make[2]: *** [src/3rdparty/argon2/CMakeFiles/argon2.dir/build.make:63: src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:202: src/3rdparty/argon2/CMakeFiles/argon2.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
`


I edited CMakeLists.txt to avoid compiling the miner.
I point out that the "cmake. - target xmrigServer" command is not accepted

**Comment by Bendr0id** [comment]
cmake --build /some/build/path/xmrigCC --target xmrigServer

**Comment by MrCook1es** [comment]
I get the same mistake as before:

![immagine](https://user-images.githubusercontent.com/38523505/71350794-63422480-2572-11ea-870d-6487d00295c7.png)

**Comment by MrCook1es** [comment]
does anyone have any ideas to solve the problem?

**Comment by cyphr3x** [comment]
Can we get a version that doesnt need a billion gbs of ram to compile?
```
cc1plus: out of memory allocating 5190462000 bytes after a total of 1040506880 bytes
make[2]: *** [CMakeFiles/xmrigMiner.dir/build.make:1415: CMakeFiles/xmrigMiner.dir/src/crypto/rx/RxDataset.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:154: CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [Makefile:84: all] Error 2 
```

**Comment by Bendr0id** [comment]
Works perfectly fine for me. I Compile the armv8 version on a machine with 2gb ram without an issue. 

Did you try to just use my precompiled one..?

Or you just disable the randomx algos with the option -DWITH_RANDOMX=OFF

**Comment by cyphr3x** [comment]
-DWITH_RANDOMX=OFF worked, thanks!

**Comment by Bendr0id** [comment]
**Alternative solution**: Install and used GCC-7 instead of GCC-9
