### ISSUE TITLE
WIN XP

### ISSUE THREAD

**Issue by georat72** [Bendr0id/xmrigCC#296]
Hello,
I have a problem. With the last XmrigCC 2.2.2 All WIN XP computers continue give me the error message :
the procedure entry point GetLargePageMinimum could not be located in the dynamic link library kernel32.dll .
I know it`s not in your priority list, but I saw in the release written 
Fixed CC support for old Windows variants (XP, 2003, 7 without SP1)

**Comment by Bendr0id** [comment]
XP supported was meant for the CC component. To build on XP you could consider to disable Randomx variant. That may solve it.
