### ISSUE TITLE
web interface: "last update" data

### ISSUE THREAD

**Issue by MrCook1es** [Bendr0id/xmrigCC#299]
what does the "last update" column mean?
It no longer indicates the time of the last update of the data, e.g. 10 seconds ago.
But it's indicating when I restarted xmrigCC Server! "13 hours ago"

![immagine](https://user-images.githubusercontent.com/38523505/72166392-6b4ef080-33c9-11ea-81b6-4b32d9a56736.png)

**Comment by Bendr0id** [comment]
Did you modify bthe index?

**Comment by Bendr0id** [comment]
Check your server clock

**Comment by MrCook1es** [comment]
> 
> 
> Did you modify bthe index?

I just edited the index.html to remove the banner, so I have a smaller page.
I deleted this line: `<img src="https://root.graef.in:8443/static/xmrigcc/banner.png"/>`

i am using xmrigCC pre-compiled version https://github.com/Bendr0id/xmrigCC/releases/download/2.5.0/xmrigCC-2.5.0-with_tls_and_gzip-gcc-win64.zip

**Comment by MrCook1es** [comment]
> 
> 
> Check your server clock

xmrigCC Server is on a remote server that has a different time zone.
Now that I have set the same time zone as the miners, the "last update" seems correct.

I continue with the checks and then give you confirmation.

**Comment by MrCook1es** [comment]
I confirm that everything now works correctly. It was the time on the windows machine where runs xmrigCC server!

**Comment by Bendr0id** [comment]
Timezone should be the same on the machine were you haver the server and where the dashboard is shown. A clock drift should be no problem.
