### ISSUE TITLE
Integrate xmrig-nvidia and similar into dashboard/miner control

### ISSUE THREAD

**Issue by rekonnected** [Bendr0id/xmrigCC#3]
I think it would be awesome to add the GPU side of things given that xmrig offers an nvidia and AMD miner, and since AFAIK it runs on the same type of configuration it should be semi-doable, right?

**Comment by rekonnected** [comment]
Given that multiple miners are switching to a unified miner design, where one program can mine CPU/GPU simultaneously, this may not be an issue in the near future.

**Comment by Bendr0id** [comment]
XMRigCC-amd is in beta status now.

Take a look:
https://github.com/Bendr0id/xmrigCC-amd

**Comment by Bendr0id** [comment]
finally released 3.0.0
