### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by cesaramorim86** [Bendr0id/xmrigCC#300]
Hi there,

Any chance of add read environment variables from config.json file
More information in:
[https://xmrig.com/docs/miner/environment-variables](url)

**Comment by Bendr0id** [comment]
i can take a look.. is it really useful?

**Comment by cesaramorim86** [comment]
yes it is. in my case want to put the rig-id = computername.
i have a proxy server and in the management panel all ther workers are the same or i need to define one by one
If can use rig-id = computer name will be easier
thank you

**Comment by MrCook1es** [comment]
> 
> 
> yes it is. in my case want to put the rig-id = computername.
> i have a proxy server and in the management panel all ther workers are the same or i need to define one by one
> If can use rig-id = computer name will be easier
> thank you

if you use a proxy (like me) simply put in the miner config, pool section: 
      "url": "proxy-url",
      "user": "x",
      "pass": "THE-NAME",

**Comment by cesaramorim86** [comment]
> > yes it is. in my case want to put the rig-id = computername.
> > i have a proxy server and in the management panel all ther workers are the same or i need to define one by one
> > If can use rig-id = computer name will be easier
> > thank you
> 
> if you use a proxy (like me) simply put in the miner config, pool section:
> "url": "proxy-url:proxy-port",
> "user": "x",
> "pass": "THE-NAME",

true. but you need to have a configuration file for each miner. 
with my idea it's easier to manage templates in the server

**Comment by Bendr0id** [comment]
Fixed, added  env variable parsing for CC-WorkerId too.
