### ISSUE TITLE
Miner not connecting to Webchain pool

### ISSUE THREAD

**Issue by Tree248** [Bendr0id/xmrigCC#306]
Good evening. I recently started looking into mining Mint.me. This was a recommended software but it wont connect it just says [webcn.cc-poolz.com:1111] read error: "end of file" 

I was just wondering if you knew if there is something I have done wrong. 

Complete config below
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "numa": true
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "hw-aes": null,
        "priority": null,
        "memory-pool": false,
        "yield": true,
        "max-threads-hint": 100,
        "asm": true,
        "argon2-impl": false,
        "astrobwt-max-size": 550,
        "cn/0": false,
        "cn-lite/0": false
    },
    "donate-level": 5,
    "donate-over-proxy": 1,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "coin": null,
            "url": "webcn.cc-poolz.com:1111",
            "user": "",
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null
        }
    ],
    "cc-client": {
        "enabled": true,
        "url": "localhost:3344",
        "access-token": "mySecret",
        "use-tls": false,
        "use-remote-logging": true,
        "upload-config-on-start": true,
        "worker-id": null,
        "reboot-cmd": null,
        "update-interval-s": 10
    },
    "print-time": 60,
    "health-print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "verbose": 0,
    "watch": true
}

**Comment by Tree248** [comment]
Hope to get the issue solved. This miner has Huge Pages and the one I am using doesn't. Would love to be able to use this for that feature.

**Comment by Bendr0id** [comment]
Miner is not supporting webchain.
