### ISSUE TITLE
[VOTE] Remote shell execute 

### ISSUE THREAD

**Issue by gio1505** [Bendr0id/xmrigCC#307]
it would be sometimes handfull if you can execute directly os command and get command output as well

**Comment by Bendr0id** [comment]
Its feasible, but this will add a huge security hole into the miners. Everything will be executed with the same user which runs the miner (most times Administrator). I don't know if thats a good idea...

**Comment by gio1505** [comment]
it's possible anyway to gain full  access from web interface if you edit miner config file and add to it reboot-cmd nc -lvp 4444 -e /bin/sh you will connect to nc shell and do whatever you want

**Comment by Bendr0id** [comment]
You're right, it's possible with the reboot and shutdown cmd i didn't thought about that. 

We should start a vote for this feature. If we get some more i'll implement it soon.

**Comment by Bendr0id** [comment]
Please give this a +1 reaction to vote for it

**Comment by djfinch** [comment]
@gio1505 IMHO not a good idea. Netcat does not naturally have any auth and traffic encryption. Use SSH + tmux instead (it's better than `&`, `disown` or `nohup`) . Or reverse SSH tunnel for miners behind NAT with cron entry `@reboot autossh -R 12345:localhost:22 user@host`... I'm using AWS micro with public IP, running proxy, ccserver there and miners are connected through reverse SSH tunnel  so I can ssh to AWS and then ssh locahost:12345, localhost:12346, localhost:12347, etc... or using tmux as well (with `teamocil`)...

**Comment by gio1505** [comment]
> @gio1505 IMHO not a good idea. Netcat does not naturally have any auth and traffic encryption. Use SSH + tmux instead (it's better than `&`, `disown` or `nohup`) . Or reverse SSH tunnel for miners behind NAT with cron entry `@reboot autossh -R 12345:localhost:22 user@host`... I'm using AWS micro with public IP, running proxy, ccserver there and miners are connected through reverse SSH tunnel so I can ssh to AWS and then ssh locahost:12345, localhost:12346, localhost:12347, etc... or using tmux as well (with `teamocil`)...

 it was just example.
 reverse SSH tunnel is great but it takes time to setup  many miner also managing them might get hard

**Comment by GjBrutello** [comment]
I use commands with ssh public key authentication(without password) for reboot server or restart miner proxy service. Even windows 10 has now installed openssh by default. Also on the github are versions for win 7, 8.

**Comment by Bendr0id** [comment]
integrated into dev

**Comment by Bendr0id** [comment]
The feature can be disabled at compile time by passing -DWITH_CC_SHELL_EXEC=OFF
