### ISSUE TITLE
VS2017 Compile Error

### ISSUE THREAD

**Issue by serracloud** [Bendr0id/xmrigCC#310]
Upon trying to compile I'm given an issue by the xmrigcc\src\3rdparty\cpp-httplib\httplib.h file. What do I need to modify in this file to get it to compile correctly? I followed the instructions on your windows build page and installed the xmrig dependencies - Cmake creates the .sln file with no problems. 
```
...
using socket_t = SOCKET;
#ifdef CPPHTTPLIB_USE_POLL
#define poll(fds, nfds, timeout) WSAPoll(fds, nfds, timeout)
#endif
...
...
#ifdef CPPHTTPLIB_USE_POLL
  struct pollfd pfd_read;
  pfd_read.fd = sock;
  pfd_read.events = POLLIN;
  auto timeout = static_cast<int>(sec * 1000 + usec / 1000);
  return HANDLE_EINTR(poll, &pfd_read, 1, timeout);

<error output>
11>C:\Users\User\source\repos\xmrigCC\src\3rdparty/cpp-httplib/httplib.h(1240): error C2064: term does not evaluate to a function taking 0 arguments
11>C:\Users\User\source\repos\xmrigCC\src\3rdparty/cpp-httplib/httplib.h(1263): warning C4003: not enough arguments for function-like macro invocation 'poll'
11>C:\Users\User\source\repos\xmrigCC\src\3rdparty/cpp-httplib/httplib.h(1263): error C2059: syntax error: ','
11>C:\Users\User\source\repos\xmrigCC\src\3rdparty/cpp-httplib/httplib.h(1286): warning C4003: not enough arguments for function-like macro invocation 'poll'
11>C:\Users\User\source\repos\xmrigCC\src\3rdparty/cpp-httplib/httplib.h(1286): error C2059: syntax error: ','
```
This same error comes up while compiling both the xmrigMiner & xmrigServer projects.

**Comment by Bendr0id** [comment]
Same issue for me using msvsc 2017. Investigating.

**Comment by Bendr0id** [comment]
It's a bug in a 3rdparty library. I contacted the maintainer already.

To workaround this for now, open `src\3rdparty/cpp-httplib/httplib.h`

Then search and replace: `HANDLE_EINTR(poll` with `poll(`, save and compile.

**Comment by serracloud** [comment]
That worked, thank you. 

Just for clarity with people who struggle with this in the future: the 3 lines of code (on 1240, 1263, & 1286) that threw those errors should all look like this:

`return poll( &pfd_read, 1, timeout);`

**Comment by Bendr0id** [comment]
Fixed in master
