### ISSUE TITLE
GLIBC_2.25 error

### ISSUE THREAD

**Issue by WebDevelopNemanja** [Bendr0id/xmrigCC#321]
Hi. I build  it from source and when I run xmrigMiner I shows me this:

./xmrigMiner: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by ./xmrigMiner)

**Comment by Bendr0id** [comment]
Hi,
looks like you did something wrong with linking.. Are you trying todo a static build?

**Comment by Bendr0id** [comment]
No response, will be closed soon
