### ISSUE TITLE
Miner CPU intensity

### ISSUE THREAD

**Issue by username1565** [Bendr0id/xmrigCC#327]
Hello. Can you add argument --intensity, or "intensity":value in JSON-config,
to set intensity of mining on each core, and decrease this intensity, using `trottling`, or some `delay`?
Because limitation of number of the CPU-threads, decreasing usage of CPU-cores,
but loading on this corea is 100%, and temperatures is maximum, on each loaded CPU-core.
Not good...
What if need to load 8 cores up to 25%, and no more?

Thanks.

**Comment by Bendr0id** [comment]
I started working on this, found a way which at least could work for linux+windows. Not sure about macOS yet.

**Comment by Bendr0id** [comment]
ready for testing on dev-branch

**Comment by Bendr0id** [comment]
merged
