### ISSUE TITLE
Plan for AMD/NVIDIA GPU support

### ISSUE THREAD

**Issue by Elyytscha** [Bendr0id/xmrigCC#33]
Would be awesome if this miner could also do GPU mining, their are already some forks of XMRRIG which can do that, maybe it should be possible to reuse some code from that forks.

This would really be awesome

**Comment by sanitariu** [comment]
Vote +

**Comment by mike2246** [comment]
Vote +

**Comment by Bendr0id** [comment]
XMRigCC-amd is in beta status now.

Take a look:
https://github.com/Bendr0id/xmrigCC-amd

**Comment by Bendr0id** [comment]
finally released 3.0.0
