### ISSUE TITLE
How to compile can run in armv5tel

### ISSUE THREAD

**Issue by 1756816846** [Bendr0id/xmrigCC#331]
Please.

**Comment by Saikatsaha1996** [comment]
> Please.
1) apt-get install wget proot automake autoconf pkg-config libcurl4-openssl-dev libjansson-dev libssl-dev libhwloc-dev hwloc libgmp-dev zlib1g-dev make g++ git build-essential cmake libuv1-dev libmicrohttpd-dev gcc-7 g++-7 curl nano clang libuv1-dev -y

2) git clone https://github.com/Bendr0id/xmrigCC.git
3) chown -R $USER:$USER xmrigCC
4) cd xmrigCC
5) cmake . -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
6) make
7) cp src/config.json .
8) nano config.json
9) change your details
10) save 
11) ./xmrigDaemon

**Comment by 1756816846** [comment]
`root@usera:~/Desktop/xmrigCC-master# cmake . -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DARM_TARGET=7
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Use ARM_TARGET=7 (x86_64)
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found HWLOC: /usr/lib/x86_64-linux-gnu/libhwloc.so  
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a  
-- Looking for __builtin___clear_cache
-- Looking for __builtin___clear_cache - not found
-- WITH_MSR=OFF
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Desktop/xmrigCC-master
root@crossbug-H410M-T-PRO:~/Desktop/xmrigCC-master# make
Scanning dependencies of target argon2

[  0%] Building C object src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o
gcc-7: error: unrecognized command line option ‘-mfpu=neon’
src/3rdparty/argon2/CMakeFiles/argon2.dir/build.make:62: recipe for target 'src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o' failed
make[2]: *** [src/3rdparty/argon2/CMakeFiles/argon2.dir/lib/argon2.c.o] Error 1
CMakeFiles/Makefile2:196: recipe for target 'src/3rdparty/argon2/CMakeFiles/argon2.dir/all' failed
make[1]: *** [src/3rdparty/argon2/CMakeFiles/argon2.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by djfinch** [comment]
AFAIK supported targets are just v7 and v8... v5 is too old. There are not NEON extension in this old piece of HW. Its even not worth trying...

**Comment by 1756816846** [comment]
> AFAIK supported targets are just v7 and v8... v5 is too old. There are not NEON extension in this old piece of HW. Its even not worth trying...

Armv7 I have been compiling failed, can you compile it

**Comment by Saikatsaha1996** [comment]
> > AFAIK supported targets are just v7 and v8... v5 is too old. There are not NEON extension in this old piece of HW. Its even not worth trying...
> 
> Armv7 I have been compiling failed, can you compile it

git clone https://github.com/Bendr0id/xmrigCC.git

chown -R $USER:$USER xmrigCC

cd xmrigCC

cmake ..
make

**Comment by 1756816846** [comment]
> > > AFAIK supported targets are just v7 and v8... v5 is too old. There are not NEON extension in this old piece of HW. Its even not worth trying...
> > 
> > 
> > Armv7 I have been compiling failed, can you compile it
> 
> git clone https://github.com/Bendr0id/xmrigCC.git
> 
> chown -R $USER:$USER xmrigCC
> 
> cd xmrigCC
> 
> cmake ..
> make

cc: error: unrecognized command line option ‘-mfpu=neon’

**Comment by Saikatsaha1996** [comment]
Don't use this line mfpu=neon
Delete everything and re compile ...

**Comment by 1756816846** [comment]
> Don't use this line mfpu=neon
> Delete everything and re compile ...

[ 70%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o
In file included from /root/XTDS/av/xmrig-master/src/crypto/cn/soft_aes.h:31:0,
                 from /root/XTDS/av/xmrig-master/src/crypto/cn/CryptoNight_arm.h:35,
                 from /root/XTDS/av/xmrig-master/src/crypto/cn/CnHash.cpp:35:
/root/XTDS/av/xmrig-master/src/crypto/cn/sse2neon.h:65:10: fatal error: arm_neon.h:
