### ISSUE TITLE
[ 70%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o In file included from /root/XTDS/av/xmrig-master/src/crypto/cn/soft_aes.h:31:0, from /root/XTDS/av/xmrig-master/src/crypto/cn/CryptoNight_arm.h:35, from /root/XTDS/av/xmrig-master/src/crypto/cn/CnHash.cpp:35: /root/XTDS/av/xmrig-master/src/crypto/cn/sse2neon.h:65:10: fatal error: arm_neon.h:

### ISSUE THREAD

**Issue by 1756816846** [Bendr0id/xmrigCC#332]
[ 70%] Building CXX object CMakeFiles/xmrig.dir/src/crypto/cn/CnHash.cpp.o
In file included from /root/XTDS/av/xmrig-master/src/crypto/cn/soft_aes.h:31:0,
from /root/XTDS/av/xmrig-master/src/crypto/cn/CryptoNight_arm.h:35,
from /root/XTDS/av/xmrig-master/src/crypto/cn/CnHash.cpp:35:
/root/XTDS/av/xmrig-master/src/crypto/cn/sse2neon.h:65:10: fatal error: arm_neon.h:

**Comment by djfinch** [comment]
How many issues you want to create before figuring out that your ARM does not support NEON extension witch are required to make it work? Supported are ARMv7 and ARMv8. ARMv5 is not!

**Comment by Bendr0id** [comment]
Duplicate
