### ISSUE TITLE
compile error xmrigCC

### ISSUE THREAD

**Issue by obiwandeath** [Bendr0id/xmrigCC#337]
I can't compile gcc xmrigCC 2.9.0 according to the instructions.
first error (missing: HWLOC_LIBRARY HWLOC_INCLUDE_DIR)
after shutdown with "-DWITH_HWLOC = OFF", exits without error.

> CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
>   Compatibility with CMake < 2.8.12 will be removed from a future version of
>   CMake.
> 
>   Update the VERSION argument <min> value or use a ...<max> suffix to tell
>   CMake that the project does not need compatibility with older versions.
> 
> 
> -- The C compiler identification is GNU 10.2.0
> -- The CXX compiler identification is GNU 10.2.0
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Check for working C compiler: C:/msys64/mingw64/bin/cc.exe - skipped
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Found UV: C:/msys64/mingw64/lib/libuv.a
> -- WITH_MSR=ON
> -- argon2: detecting feature 'sse2'...
> -- Performing Test FEATURE_sse2_NOFLAG
> -- Performing Test FEATURE_sse2_NOFLAG - Success
> -- argon2: feature 'sse2' detected!
> -- argon2: detecting feature 'ssse3'...
> -- Performing Test FEATURE_ssse3_NOFLAG
> -- Performing Test FEATURE_ssse3_NOFLAG - Failed
> -- Performing Test FEATURE_ssse3_FLAG
> -- Performing Test FEATURE_ssse3_FLAG - Success
> -- argon2: feature 'ssse3' detected!
> -- argon2: detecting feature 'xop'...
> -- Performing Test FEATURE_xop_NOFLAG
> -- Performing Test FEATURE_xop_NOFLAG - Failed
> -- Performing Test FEATURE_xop_FLAG
> -- Performing Test FEATURE_xop_FLAG - Success
> -- argon2: feature 'xop' detected!
> -- argon2: detecting feature 'avx2'...
> -- Performing Test FEATURE_avx2_NOFLAG
> -- Performing Test FEATURE_avx2_NOFLAG - Failed
> -- Performing Test FEATURE_avx2_FLAG
> -- Performing Test FEATURE_avx2_FLAG - Success
> -- argon2: feature 'avx2' detected!
> -- argon2: detecting feature 'avx512f'...
> -- Performing Test FEATURE_avx512f_NOFLAG
> -- Performing Test FEATURE_avx512f_NOFLAG - Failed
> -- Performing Test FEATURE_avx512f_FLAG
> -- Performing Test FEATURE_avx512f_FLAG - Success
> -- argon2: feature 'avx512f' detected!
> -- Found OpenSSL: C:/msys64/mingw64/lib/libcrypto.a (found version "1.1.1j")
> -- The ASM compiler identification is GNU
> -- Found assembler: C:/msys64/mingw64/bin/cc.exe
> -- Configuring done
> -- Generating done

But "make" fails and doesn't create the miner. Plz help solve the problem.

**Comment by Bendr0id** [comment]
Download xmrig-deps (https://github.com/xmrig/xmrig-deps) and set "-DXMRIG_DEPS=c:/xmrig-deps/gcc/x64" to your local dir.

**Comment by Bendr0id** [comment]
Or download hwloc and compile it in mingw too and install (make && make install)

**Comment by Bendr0id** [comment]
Linux compiles fine with `cmake . -DWITH_HWLOC=OFF` will test windows later

**Comment by Bendr0id** [comment]
Windows compiles fine too. ` cmake . -G "Unix Makefiles" -DWITH_HWLOC=OFF -DXMRIG_DEPS=c:/xmrig-deps-3.5/gcc/x64
`

```
[100%] Linking CXX executable xmrigMiner.exe
[100%] Built target xmrigMiner
```

**Comment by Bendr0id** [comment]
Does it work?

**Comment by Bendr0id** [comment]
No response.
