### ISSUE TITLE
playing with multihash factor

### ISSUE THREAD

**Issue by untoreh** [Bendr0id/xmrigCC#34]
hello I have a ryzen 1700
this is what I get
```
threads=2 mhf=3 370-380mh/s
threads=2 mhf=4 270-280mh/s
threads=4 mhf=2 350-360mh/s
threads=4 mhf=3 aff=0x1111 mask=0x5 340-350mh/s
```
I imagined the last one would perform better but maybe the system must be completely idle. Anyway running only 2 threads and get the same if not more as of running 4 threads is great!

**Comment by Bendr0id** [comment]
Thanks for sharing!

Could you please try:
Affinity 0x5555
Threads 8
Mhf 2
Aesni 1

**Comment by untoreh** [comment]
mhf 2 would require 4MB of L3 per thread that would be 32MB while the ryzen has 16MB, in fact it performs poorly with `180mh/s`.
I didn't mention `threads=8 mhf=1` because it performs the same like stock xmrig, that is `500-510mh/s`
actually this was something curious since in the readme it's written that the 1950x performs better on xmrigcc but the L3 cache is aligned with the number of cores so it should yield the same like stock xmrig, while the ryzen 1600 has same L3 as ryzen 1700 but less cores so in this case I can see xmrigCC performing better

**Comment by Bendr0id** [comment]
Sorry it was a mistake/typo, I meant mhf=1 of course.  Problem with xmrig stock is that on some processors it's not able to do cpu affinity correct, which is fixed in XMRigCC

**Comment by Bendr0id** [comment]
And you are right, when L3 is big enough to handle 16t (1700) or 16t*2 (1950x) the boost is much less then on cpus like the 1600. The only benefit you can have is to run some threads in double hash to reduce cpu load with almost the same hashrate.
