### ISSUE TITLE
Haven coin don't mine at pools

### ISSUE THREAD

**Issue by borodamd** [Bendr0id/xmrigCC#344]
Good day.
I was trying to mine haven coin, but there is strange things happened. Miner shows what mining goes, but pool don't see this workers. I was trying 3 different pools, but result is same. A;lso this problem and with windows and with linux client. With pure xmrig no such problems.

Here is screrenshot of miner window:
![xhv](https://user-images.githubusercontent.com/8099685/117924982-49d48080-b2ff-11eb-8393-05e08f922a28.png)

Here is config code:

    "pools": [
        {
            "algo": "cryptonight-heavy",
			"pow-variant": "xhv",
            "url": "haven.herominers.com:10451",
            "user": "WALLET",
            "pass": "bwork-test",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": "",
            "daemon": false,
            "socks5": null,
            "self-select": null
        }

**Comment by uz-spark** [comment]
As you can see in the log, the pool rejects your shares because you're using the wrong PoW. The one you need to use even listed in the how to start section on Herominers, it's cn-heavy/xhv, not cn-heavy/0.

**Comment by borodamd** [comment]
Thanks a lot. It's working now.
Solution was put in config 
"algo": "cn-heavy/xhv"
and remove pow-variant,
