### ISSUE TITLE
Enable Huge Pages for macos

### ISSUE THREAD

**Issue by Y8405** [Bendr0id/xmrigCC#345]
Hey guys I was wondering how to enable Huge Pages or I think it's called Super Pages for macos as described on Xmrig.com. I managed to activate it through gpedit for my windows 10 pc for CPU mining.

Although when I run Xmrig on my Mac it shows as supported but doesn't load.

Thank you for help :)

**Comment by Bendr0id** [comment]
On mac just make sure you run it as root or user with superuser rights. The rest should be done by the miner automaticall then.

**Comment by killerTiptoe** [comment]
I Don't unstnd!!!what should i must to run>?
