### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by snakus** [Bendr0id/xmrigCC#349]
When I query http://nas.ntpt.pl:3344/admin/getClientStatusList all workes RUNNING even if some of them are offline

**Comment by uz-spark** [comment]
Looking at the code, that's a different status, it only has 'RUNNING', 'PAUSED' and 'CONFIG_UPDATED' values. You're looking for 'last_status_update' which is the time (amount of seconds from the start of the epoch) when the client was in contact last time in comparison with 'current_server_time' at the start of the JSON.

**Comment by snakus** [comment]
So i must write function to check last_status_update time for worker ?

**Comment by uz-spark** [comment]
Yup, with the threshold of 60 seconds to match the dashboard data.

**Comment by snakus** [comment]
Ok i writed wait to see if it works Thank You.
