### ISSUE TITLE
xmrigDaemon improvements

### ISSUE THREAD

**Issue by untoreh** [Bendr0id/xmrigCC#35]
- The xmrigDaemon spawns the client calling `system()` thus leaving a lingering shell, I have prefixed the command with `exec` to drop the shell and doesn't to appear to have any problems so the shell is not really needed i guess
- the path to the miner is hard coded, it would be useful to provide a custom path, however the daemon doesn't read the config file, so maybe it should be an arg or an env var or another small config file? Again this can kind of worked around currently with a symlink or a scripts that execs into the preferred path
- the miner happily runs as long as you start it with `--daemonized`, wouldn't it be better with some sort of IPC? or maybe it is needless complications

**Comment by Bendr0id** [comment]
Good idea with the shell, will try it out later. 

I already thought about a way to put miner path as param. I think i'll add some additional parsing of the args to the daemon.

About the --daemonized option, sure everybody can start the miner without the daemon by adding this option. Honestly it is just a vehicle to reduce misuage and "bugs" in this tracker about "When i change config miner stops"

The miner can work without the daemon, daemon is only there to restart the miner on config changes or when the process is killed. This function can also be covered by a systemd service on linux or a sc service on windows.

**Comment by untoreh** [comment]
I guess if someone really wants can just switch the flag on at compile time, it could also be its own parameter in the config not included and off by default, it depends how much miusage you think it would cause :)

**Comment by FranzDE** [comment]
@Bendr0id 
"The miner can work without the daemon, **daemon is only there to restart the miner on config changes _or when the process is killed_**. This function can also be covered by a systemd service on linux or a sc service on windows."

If I run the deamon and close the miner with the task manager, the miner process is not restarted. It would be nice and I would avoid a bit 'of problems.

To have automatic restart I had to realize this code:
start.bat
```
@echo off
:Restart
start "xmrigMiner" /wait "C:\path_to_miner_folder\xmrigMiner.exe"
goto Restart
```
but in this code I can not integrate --daemonized option :(
Is it possibile to compile the miner to use it directly without the deamon?

I was thinking of integrating this code:
```
@echo off
:Restart
start "Winstep Xtreme" /wait "C:\Program Files (x86)\Winstep\WinstepXtreme.exe"
goto Restart
```

**Comment by FranzDE** [comment]
I see on the new release the auto-restart option. good
I suggest a delay for some possible issue.

```
@echo off
:Restart
start "xmrigMiner" /wait "C:\path_to_miner_folder\xmrigMiner.exe" --daemonized
TIMEOUT 30
goto Restart
```

**Comment by FranzDE** [comment]
@Bendr0id I see on the new release 1.5.5 the auto-restart option. good
I suggest a delay in the code for some possible issue.

@echo off
:Restart
start "xmrigMiner" /wait "C:\path_to_miner_folder\xmrigMiner.exe" --daemonized
TIMEOUT 30
goto Restart

**Comment by andreytsushima** [comment]
Can you create like param.h to customize config file name or xmrigMiner.exe?

**Comment by Bendr0id** [comment]
Can be done via cmake. Open CMakelists.txt at the top you can define the names. Then remove cmakecache.txt and call cmake again. Then build.

Am 10.08.2018 05:36 schrieb andreytsushima <notifications@github.com>:

Can you create like param.h to customize config file name or xmrigMiner.exe?
