### ISSUE TITLE
Why is this difference?

### ISSUE THREAD

**Issue by can-acar** [Bendr0id/xmrigCC#353]
During the process, the "donate.greaf.in" address interrupts my mining process and uses the entire CPU. When I make a comparison, the "hash rate" in donation mining is around 3000 H/s.
Why can't I see more than 3000H/s in my normal mining job and why is this difference?

![image](https://user-images.githubusercontent.com/644199/120367488-9832d900-c319-11eb-8f16-40e7868caba3.png)

**Comment by uz-spark** [comment]
Because the rx/0 and rx/wow algorithms are different ?

**Comment by Bendr0id** [comment]
rx/wow (wownero) algo is running much faster than rx/0 (monero).

My donation proxy changed the coin to mine based on profit.
