### ISSUE TITLE
Intel XEON 2680 V2 (25 MB Cache)

### ISSUE THREAD

**Issue by rizwansarwar** [Bendr0id/xmrigCC#36]
Hi, 
I saw in your main page that you have achieved a hash rate of 2500 with 2x XEON 2670. I have 2x XEON 2680 with 25MB Cache. I have ESXi running on this box, and I have only one VM on this ESXi that does the mining. I have only been able to get close 990 H/s. I can't all be ESXi eating up the performance? Do you mind sharing what (OS, MEM, HARDWARE) you used to benchmark your tests? If you are right then I am loosing a lot by running a VM, and switching to Bare Metal might triple my hash rate. Thanks

**Comment by Bendr0id** [comment]
Hi sorry for late response. 

I haven't done this test on my own, a user send me the report. 

But i think it was 3300 on AEON and i mixed it up. Sorry for that. 

I changed it on the README.

But i looked at the specs. Of the E5-2680v2

So for each cpu you should get max by aligning 12 threads to each cpu, putting 11 threads on singlehash and one thread on doublehash.

I think you are using linux in that vm, so it should be:

"aesni" : 1,
"threads" : 24,
"cpu-affinity" : "0xC03FFFFF" // 11000000001111111111111111111111
"multihash-thread-mask": "0x401" // run multihash on cpu0 core0 and cpu1 core=0
"multihash-factor":2,

Please try these settings, maybe there is still little improvement.

**Comment by rizwansarwar** [comment]
Hi, 
Thanks for quick response, I was wondering exactly that, seemed unreal :).

Anyway I tried your settings, they max out at 1040. I have however been able to 1250 with both your miner and XMR-STAK. I will post the settings a bit later as I was trying many different mask settings and one of them resulted in 1250H/s, which I think is the max for this CPU, I can't squeeze any more out of it lol. Thanks for response.
