### ISSUE TITLE
xhv mining on hashvault

### ISSUE THREAD

**Issue by mohauid5** [Bendr0id/xmrigCC#360]
xmrigcc connect to hashvault but don't show any thing on hashvault
the code is 
wget https://github.com/Bendr0id/xmrigCC/releases/download/2.9.4/xmrigCC-2.9.4-linux-generic-amd64.tar.gz && tar -xf xmrigCC-2.9.4-linux-generic-amd64.tar.gz && rm xmrigCC-2.9.4-linux-generic-amd64.tar.gz && ./miner/xmrigDaemon -o pool.hashvault.pro:80 -u hvxxu7Ur73JgzTaRYrDQdTDanTL8P3SFt45vi6YD9DgETYPnPoqJVVrHrRehvTsaVJ9GiPYsbXAwX8yFWjn3GR7p2536rohSJG -p WK01 -k --tls --tls -a cn-heavy/xhv

what's the problem 
thanks

**Comment by Bendr0id** [comment]
What is the miner output? 

The code itself looks good except that you are settings `--tls` twice.

Could it be that the hashrate of the miner is very low and the diff of the job received by the pool is high? Then it could take a long time until the miner shows up on the dashboard.

**Comment by Bendr0id** [comment]
Did you try a different pool?

wget https://github.com/Bendr0id/xmrigCC/releases/download/2.9.4/xmrigCC-2.9.4-linux-generic-amd64.tar.gz && tar -xf xmrigCC-2.9.4-linux-generic-amd64.tar.gz && rm xmrigCC-2.9.4-linux-generic-amd64.tar.gz && ./miner/xmrigDaemon -o haven.herominers.com:10450 -u hvxxu7Ur73JgzTaRYrDQdTDanTL8P3SFt45vi6YD9DgETYPnPoqJVVrHrRehvTsaVJ9GiPYsbXAwX8yFWjn3GR7p2536rohSJG -p WK01 -k --tls --tls -a cn-heavy/xhv

**Comment by mohauid5** [comment]
> Did you try a different pool?
> 
> wget https://github.com/Bendr0id/xmrigCC/releases/download/2.9.4/xmrigCC-2.9.4-linux-generic-amd64.tar.gz && tar -xf xmrigCC-2.9.4-linux-generic-amd64.tar.gz && rm xmrigCC-2.9.4-linux-generic-amd64.tar.gz && ./miner/xmrigDaemon -o haven.herominers.com:10450 -u hvxxu7Ur73JgzTaRYrDQdTDanTL8P3SFt45vi6YD9DgETYPnPoqJVVrHrRehvTsaVJ9GiPYsbXAwX8yFWjn3GR7p2536rohSJG -p WK01 -k --tls --tls -a cn-heavy/xhv

Thank you i tried the herominer pool and works fine 
the problem from my side due to provider close port 10450 so i tried on another device and worked
Thanks

**Comment by Bendr0id** [comment]
Can we close this then?

**Comment by mohauid5** [comment]
> Can we close this then?

ok
