### ISSUE TITLE
Broken text formatting in Telegram in v2.9.6

### ISSUE THREAD

**Issue by ORGaniZMo** [Bendr0id/xmrigCC#366]
> XMRigCC%20Status%0A%0AMiners:%2034%20(Online)%2C%200%20(Offline)%0AShares:%201504%20(Good)%2C%2027%20(Bad)%0AHashrates:%2042656.3h/s%20(1min)%2C%2034710.2h/s%20(15min)%0AAvg.%20Time:%20105.353s

**Comment by Bendr0id** [comment]
Fixed on master
