### ISSUE TITLE
Unable to Mine

### ISSUE THREAD

**Issue by sachinvupparige** [Bendr0id/xmrigCC#367]
Hi Guys,
I am very Noob in all these so need help please. I am trying to mine Scala( Panthere) I am using XMRIGCC proxy to connect my couple of rigs to it( I am using XMRIGCC as my miner) . When I run XMRIGCC proxy it doesnt give any error however when i run  my miner it continuously give Error: ****unable to perforrequest POST -> http://sg.scala.herominers.com:1190/client/setclientstatus?clientID=PCname****

Code in XMRIGG CC proxy as follows --- 

{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 1111,
            "tls": false
        },
        {
            "host": "0.0.0.0",
            "port": 2222,
            "tls": false
        }
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 2,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "panthera",
            "coin": "scala",
            "url": "sg.scala.herominers.com:1190",
            "user": "wallet",
            "pass": "x",
            "rig-id": null,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

Code in Miner as follows ---
{
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "autosave": true,
    "version": 1,
    "background": false,
    "colors": true,
    "randomx": {
        "init": -1,
        "init-avx2": -1,
        "mode": "auto",
        "1gb-pages": false,
        "rdmsr": true,
        "wrmsr": true,
        "cache_qos": false,
        "numa": true,
        "scratchpad_prefetch_mode": 1
    },
    "cpu": {
        "enabled": true,
        "huge-pages": true,
        "huge-pages-JIT": false,
        "hw-aes": null,
        "priority": null,
        "max-cpu-usage": null,
        "memory-pool": false,
        "yield": true,
        "force-autoconfig": false,
        "max-threads-hint": 100,
        "asm": true,
        "argon2-impl": null,
        "astrobwt-max-size": 550,
        "astrobwt-avx2": false,
        "argon2": [0, 2, 3],
        "astrobwt": [0, 1, 2, 3],
        "cn": [
            [1, 0],
            [1, 2]
        ],
        "cn-extremelite": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3]
        ],
        "cn-heavy": [
            [1, 0]
        ],
        "cn-lite": [
            [1, 0],
            [1, 2],
            [1, 3]
        ],
        "cn-pico": [
            [2, 0],
            [2, 1],
            [2, 2],
            [2, 3]
        ],
        "panthera": [0, 2],
        "rx": [0, 2],
        "rx/arq": [0, 1, 2, 3],
        "rx/wow": [0, 2, 3],
        "rx/yada": [0, 2],
        "cn/0": false,
        "cn-lite/0": false,
        "rx/keva": "rx/wow"
    },
    "donate-level": 1,
    "donate-over-proxy": 0,
    "log-file": null,
    "pools": [
        {
            "algo": null,
            "coin": null,
            "url": "192.16.0.14:1111",
            "user": "wallet",
            "spend-secret-key": null,
            "pass": "x",
            "rig-id": null,
            "nicehash": false,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false,
            "socks5": null,
            "self-select": null
        }
    ],
    "cc-client": {
        "enabled": true,
        "use-tls": false,
        "use-remote-logging": true,
        "upload-config-on-start": true,
        "url": "sg.scala.herominers.com:1190",
        "access-token": "mySecret",
        "worker-id": null,
        "reboot-cmd": null,
        "update-interval-s": 10
    },
    "print-time": 60,
    "retries": 5,
    "retry-pause": 5,
    "syslog": false,
    "user-agent": null,
    "watch": true
}

Please guide me where I am going wrong.

**Comment by uz-spark** [comment]
You're trying to connect the CC client to CC server at the "sg.scala.herominers.com:1190", it can't connect because that's not a CC server. If you don't need a CC functionality then set "enabled" to false in "cc-client" section. If you do, you need to run a CC server too, and point your clients to the right address.

**Comment by uz-spark** [comment]
Also you've just compromised your pool account, someone viewing this can copy your address and ask Herominers to move it's balance to another address. Snip it.

**Comment by sachinvupparige** [comment]
> Also you've just compromised your pool account, someone viewing this can copy your address and ask Herominers to move it's balance to another address. Snip it and generate a new address or use different pool

Its ok, there is nothing in... Thank you very much for letting me know.

**Comment by sachinvupparige** [comment]
> You're trying to connect the CC client to CC server at the "sg.scala.herominers.com:1190", it can't connect because that's not a CC server. If you don't need a CC functionality then set "enabled" to false in "cc-client" section. If you do, you need to run a CC server too, and point your clients to the right address.

This part, sounded like greek to me :-(. Could you please guide me here, What I should be doing.. It will be great help

**Comment by sachinvupparige** [comment]
> You're trying to connect the CC client to CC server at the "sg.scala.herominers.com:1190", it can't connect because that's not a CC server. If you don't need a CC functionality then set "enabled" to false in "cc-client" section. If you do, you need to run a CC server too, and point your clients to the right address.

Hey Thank you very much, After "enabled": false, now error disappeared. however.. your next advise  If you do, you need to run a CC server too, and point your clients to the right address.
Could you please tell me how to do it.
