### ISSUE TITLE
connection refused error on XMRigCC miner

### ISSUE THREAD

**Issue by sachinvupparige** [Bendr0id/xmrigCC#368]
Hello @Bendr0id and all,  I have an issue with XMRIGCC, I have set my proxy setting as follows 

{
    "access-log-file": null,
    "access-password": null,
    "algo-ext": true,
    "api": {
        "id": null,
        "worker-id": null
    },
    "http": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 0,
        "access-token": null,
        "restricted": true
    },
    "background": false,
    "bind": [
        {
            "host": "0.0.0.0",
            "port": 1111,
            "tls": false
        },
        {
            "host": "0.0.0.0",
            "port": 2222,
            "tls": false
        },
         {
            "host": "0.0.0.0",
            "port": 5555,
            "tls": false
        }
    ],
    "colors": true,
    "custom-diff": 0,
    "donate-level": 2,
    "log-file": null,
    "mode": "nicehash",
    "pools": [
        {
            "algo": "panthera",
            "coin": "scala",
            "url": "sg.scala.herominers.com:1190",
            "user": "Wallett",
            "pass": "x",
            "rig-id": null,
            "keepalive": false,
            "enabled": true,
            "tls": false,
            "tls-fingerprint": null,
            "daemon": false
        }
    ],
    "retries": 2,
    "retry-pause": 1,
    "reuse-timeout": 0,
    "tls": {
        "protocols": null,
        "cert": null,
        "cert_key": null,
        "ciphers": null,
        "ciphersuites": null,
        "dhparam": null
    },
    "user-agent": null,
    "syslog": false,
    "verbose": false,
    "watch": true,
    "workers": true
}

Apart from Port numbers 1111, 2222 if i use any other port I am getting Connection refused error,. I have totally 6 computer rigs. because of the error I can connect only two computers. Please help me what is the fix for this. tried port number : 3333,4444,5555,6666,7777,8888,9999 all are giving the same error. If I use port number 2222,1111 on same system it is working fine.

![image](https://user-images.githubusercontent.com/89645301/135522404-de9f1478-3097-4da2-91cb-605ecf18d0ba.png)

**Comment by Bendr0id** [comment]
Looks like a firewall issue then.

First, why do you need so much ports for 6 rigs? That doesnt make sense at all they can use all the same.

Second who told you that you need a proxy for 6 rigs? I mean, ok for 60+ but not for 6.

Third, you're not using my miner (xmrigcc), so better ask the xlarig guys.

**Comment by HankFit247** [comment]
I had a similar issue with XMRig Proxy.

Disable Firewall, then add the ports to your config.json

"bind": [
    {
        "host": "0.0.0.0",
        "port": 1111,
        "tls": false
    },
    {
        "host": "0.0.0.0",
        "port": 2222,
        "tls": false
    },
    {
        "host": "0.0.0.0",
        "port": 3333,
        "tls": false
    },
    {
        "host": "0.0.0.0",
        "port": 4444,
        "tls": false
    },
    {
        "host": "0.0.0.0",
        "port": 5555,
        "tls": false
    },
	{
        "host": "0.0.0.0",
        "port": 6666,
        "tls": false
    }
    
    Once your machines are connecting successfully, then revisit your firewall.

**Comment by Bendr0id** [comment]
No response, so closed
