### ISSUE TITLE
Raspberry Pi4 as xmrigCC Server - installation instructions help

### ISSUE THREAD

**Issue by HankFit247** [Bendr0id/xmrigCC#369]
I'm hoping someone can assist here.

1. sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
2. git clone https://github.com/Bendr0id/xmrigCC.git
3. mkdir xmrigCC/build && cd xmrigCC/build
4. cmake ..
5. make -j4

[ 76%] Building CXX object CMakeFiles/xmrigMiner.dir/src/crypto/common/VirtualMemory_hwloc.cpp.o
make[2]: *** [CMakeFiles/xmrigMiner.dir/build.make:1285: CMakeFiles/xmrigMiner.dir/src/crypto/cn/CnHash.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

From here, I'm not sure what I need to do to resolve the errors.

**Comment by Bendr0id** [comment]
So ou did not actually copy the build issue just the summary..

But I would expect that you run out of memory while compiling. 

Can you try calling make -j1 instead of -j4

**Comment by HankFit247** [comment]
make -j1

results in:

[ 70%] Building CXX object CMakeFiles/xmrigMiner.dir/src/crypto/cn/CnHash.cpp.o
In file included from /home/pi/xmrigCC/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrigCC/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrigCC/src/crypto/cn/sse2neon.h: In function '__m128i _mm_aesenc_si128(__m128i, __m128i)':
/home/pi/xmrigCC/src/crypto/cn/sse2neon.h:4026:31: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) const __m128i zero = { 0 };
                               ^~~~
In file included from /home/pi/xmrigCC/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h: In function '__m128i aes_round_tweak_div(const __m128i&, const __m128i&)':
/home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:460:29: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) uint32_t k[4];
                             ^
/home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:461:29: warning: requested alignment 16 is larger than 8 [-Wattributes]
     alignas(16) uint32_t x[4];
                             ^
In file included from /home/pi/xmrigCC/src/crypto/cn/sse2neon.h:65,
                 from /home/pi/xmrigCC/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrigCC/src/crypto/cn/CnHash.cpp:35:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h: In function '__m128i _mm_setzero_si128()':
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:16143:1: error: inlining failed in call to always_inline 'int64x2_t vreinterpretq_s64_s32(int32x4_t)': target specific option mismatch
 vreinterpretq_s64_s32 (int32x4_t __a)
 ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/pi/xmrigCC/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrigCC/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrigCC/src/crypto/cn/sse2neon.h:146:57: note: called from here
 #define vreinterpretq_m128i_s32(x) vreinterpretq_s64_s32(x)
                                    ~~~~~~~~~~~~~~~~~~~~~^~~
/home/pi/xmrigCC/src/crypto/cn/sse2neon.h:350:12: note: in expansion of macro 'vreinterpretq_m128i_s32'
     return vreinterpretq_m128i_s32(vdupq_n_s32(0));
            ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/pi/xmrigCC/src/crypto/cn/sse2neon.h:65,
                 from /home/pi/xmrigCC/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrigCC/src/crypto/cn/CnHash.cpp:35:
/usr/lib/gcc/arm-linux-gnueabihf/8/include/arm_neon.h:6733:1: error: inlining failed in call to always_inline 'int32x4_t vdupq_n_s32(int32_t)': target specific option mismatch
 vdupq_n_s32 (int32_t __a)
 ^~~~~~~~~~~
In file included from /home/pi/xmrigCC/src/crypto/cn/soft_aes.h:31,
                 from /home/pi/xmrigCC/src/crypto/cn/CryptoNight_arm.h:35,
                 from /home/pi/xmrigCC/src/crypto/cn/CnHash.cpp:35:
/home/pi/xmrigCC/src/crypto/cn/sse2neon.h:146:57: note: called from here
 #define vreinterpretq_m128i_s32(x) vreinterpretq_s64_s32(x)
                                    ~~~~~~~~~~~~~~~~~~~~~^~~
/home/pi/xmrigCC/src/crypto/cn/sse2neon.h:350:12: note: in expansion of macro 'vreinterpretq_m128i_s32'
     return vreinterpretq_m128i_s32(vdupq_n_s32(0));
            ^~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/xmrigMiner.dir/build.make:1285: CMakeFiles/xmrigMiner.dir/src/crypto/cn/CnHash.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:127: CMakeFiles/xmrigMiner.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Bendr0id** [comment]
is that a 32bit rpi?

Did you try my binaries.. Did they work?

**Comment by HankFit247** [comment]
It's a Raspberry Pi 4 Model B Quad Core 64 Bit w\ 8gb ram

I'm going to pick up a fresh SD Card today, and install a fresh OS.

**Comment by HankFit247** [comment]
New SD Card:

Raspberry Pi OS (64-bit) Lite
05-07-2021
https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2021-05-28/

$ uname -a
aarch64

$ gcc -v
gcc version 8.3.0 (Debian 8.3.0-6)

$ sudo apt-get install git build-essential cmake libuv1-dev libssl-dev libhwloc-dev
$ git clone https://github.com/Bendr0id/xmrigCC.git
$ mkdir xmrigCC/build && cd xmrigCC/build
$ cmake ..
$ make -j1

Build completed without issue!!!

**Comment by Bendr0id** [comment]
Ok cool. I'll close this then.
