### ISSUE TITLE
Feature Request: Implement SSL support and login/pw

### ISSUE THREAD

**Issue by stevenmcastano** [Bendr0id/xmrigCC#37]
First of... fantastic project, I love it... I just updated all of my CPU based mining rigs!!

One thing I would love to see is the ability to support SSL for when clients are checking in and doing their posts. I'm running my xmrigCCServer behind nginx and haproxy so I can have redundant dashboards and so clients from multiple different locations can log in. I basically enforce SSL for everything and when doing so, the clients can check in anymore. So I found a work around to have clients check in with SSL but use SSL and a login/pw for admin... but out of the box support would be awesome!

**Comment by Bendr0id** [comment]
I'm already working on implementing tls/ssl support for the stratum (pool) communication. Once this is done i need to think about a way todo that for the miner to server and server/dashboard to browser communication. 

Problem here is, with my current knowledge, it won't work without creating a self signed certificate on server side. Which isn't a problem on linux servers, but i dont have a easy solution to create a certificate on Windows.

For the miner to server communication i could use something like TLS-SRP or PSK which doesn't need a certificate. But for server/dashboard to browser communication i currently don't have a proper solution. Feel free to share if you know a way without certificate.

**Comment by Bendr0id** [comment]
Status Update TLS/SSL:

CC: Done
*  XMRigCC Server -> Dashboard
*  XMRigCC Miner -> XMRigCC Server

Stratum: In progress
*  XMRigCC Miner -> Pool

**Comment by Bendr0id** [comment]
@stevenmcastano feel free to try dev-tls branch. Its now working. Will be merged to master soon.

**Comment by stevenmcastano** [comment]
Will do, this is exactly what I was waiting for to let my clients connect publicly rather than through a VPN tunnel.
