### ISSUE TITLE
Documentation Issue in xmrigcc-proxy, Build instructions.

### ISSUE THREAD

**Issue by HankFit247** [Bendr0id/xmrigCC#372]
Page:
https://github.com/Bendr0id/xmrigcc-proxy

Line:
Clone with git clone https://github.com/bendr0id/xmrigcc-proxy.git 🔨 Build instructions.

Build Instructions points to:
https://github.com/xmrig/xmrig-proxy/wiki/Build

There is no "Issues" section, otherwise I would have posted there...

**Comment by Bendr0id** [comment]
It's the same as the stock xmrig-proxy. That's why it's pointing it to the same page. Laziness of copy and pasting the same.
