### ISSUE TITLE
release for FreeBSD? 

### ISSUE THREAD

**Issue by PSLLSP** [Bendr0id/xmrigCC#376]
You have impressive collection of build binaries. I still miss one, version for FreeBSD. `xmrig` has that build, like **xmrig-6.16.2-freebsd-static-x64.tar.gz**

FreeNAS/TrueNAS is build on FreeNAS and it supports jails and one of plugins is `xmrig`, to create xmrig jails. xmrig-6.16.2-freebsd-static-x64.tar.gz can be used to replace (upgrade) miner in xmrig jail.

Could you produce build for FreeBSD? Or even plugin xmrigCC for TrueNAS?? ;-) This is low priority wish...

**Comment by Bendr0id** [comment]
I don't have a NAS but I can setup a FreeBSD build machine and include binaries in the next release. 

I thought that the static generic Linux build will also work for FreeBSD. Did you tried that?

**Comment by PSLLSP** [comment]
No, Linux version don't work...

xmrig that is installed from plugin; it doesn't mine GhostRider on older CPU (AMD X4 AM3), it ends with coredump:
```
root@xmrig-x:~ # uname -a
FreeBSD xmrig-x 12.2-RELEASE-p11 FreeBSD 12.2-RELEASE-p11 75566f060d4(HEAD) TRUENAS  amd64

root@xmrig-x:~ # file /usr/local/bin/xmrig
/usr/local/bin/xmrig: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked,

root@xmrig-x:~ # /usr/local/bin/xmrig --version
XMRig 6.16.2
 built on Jan 12 2022 with clang 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2)
 features: 64-bit AES

libuv/1.42.0
OpenSSL/1.1.1h-freebsd
hwloc/2.5.0
```

xmrigCC, Linux version, it cannot be started at all:
```
root@xmrig-x:~ # file xmrigCC/miner/xmrigDaemon
xmrigCC/miner/xmrigDaemon: ELF 64-bit LSB executable, x86-64, version 1 (SYSV),statically linked, stripped

root@xmrig-x:~ # xmrigCC/miner/xmrigDaemon --version
ELF binary type "0" not known.
xmrigCC/miner/xmrigDaemon: Exec format error. Binary file not executable.

root@xmrig-x:~ # xmrigCC/miner/xmrigDaemon -c config.json
ELF binary type "0" not known.
xmrigCC/miner/xmrigDaemon: Exec format error. Binary file not executable.
```
xmrig from xmrig-6.16.2-freebsd-static-x64.tar.gz, it works without any issue:
```
root@xmrig-x:~ # file xmrig-6.16.2/xmrig
xmrig-6.16.2/xmrig: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), statically linked, for FreeBSD 11.4, FreeBSD-style, stripped

root@xmrig-x:~ # xmrig-6.16.2/xmrig --version
XMRig 6.16.2
 built on Dec  2 2021 with clang 10.0.0 (git@github.com:llvm/llvm-project.git llvmorg-10.0.0-0-gd32170dbd5b)
 features: 64-bit AES

libuv/1.42.0
OpenSSL/1.1.1l
hwloc/2.5.0
```

**Comment by Bendr0id** [comment]
Added freebsd static binaries to the release 3.0.0

Can you please verify if that fits for you?

Thanks in advance,

**Comment by Bendr0id** [comment]
Miner only:
https://github.com/Bendr0id/xmrigCC/releases/download/3.0.0/xmrigCC-miner_only-3.0.0-freebsd-static-amd64.tar.gz

Miner+Server:
https://github.com/Bendr0id/xmrigCC/releases/download/3.0.0/xmrigCC-3.0.0-freebsd-static-amd64.tar.gz

**Comment by PSLLSP** [comment]
I did fast test and it works, I do not see any issue! Well, it reports miner version as Linux (not FreeBSD) but the same is with original xmrig... The version is visible on some pools, **XMRigCC/3.0.0 (Linux x86_64) libuv/1.42.0 clang/11.0.1**.

I will play with this miner, I have to explore remote control, it looks like a cool feature...

**Comment by Bendr0id** [comment]
Sure, let me know if I can help you.

Feel free to join the discord and/or telegram channel for support.
