### ISSUE TITLE
where to Host Index.html Files

### ISSUE THREAD

**Issue by info4mationprivate8tools** [Bendr0id/xmrigCC#389]
i am very Beginner where to host files ?

**Comment by Bendr0id** [comment]
The file is hosted through the xmrigServer. You can't just put the index.html file in a Webserver. That doesn't work. The xmrigServer provides all the needed webservices.

Regards,
Bendr0id

**Comment by Bendr0id** [comment]
All clear?

**Comment by info4mationprivate8tools** [comment]
think i have multiple pc on other network how i control all pc in my one server dashboard

**Comment by Bendr0id** [comment]
Start the server on one machine on the network, make sure the firewall has opened port 3344 on that machine, on the miner pcs in the config.json set the server ip.

like this:

`
 "cc-client": {
        "enabled": true,
        "url": "yourServerIp:3344",
        "access-token": "mySecret",
        "use-tls": false,
        "use-remote-logging": true,
        "upload-config-on-start": true,
        "worker-id": null,
        "reboot-cmd": null,
        "update-interval-s": 10
    },
`

**Comment by info4mationprivate8tools** [comment]
ok can i run this config on simple xmrig

**Comment by info4mationprivate8tools** [comment]
if i have my own linux server its possible i manage my all miner c2 from linux server ??
sorry for my bad english
