### ISSUE TITLE
Are you able to compile a 32-bit arm binary release?

### ISSUE THREAD

**Issue by kensagle** [Bendr0id/xmrigCC#39]
I have some older androids running arm71 that work well with xmrig in termux, but would like to use your version for the management features.

This is a great project!  Excellent work!

**Comment by kensagle** [comment]
I got it to work.  I had to add #include <errno.h> to /src/cc/XMRigd.cpp. or I would get EINTR undefined error.

**Comment by Bendr0id** [comment]
Cool, i currently don't have a 32bit arm machine somewhere to compile static builds. Maybe i can create one with my raspberry.

**Comment by Bendr0id** [comment]
Btw. will add that include to next release too.
