### ISSUE TITLE
xmrigcc Issue

### ISSUE THREAD

**Issue by Phrazor** [Bendr0id/xmrigCC#393]
Hallo !

Bin gerade dabei xmrigcc auf ein paar Rechnern zu installieren und diese dann über eine Internetadresse auf meinen Pi den Status schicken zu lassen ... Lokal kein Problem aber übers Internet krieg ich immer sporadisch folgenden Fehler und leider fliegt auch kurzfristig dann immer der Client raus kommt aber nach ein paar Sekunden wieder...: 

error:unable to performRequest POST [https://Domain.tld:3344/client/setClientStatus?clientId=blablablubb]

Habe auch aktuell keinen NGINX davor hängen oder dergleichen... UDM mit direkten Port auf den Raspi ...

Hat einer eine Idee ? Evtl. liest es ja sogar der Entwickler der App :) Deshalb schreib ich auch in meiner Muttersprache xD

Grüsse

**Comment by Bendr0id** [comment]
Hallo, 
Schreib mich am besten über telegram oder discord an, dann können wir deine Einstellungen durchgehen.

LG,
Ben
