### ISSUE TITLE
Build Static Android ARMv8

### ISSUE THREAD

**Issue by sradityaa** [Bendr0id/xmrigCC#395]
How can I create static complications for ARMv8 android like the ones in release?

Help please..

**Comment by sradityaa** [comment]
> How can I create static complications for ARMv8 android like the ones in release?
> 
> Help please..

**Comment by sradityaa** [comment]
Like this *-android-dynamic-arm64.tar.gz (CPU+GPU)

**Comment by Bendr0id** [comment]
Either compile on bare metal using alpine to get full static builds or cross compile with a toolchain.

**Comment by Bendr0id** [comment]
*-android-dynamic-arm64.tar.gz is not a static build. It's a dynamic build using the android ndk.

**Comment by sradityaa** [comment]
Sorry I spelled it wrong. Then how do complications? Is there a guide for that?

**Comment by Bendr0id** [comment]
I don't have a guide, i just created my own build suite for it. I think you'll find some help by googling for "xmrig build android".

**Comment by Saikatsaha1996** [comment]
> Sorry I spelled it wrong. Then how do complications? Is there a guide for that?

Why you want for own build ?
You have any issues with `dev-build` ?

**Comment by sradityaa** [comment]
> > Sorry I spelled it wrong. Then how do complications? Is there a guide for that?
> 
> Why you want for own build ? You have any issues with `dev-build` ?

Want to make it work for other ABIs too like Armeabi-v7 a, x86 & x86_64.

**Comment by sradityaa** [comment]
> I don't have a guide, i just created my own build suite for it. I think you'll find some help by googling for "xmrig build android".

Thank you. I've tried it according to your suggestion. And it works fine. But I haven't tried it to see if it will work for other ABIs too.

**Comment by sradityaa** [comment]
> > Sorry I spelled it wrong. Then how do complications? Is there a guide for that?
> 
> Why you want for own build ? You have any issues with `dev-build` ?

Apart from that, I also only want to compile the file miner, without unnecessary daemon files for me.
