### ISSUE TITLE
Please add support for "phi" (haroldcoin)

### ISSUE THREAD

**Issue by realsetvin** [Bendr0id/xmrigCC#409]
Its possible to mine on cpu but preferable to mine on gpu. 

last known open source implementation of phi on open cl gpu 
https://github.com/KL0nLutiy/sgminer-kl

wildrig says he may soon drop support for this algo, and it seems someone is currently abusing the diff adjustment for this coin. Would be very grateful if we could see this added. Thanks for your time and consideration!

**Comment by realsetvin** [comment]
Here is the open source cpu version
https://github.com/tpruvot/ccminer

**Comment by realsetvin** [comment]
![image](https://github.com/Bendr0id/xmrigCC/assets/117243445/4cbe3049-a29b-4a09-b793-ed5934ee9c35)
![image](https://github.com/Bendr0id/xmrigCC/assets/117243445/c7b0c0d9-e0dd-4a40-ae8d-a8a13ec8a9dc)

The coin still has a market on xeggex, working website, online nodes, ext - but its a shame that someone can abuse the system due to lack of available miners. Maybe we can fix that? Please let me know if there is something I can do to help.

**Comment by Bendr0id** [comment]
24h volume is 120$, the effort is not worth it. It has a different network protocol and algo which is waste of energy on a cpu. XMRigCC is focused on CPU coins.
