### ISSUE TITLE
Linux debian 8 Error Build

### ISSUE THREAD

**Issue by Zelecktor** [Bendr0id/xmrigCC#46]
Have latest libuv installed. Already used cmake . and the static cmake but got the same error at 56%

Also have installed gcc g++ gcc-7 g++7

```
root@miner:~/xmrigCC# make
Scanning dependencies of target xmrigDaemon
[  2%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
Linking CXX executable xmrigDaemon
[  2%] Built target xmrigDaemon
Scanning dependencies of target xmrig_cc_common
[  4%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.o
[  6%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.o
Linking CXX static library libxmrig_cc_common.a
[  6%] Built target xmrig_cc_common
Scanning dependencies of target xmrig_common
[  8%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.o
Linking CXX static library libxmrig_common.a
[ 25%] Built target xmrig_common
Scanning dependencies of target cpuid
[ 27%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[ 29%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[ 31%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[ 33%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 35%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
Linking C static library libcpuid.a
[ 35%] Built target cpuid
Scanning dependencies of target xmrig_os_dependencies
[ 37%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_unix.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_unix.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/log/SysLog.cpp.o
Linking CXX static library libxmrig_os_dependencies.a
[ 50%] Built target xmrig_os_dependencies
Scanning dependencies of target xmrig_cpuid
[ 52%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_cpuid.cpp.o
Linking CXX static library libxmrig_cpuid.a
[ 52%] Built target xmrig_cpuid
Scanning dependencies of target xmrigMiner
[ 54%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.o
In file included from /root/xmrigCC/src/workers/Workers.h:34:0,
                 from /root/xmrigCC/src/App.cpp:42:
/root/xmrigCC/src/net/JobResult.h: In member function 'uint64_t JobResult::actualDiff() const':
/root/xmrigCC/src/net/JobResult.h:69:71: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
/root/xmrigCC/src/App.cpp: In static member function 'static void App::onCommandReceived(uv_async_t*)':
/root/xmrigCC/src/App.cpp:268:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
CMakeFiles/xmrigMiner.dir/build.make:77: recipe for target 'CMakeFiles/xmrigMiner.dir/src/App.cpp.o' failed
make[2]: *** [CMakeFiles/xmrigMiner.dir/src/App.cpp.o] Error 4
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/xmrigMiner.dir/all' failed
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by Bendr0id** [comment]
Looks like there is not enough swap/memory to build. Could that be? There is a working prebuild static which works also on old Debian/CentOS. Please consider to use that.

Am 23.02.2018 17:09 schrieb Zelecktor <notifications@github.com>:

Have latest libuv installed. Already used cmake . and the static cmake but got the same error at 56%

root@miner:~/xmrigCC# make
Scanning dependencies of target xmrigDaemon
[  2%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
Linking CXX executable xmrigDaemon
[  2%] Built target xmrigDaemon
Scanning dependencies of target xmrig_cc_common
[  4%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.o
[  6%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.o
Linking CXX static library libxmrig_cc_common.a
[  6%] Built target xmrig_cc_common
Scanning dependencies of target xmrig_common
[  8%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.o
[ 14%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.o
[ 16%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.o
[ 22%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.o
Linking CXX static library libxmrig_common.a
[ 25%] Built target xmrig_common
Scanning dependencies of target cpuid
[ 27%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[ 29%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[ 31%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[ 33%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 35%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
Linking C static library libcpuid.a
[ 35%] Built target cpuid
Scanning dependencies of target xmrig_os_dependencies
[ 37%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.o
[ 39%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
[ 41%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[ 43%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_unix.cpp.o
[ 45%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
[ 47%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_unix.cpp.o
[ 50%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/log/SysLog.cpp.o
Linking CXX static library libxmrig_os_dependencies.a
[ 50%] Built target xmrig_os_dependencies
Scanning dependencies of target xmrig_cpuid
[ 52%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_cpuid.cpp.o
Linking CXX static library libxmrig_cpuid.a
[ 52%] Built target xmrig_cpuid
Scanning dependencies of target xmrigMiner
[ 54%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.o
In file included from /root/xmrigCC/src/workers/Workers.h:34:0,
                 from /root/xmrigCC/src/App.cpp:42:
/root/xmrigCC/src/net/JobResult.h: In member function 'uint64_t JobResult::actualDiff() const':
/root/xmrigCC/src/net/JobResult.h:69:71: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
         return Job::toDiff(reinterpret_cast<const uint64_t*>(result)[3]);
                                                                       ^
/root/xmrigCC/src/App.cpp: In static member function 'static void App::onCommandReceived(uv_async_t*)':
/root/xmrigCC/src/App.cpp:268:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
CMakeFiles/xmrigMiner.dir/build.make:77: recipe for target 'CMakeFiles/xmrigMiner.dir/src/App.cpp.o' failed
make[2]: *** [CMakeFiles/xmrigMiner.dir/src/App.cpp.o] Error 4
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/xmrigMiner.dir/all' failed
make[1]: *** [CMakeFiles/xmrigMiner.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Zelecktor** [comment]
Hello, no its not a memory issue. have 4 GB RAM,  an Intel(R) Xeon(R) CPU E5-2697A v4 @ 2.60GHz
 * CPU L2/L3:    2.2 MB/120.0 MB

I also tried to use your pre-build static for linux but have this error:
"Access deneid" also tried with sudo but it says "command not found"

Thans in advance.

**Comment by Bendr0id** [comment]
That looks more like you have local permission problems, that doesn't sound like an issue to the miner.

Please download this:
```
https://github.com/Bendr0id/xmrigCC/releases/download/1.4.0/xmrigCC-1.4.0-gcc7-linux-static-miner_only-x64.tar.gz
```
Then extract with:

```
tar xvfz xmrigCC-1.4.0-gcc7-linux-static-miner_only-x64.tar.gz
```

Then edit the config.json file for your needings and start the daemon afterwards with:

```
./xmrigDaemon -c config.json
```

If it is not working please send the printout.

**Comment by Zelecktor** [comment]
I see. It isnt work when you drop the files on the root folder, you need to un-compress with the command `tar xvfz`. Yes, it worked. Thanks very much.

But still im having problems to compile by myself. Just because i did some modifications to src to add a little increase performance. But first i need to compile it clean, just as it is the master branch. Maybe i can try with another OS such ubuntu 16 and see what happen. On that case i need to know if i cloud make a custom statik version. (and yes, i'll leave 5% donation as i did with the original xmrig)
Thanks very much

**Comment by Bendr0id** [comment]
Ofcourse you can create a static build. There is a howto in the wiki.

https://github.com/Bendr0id/xmrigCC/wiki/Build-Debian%5CUbuntu#static-build

I think the problem of your compilation is old gcc (4.9) and it looks like there is to less swap space. Please make sure that swap is enabled.

**Comment by Zelecktor** [comment]
Yes i see the wiki, i'll try and advice you. Thanks very much!

This is completely new for me. When you say "swap" you mean with memory available, like RAM and hard drive? or another thing that im ignoring?
And about to enable, i have no idea how to do it :(

**Comment by Bendr0id** [comment]
Whats the output of
```
free -h
```
?

**Comment by Zelecktor** [comment]
```
root@ubuntu-s-3vcpu-1gb-nyc3-01:~# free -h
              total        used        free      shared  buff/cache   available
Mem:           992M         50M        191M         10M        750M        728M
Swap:            0B          0B          0B

```

**Comment by Bendr0id** [comment]
Uuuh. Thats to less mem (Your vm has less then 1GB) to compile. You can workaround that by following:

```
sudo dd if=/dev/zero of=/swapfile bs=1G count=4
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
```

Now the compile should work.

**Comment by Zelecktor** [comment]
issues everywhere! 

```
root@ubuntu-s-3vcpu-1gb-nyc3-01:~# sudo dd if=/dev/zero of=/swapfile bs=1G count=4
dd: memory exhausted by input buffer of size 1073741824 bytes (1.0 GiB)
root@ubuntu-s-3vcpu-1gb-nyc3-01:~# sudo chmod 600 /swapfile
root@ubuntu-s-3vcpu-1gb-nyc3-01:~# sudo mkswap /swapfile
mkswap: error: swap area needs to be at least 40 KiB

```

**Comment by Zelecktor** [comment]
Finally it was not nessesary, finally i could compile 😄 static and non static.
Here is the static output:

```
root@ubuntu-s-3vcpu-1gb-nyc3-04:~/xmrigCC/buildstatic# cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a -DWITH_CC_SERVER=OFF -DWITH_HTTPD=OFF
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmrigCC/buildstatic
root@ubuntu-s-3vcpu-1gb-nyc3-04:~/xmrigCC/buildstatic# make
Scanning dependencies of target xmrig_os_dependencies
[  1%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
[  5%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_unix.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_unix.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/log/SysLog.cpp.o
[ 14%] Linking CXX static library libxmrig_os_dependencies.a
[ 14%] Built target xmrig_os_dependencies
Scanning dependencies of target xmrig_common
[ 16%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
[ 27%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.o
[ 32%] Linking CXX static library libxmrig_common.a
[ 32%] Built target xmrig_common
Scanning dependencies of target xmrig_cpuid
[ 34%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_cpuid.cpp.o
[ 36%] Linking CXX static library libxmrig_cpuid.a
[ 36%] Built target xmrig_cpuid
Scanning dependencies of target xmrig_cc_common
[ 38%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.o
[ 41%] Linking CXX static library libxmrig_cc_common.a
[ 41%] Built target xmrig_cc_common
Scanning dependencies of target cpuid
[ 43%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[ 45%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[ 47%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[ 49%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 50%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
[ 52%] Linking C static library libcpuid.a
[ 52%] Built target cpuid
Scanning dependencies of target xmrigMiner
[ 54%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.o
/root/xmrigCC/src/App.cpp: In static member function âstatic void App::onCommandReceived(uv_async_t*)â:
/root/xmrigCC/src/App.cpp:268:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
[ 58%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Client.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Job.cpp.o
[ 61%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Network.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/DonateStrategy.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 67%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/SubmitResult.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrigMiner.dir/src/Summary.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/MultiWorker.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Handle.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Hashrate.cpp.o
[ 78%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Worker.cpp.o
[ 80%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Workers.cpp.o
[ 81%] Building CXX object CMakeFiles/xmrigMiner.dir/src/xmrig.cpp.o
[ 83%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_keccak.c.o
[ 85%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_groestl.c.o
[ 87%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_blake256.c.o
[ 89%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_jh.c.o
[ 90%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_skein.c.o
[ 92%] Building CXX object CMakeFiles/xmrigMiner.dir/src/crypto/CryptoNight.cpp.o
[ 94%] Building CXX object CMakeFiles/xmrigMiner.dir/src/cc/CCClient.cpp.o
[ 96%] Linking CXX executable xmrigMiner
[ 96%] Built target xmrigMiner
Scanning dependencies of target xmrigDaemon
[ 98%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
[100%] Linking CXX executable xmrigDaemon
[100%] Built target xmrigDaemon

```
Now i got these files:
```
CMakeCache.txt        libxmrig_common.a           src
CMakeFiles            libxmrig_cpuid.a            test
cmake_install.cmake   libxmrig_os_dependencies.a  xmrigDaemon
libxmrig_cc_common.a  Makefile                    xmrigMiner

```

To use the files `xmrigDaemon` and `xmrigMiner` in my linux machine that i cloudn't build (debian 8).
As the issue before, if a drop those files on the root it will say "Permision deneid" or "command not found".
How i make the exactly .tar.gz file to install on my other machine?

Thanks in advance

**Comment by Bendr0id** [comment]
tar cfvz archiv.tar.gz xmrigDaemon xmrigMiner

Am 24.02.2018 07:06 schrieb Zelecktor <notifications@github.com>:

Finally it was not nessesary, finally i could compile 😄 static and non static.
Here is the static output:

root@ubuntu-s-3vcpu-1gb-nyc3-04:~/xmrigCC/buildstatic# cmake .. -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a -DWITH_CC_SERVER=OFF -DWITH_HTTPD=OFF
-- The C compiler identification is GNU 7.1.0
-- The CXX compiler identification is GNU 7.1.0
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /root/xmrigCC/buildstatic
root@ubuntu-s-3vcpu-1gb-nyc3-04:~/xmrigCC/buildstatic# make
Scanning dependencies of target xmrig_os_dependencies
[  1%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/Api.cpp.o
[  3%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/api/ApiState.cpp.o
[  5%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/App_unix.cpp.o
[  7%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Cpu_unix.cpp.o
[  9%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Mem_unix.cpp.o
[ 10%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/Platform_unix.cpp.o
[ 12%] Building CXX object CMakeFiles/xmrig_os_dependencies.dir/src/log/SysLog.cpp.o
[ 14%] Linking CXX static library libxmrig_os_dependencies.a
[ 14%] Built target xmrig_os_dependencies
Scanning dependencies of target xmrig_common
[ 16%] Building CXX object CMakeFiles/xmrig_common.dir/src/Console.cpp.o
[ 18%] Building CXX object CMakeFiles/xmrig_common.dir/src/Mem.cpp.o
[ 20%] Building CXX object CMakeFiles/xmrig_common.dir/src/net/Url.cpp.o
[ 21%] Building CXX object CMakeFiles/xmrig_common.dir/src/Options.cpp.o
[ 23%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/ConsoleLog.cpp.o
[ 25%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/FileLog.cpp.o
[ 27%] Building CXX object CMakeFiles/xmrig_common.dir/src/log/Log.cpp.o
[ 29%] Building CXX object CMakeFiles/xmrig_common.dir/src/Platform.cpp.o
[ 30%] Building CXX object CMakeFiles/xmrig_common.dir/src/Cpu.cpp.o
[ 32%] Linking CXX static library libxmrig_common.a
[ 32%] Built target xmrig_common
Scanning dependencies of target xmrig_cpuid
[ 34%] Building CXX object CMakeFiles/xmrig_cpuid.dir/src/Cpu_cpuid.cpp.o
[ 36%] Linking CXX static library libxmrig_cpuid.a
[ 36%] Built target xmrig_cpuid
Scanning dependencies of target xmrig_cc_common
[ 38%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ControlCommand.cpp.o
[ 40%] Building CXX object CMakeFiles/xmrig_cc_common.dir/src/cc/ClientStatus.cpp.o
[ 41%] Linking CXX static library libxmrig_cc_common.a
[ 41%] Built target xmrig_cc_common
Scanning dependencies of target cpuid
[ 43%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/cpuid_main.c.o
[ 45%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/asm-bits.c.o
[ 47%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_amd.c.o
[ 49%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/recog_intel.c.o
[ 50%] Building C object src/3rdparty/libcpuid/CMakeFiles/cpuid.dir/libcpuid_util.c.o
[ 52%] Linking C static library libcpuid.a
[ 52%] Built target cpuid
Scanning dependencies of target xmrigMiner
[ 54%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.o
[ 56%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.o
/root/xmrigCC/src/App.cpp: In static member function âstatic void App::onCommandReceived(uv_async_t*)â:
/root/xmrigCC/src/App.cpp:268:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
                                                                            ^
[ 58%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Client.cpp.o
[ 60%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Job.cpp.o
[ 61%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/Network.cpp.o
[ 63%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/DonateStrategy.cpp.o
[ 65%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/FailoverStrategy.cpp.o
[ 67%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/strategies/SinglePoolStrategy.cpp.o
[ 69%] Building CXX object CMakeFiles/xmrigMiner.dir/src/net/SubmitResult.cpp.o
[ 70%] Building CXX object CMakeFiles/xmrigMiner.dir/src/Summary.cpp.o
[ 72%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/MultiWorker.cpp.o
[ 74%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Handle.cpp.o
[ 76%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Hashrate.cpp.o
[ 78%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Worker.cpp.o
[ 80%] Building CXX object CMakeFiles/xmrigMiner.dir/src/workers/Workers.cpp.o
[ 81%] Building CXX object CMakeFiles/xmrigMiner.dir/src/xmrig.cpp.o
[ 83%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_keccak.c.o
[ 85%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_groestl.c.o
[ 87%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_blake256.c.o
[ 89%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_jh.c.o
[ 90%] Building C object CMakeFiles/xmrigMiner.dir/src/crypto/c_skein.c.o
[ 92%] Building CXX object CMakeFiles/xmrigMiner.dir/src/crypto/CryptoNight.cpp.o
[ 94%] Building CXX object CMakeFiles/xmrigMiner.dir/src/cc/CCClient.cpp.o
[ 96%] Linking CXX executable xmrigMiner
[ 96%] Built target xmrigMiner
Scanning dependencies of target xmrigDaemon
[ 98%] Building CXX object CMakeFiles/xmrigDaemon.dir/src/cc/XMRigd.cpp.o
[100%] Linking CXX executable xmrigDaemon
[100%] Built target xmrigDaemon



Now i got these files:

CMakeCache.txt        libxmrig_common.a           src
CMakeFiles            libxmrig_cpuid.a            test
cmake_install.cmake   libxmrig_os_dependencies.a  xmrigDaemon
libxmrig_cc_common.a  Makefile                    xmrigMiner



To use the files xmrigDaemon and xmrigMiner in my linux machine that i cloudn't build (debian 8).
As the issue before, if a drop those files on the root it will say "Permision deneid" or "command not found".
How i make the exactly .tar.gz file to install on my other machine?

Thanks in advance

**Comment by Bendr0id** [comment]
Make sure you set the execute flag to the miner on the debian machine. It can be lost during compression/extraction.

`chmod +x xmrig*`

`chown youruser:youruser xmrig*`

`./xmrigDaemon` should execute the miner then.

**Comment by Bendr0id** [comment]
Can we close this?

**Comment by Zelecktor** [comment]
Yes, thanks very much
