### ISSUE TITLE
prevent server from resuming the client

### ISSUE THREAD

**Issue by untoreh** [Bendr0id/xmrigCC#47]
I think it should be configurable on the server whether to force resume the miner or not, if the miner itself has been paused manually it might not be a desirable behaviour

**Comment by Bendr0id** [comment]
Current behavior for all commands is that server overrules everything. The client is currently not able to differentiate between local and remote commands. 

When there is a clean way to implement which is applicable for everybody, i'll implement it.

**Comment by untoreh** [comment]
ok, I am currently using this patch as a quick fix on `cc/CCClient.cpp` hope it didn't break anything 

```diff
151a152
> 	bool skipCommand;
155c156,157
<                 if (!Workers::isEnabled()) {
---
> 		skipCommand = true;
>                 /*if (!Workers::isEnabled()) {
157c159
<                 }
---
>                 }*/
173,174c175,176
< 
<             m_self->m_async->data = reinterpret_cast<void*>(controlCommand.getCommand());
---
> 	if (!skipCommand) {
>     		m_self->m_async->data = reinterpret_cast<void*>(controlCommand.getCommand());
175a178
> 	}

```

**Comment by Zelecktor** [comment]
Thank you @untoreh thats what im looking for. But have some problems,
Already i changed those lines exactly as you did (add and remove) but CC-client still is sending the command.

![captura](https://user-images.githubusercontent.com/19712343/36734709-146cd73a-1bb3-11e8-805e-8f062f9c1b2d.PNG)

Can you upload your full `CCClient.cpp` ?

**Comment by untoreh** [comment]
save the quoted text into a file and use the `patch` command like this: 
```bash 
patch /path/to/CCClient.cpp patchfile
```
However, as suggested by @Bendr0id, you can avoid recompiling if you just send the stop request directly to the server. Although i would say that it is kinda redundant to call the server to issue a local command, also the client<->server does keep the tcp connection alive even if you set a very low update rate so there is also some extra latency

**Comment by Bendr0id** [comment]
@Zelecktor you can use xmrigCC also without the server, maybe thats what you want.

**Comment by Zelecktor** [comment]
@Bendr0id, im using with the server, remember that i compiled on linux first to set server and linux workers, now im on windows machines, but i use windows for other purposes, not for mining only, Usually i start mining when i leave the PC idle.

@untoreh I used the patch command, the CC-client is fixed but still have problem with the CC-client command, its like "hidden" because after pause, inmidiatly it resume mining.

![captura](https://user-images.githubusercontent.com/19712343/36738964-8d74601c-1bbd-11e8-8acf-5bc03f1ae9c4.PNG)

**Comment by untoreh** [comment]
@Zelecktor have you checked cpu usage? maybe stats take a while to update, i didn't test it on windows but on linux works fine

**Comment by Zelecktor** [comment]
@untoreh Yes, (something strange), "P" keyboard works on linux.

On windows works for about 2seconds, then it resume mining. CPU usage is like 0% after pause, 2 seconds after that 90% (means that its mining)
