### ISSUE TITLE
Linux Shared Hosting CC Server

### ISSUE THREAD

**Issue by yangsystem** [Bendr0id/xmrigCC#48]
Is there a way to install the ccserver on a linux shared hosting. My provider uses CloudLinux.
Or should I make a request and move to a windows based server?

**Comment by Bendr0id** [comment]
I don't see a problem on installing it on CloudLinux, do you tried it already?

**Comment by yangsystem** [comment]
I have access with putty but I don't know what to do.
Can you give me a list of what should I do.

**Comment by Bendr0id** [comment]
Follow these steps:

https://github.com/Bendr0id/xmrigCC/wiki/Build-RedHat%5CCentOS

**Comment by yangsystem** [comment]
it seem's I don't have yum installed there. I will use a windows machine for the pre-build version.
