### ISSUE TITLE
Ability to delete config files in Dashboard

### ISSUE THREAD

**Issue by yangsystem** [Bendr0id/xmrigCC#53]
Can you put a button to delete config file from server?
I don't want to remote desktop every time to delete in case I change the name of a worker.
Now I can see the old miner as offline, I want to delete him from list from the dashboard

**Comment by Bendr0id** [comment]
Has nothing to do with the config..

It keeps a list in memory of all connected/disconnected miners. Will think about a flush list button.

Would that be sufficient?

Workaround for now would be to restart XMRigCCServer.

Am 27.02.2018 14:24 schrieb yangsystem <notifications@github.com>:

Can you put a button to delete config file from server?
I don't want to remote desktop every time to delete in case I change the name of a worker.
Now I can see the old miner as offline, I want to delete him from list from the dashboard

**Comment by yangsystem** [comment]
Yes it will be OK.
10Q

**Comment by Bendr0id** [comment]
Implemented in 1.6.5+
