### ISSUE TITLE
Please update Ubuntu build how to

### ISSUE THREAD

**Issue by kensagle** [Bendr0id/xmrigCC#56]
package libssl-dev is required now in version 1.5 on Ubuntu and likely other distros, but I only checked Ubuntu.

Thanks

**Comment by Bendr0id** [comment]
Yes. It's in progress. For static build there is even more todo. Some parts I already added to CentOS. But it will take some days. Sorry

Am 04.03.2018 01:18 schrieb kensagle <notifications@github.com>:

package libssl-dev is required now in version 1.5 on Ubuntu and likely other distros, but I only checked Ubuntu.

Thanks

**Comment by Bendr0id** [comment]
Updated.
