### ISSUE TITLE
Add Guide for tuning XMRigCC to Wiki

### ISSUE THREAD

**Issue by pharmecis** [Bendr0id/xmrigCC#57]
I have tried all day to get xmrigCC to out perform xmr-stak but I have not been successful.  I have learned how to set the features properly I believe with masks but I can't reach numbers advertised in the benchmarks.

Specifically, the E7-4820 processor is rated at 2200H/s stock.  My E7-4870's I can't get above 1400H/s stock, 1500 something tuned.  I just tried 3 different E7 processors, all in multiple cpu configs (double or quad) and I simply can't get them to perform as well as xmr-stak.

I sooooooooo want to use all the nifty dandy features for management.  It's everything I've been looking for but I'm seeing 10 to 30% performance deltas and instability in hash rates.

Please tell me I'm stupid and show me the way!

**Comment by Bendr0id** [comment]
I have to update the whole wiki articles about building, and TLS. About multihash there is already a quite good part in the readme.md on the main page.

Most of the benchmarks I've received from users, but I'll try to help you. Please try to contact me on telegram. @bendr0id

Am 04.03.2018 06:07 schrieb pharmecis <notifications@github.com>:

I have tried all day to get xmrigCC to out perform xmr-stak but I have not been successful. I have learned how to set the features properly I believe with masks but I can't reach numbers advertised in the benchmarks.

Specifically, the E7-4820 processor is rated at 2200H/s stock. My E7-4870's I can't get above 1400H/s stock, 1500 something tuned. I just tried 3 different E7 processors, all in multiple cpu configs (double or quad) and I simply can't get them to perform as well as xmr-stak.

I sooooooooo want to use all the nifty dandy features for management. It's everything I've been looking for but I'm seeing 10 to 30% performance deltas and instability in hash rates.

Please tell me I'm stupid and show me the way!

**Comment by untoreh** [comment]
@pharmecis  I see the E7-4820/70 have per core cache xx70 has 3MB and xx20 has 2.25, which means you have to use mhf 1, and 10/8 threads on cryptonight. The 4870 would be utilized more effectively with cryptonight-lite since you can put mhf 3 and use all the cache of each core. 
Thread affinity just put 0xFF for 8 and 0x3FF for 10 since you are going to use all the cores. 
Mhf mask is not important because the cores have equal cache so default is fine.

**Comment by Bendr0id** [comment]
@pharmecis Please try 1.7.0 to see if the instability is gone. Should be already gone with 1.6.5 aswell due to refactoring in memory/hugepages allocation. If problem persist please create a new ticket.
