### ISSUE TITLE
Feature request : Request JSON body minify

### ISSUE THREAD

**Issue by vov4uk** [Bendr0id/xmrigCC#6]
Average request length about ~600 bytes 
But if use short names: for example  current_status -> c_s
and round decimals to 2 digits "hashrate_highest":76.9971126082
It can save a lot of traffic.

Thank you,
Volodymyr.

**Comment by Bendr0id** [comment]
Sounds like a micro optimization.

if you reduce from 600bytes to 500bytes by removing the readability, it's  worthless.

Better use gzip compression for request. 

But 600byte every 10s is 200kb/hour. Is it really worth to spend effort into that?

**Comment by vov4uk** [comment]
Actually main purpose of this request was to make lower load to server. But I agree with you, readability more important than 100 bytes. I'll close task
