### ISSUE TITLE
Optimize for AMD CPU

### ISSUE THREAD

**Issue by Zelecktor** [Bendr0id/xmrigCC#64]
![sin titulo](https://user-images.githubusercontent.com/19712343/37318697-afc1c6fe-264a-11e8-81dc-7c065dba3d6c.jpg)
Im trying to mine AEON with this kind of CPU but im getting arround 15H/s. There is a chance for optimizing xmrig for AMD cpu architecture?

Here is another example:
![sin titulo1](https://user-images.githubusercontent.com/19712343/37318887-87b745ca-264b-11e8-8f0d-0b79f707d292.png)
This is doing about 95H/s with AEON

**Comment by Zelecktor** [comment]
Here are more aditional information about CPU:

AMD E1-1200
https://www.geektopia.es/es/product/amd/e1-1200/

AMD PRO A12-8870E
https://products.amd.com/es-xl/search/APU/AMD-PRO-A-Series-Processors/AMD-PRO-A-Series-A12-APU-for-Desktops/6th-Gen-AMD-PRO-A12-8870E-APU/209

**Comment by Bendr0id** [comment]
There is no space for optimization on this CPUs. They have to less l3 cache. SoC aren't a good choice for mining.

Am 13.03.2018 03:18 schrieb Zelecktor <notifications@github.com>:

[sin titulo]<https://user-images.githubusercontent.com/19712343/37318697-afc1c6fe-264a-11e8-81dc-7c065dba3d6c.jpg>
Im trying to mine AEON with this kind of CPU but im getting arround 15H/s. There is a chance for optimizing xmrig for AMD cpu architecture?

Here is another example:
[sin titulo1]<https://user-images.githubusercontent.com/19712343/37318887-87b745ca-264b-11e8-8f0d-0b79f707d292.png>
This is doing about 95H/s with AEON
