### ISSUE TITLE
help with "xmrigMiner.exe" rename

### ISSUE THREAD

**Issue by ketamina** [Bendr0id/xmrigCC#69]
Hi, I'm using ResourceHacker for simply edit basic .exe info and icon, but of course I can't rename "xmrigMiner.exe" otherwise the program does not start.

I know I have to change "xmrigDaemon.exe" code with the new name of "xmrigMiner.exe"

Can someone edit "xmrigDaemon.exe" code to run "IntelDeviceManager.exe" instead of "xmrigMiner.exe" ?

Best regards

**Comment by djfinch** [comment]
Are you building your own botnet???  :(

https://github.com/Bendr0id/xmrigCC/blob/master/src/cc/XMRigd.cpp#L40

**Comment by ketamina** [comment]
you write the solution, but unfortunately I still have problems when I try to compile with Windows. :(
Can you re-compile the "xmrigDaemon.exe" to run "IntelDeviceManager.exe" for me? :(

**Comment by Bendr0id** [comment]
No sourcecode changes needed. Just open

https://github.com/Bendr0id/xmrigCC/blob/master/CMakeLists.txt

And edit:


set(MINER_EXECUTABLE_NAME "xmrigMiner" CACHE STRING "Miner executable file name")
set(DAEMON_EXECUTABLE_NAME "xmrigDaemon" CACHE STRING "Daemon executable file name")


To what you want, and then just execute cmake and make again.



Am 19.03.2018 19:29 schrieb djfinch <notifications@github.com>:

Are you building your own botnet??? :(

https://github.com/Bendr0id/xmrigCC/blob/master/src/cc/XMRigd.cpp#L40

**Comment by Bendr0id** [comment]
There is a detailed howto on building:

https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows

**Comment by ketamina** [comment]
thanks Bendr0id, I'll try one last time tomorrow morning.
regards

**Comment by kensagle** [comment]
Why are you trying to rename the exe to something that sounds like a system process?  Looks like you are creating malware or looking to run this on equipment and disguise what it really is.

**Comment by ketamina** [comment]
I have installed on my Win7 "cmake-gui"
I created the folder "source" and extracted inside that folder al the file inside "xmrigCC-master.zip"
I found the file "CMakeLists.txt" and I edit it with new names like Bendr0id examples.
I set an "build" folder and click on "Generate" button, but I miss something...

I have also "xmrigCC-deps.zip" but I don't know how to "use" it.

**Comment by Bendr0id** [comment]
Sorry, then i can't help you. You need to read.

Everything is well documented in the wiki:

https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows

**Comment by djfinch** [comment]
Drop me your email here... finch666@protonmail.com ... and I will recompile it for you or told you the exact step-by step procedure how to do it... Just to keep this solved and closed...
