### ISSUE TITLE
Memory leak in CCServer?

### ISSUE THREAD

**Issue by ruptse** [Bendr0id/xmrigCC#7]
CCserver process getting killed after running for some time due to "Out of memory". Possible memory leak or auto flush needed with CCserver? (Ubuntu 16.04 with 1GB RAM)

**Comment by Bendr0id** [comment]
I haven't heard about that before. I know a few ppl using it for quite a long time without restart (weeks). But of course could be. Which version of XmrigCCServer are you using and how many miners are connected to it? On which resource you think there is a auto flush needed?

**Comment by Bendr0id** [comment]
Sounds like a leak, yes.
I'll do tomorrow some tests, take core dumps and see if i can find it.
Could also be in the libraries i use.

**Comment by Bendr0id** [comment]
Ok, found it. I couldn't wait until tomorrow. 

The "big" one was a stupid strdup :man_facepalming: 

There is a smal one left, connected to "basic auth", which is only used when dashboard is accessing the server, which is most likely not that frequent like miners hammer it.

I'll hoefully find that one soon.

**Comment by rekonnected** [comment]
Thank you. I was trying to figure out what was going on for so long. I just resorted to SSHing into my VPS and restarting it every time it died.

**Comment by Bendr0id** [comment]
Sorry about that and thx for finding this out! 

Will be in the next release. 

For those wo compile on their own, just pull latest master and make.

@ruptse if your donation level is > 0 -> keep it :grin: i appreciate and it keeps me loving this project.

**Comment by ruptse** [comment]
Great ... thanks for promptly fixing! Will try it out.
