### ISSUE TITLE
1.5.1 quits with no error on 32 bit ARM running in Termux

### ISSUE THREAD

**Issue by kensagle** [Bendr0id/xmrigCC#71]
I upgraded all my devices to 1.5.1, they all compiled fine.  When starting the daemon it just quits with no error.  If I run the 1.5.0 version it runs fine.  My devices that have 64-bit ARM work fine on 1.5.1.  This is all via termux in android.  I will try to get more details.  Anyone else have this issue?

All my computers running Linux run fine on 1.5.1 as well.

**Comment by Bendr0id** [comment]
Could be similar issues XMRig stock has. I tried it on my ARMv8 vps and also on my armv7a rpi with x64. I need to install a 32bit os on it to test. Can take some time..

**Comment by Bendr0id** [comment]
Sorry for lates response. Could you try again with the latest master?

**Comment by kensagle** [comment]
Sorry for the delay.  1.5.5 was working with some random crashes.  I have not tried 1.6 yet.

**Comment by kensagle** [comment]
1.6.0 worked, closing
