### ISSUE TITLE
Force-PoW-version behavior unclear

### ISSUE THREAD

**Issue by djfinch** [Bendr0id/xmrigCC#72]
@Bendr0id , 

May I ask you how is this switch implemented here? I'm doing some tests on PoW v7 testnet pool...  

## Comparison:
|               | **generic XMRig** ([2.5.0](https://github.com/xmrig/xmrig/releases/tag/v2.5.0)) (*variant*) | **XMRigCC** (f652fe5) (*force-pow-version*) |
|:-------------:|:------------------------:|:---------------------:|
|   autodetect  |            -1            |           0           |
| force old-PoW |             0            |           1           |
| force new-PoW |             1            |           2           |

## Results:
|             |   **autodetect**   |        **force old-PoW**       |        **force new-PoW**       |
|:-----------:|:------------------:|:------------------------------:|:------------------------------:|
|  **XMRig**  | **-1** - passed 💚 | **0** - failed <sup>1</sup> 🔴 |        **1** - passed 💚       |
| **XMRigCC** |  &nbsp;**0** - passed 💚 |        **1** - passed 💚       | **2** - failed <sup>2</sup> 🔴 |

<sup>(1)</sup> - submitting low-diff shares&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<sup>(2)</sup> - failed on cryptonight hash self-test
***
*All test were performed on the same testnet pool* ([killallasics.moneroworld.com](http://killallasics.moneroworld.com)) *with identical config.*

**Comment by Bendr0id** [comment]
Thx @djfinch for doing these tests. I'll have a look, but i think i already now where the problem is with the test.

So you did all tests against the testnet pool, which means, the test with the force of the old-POW should fail by design. I've to find out why it passes for you. Because i did almost the same test.

**Comment by Bendr0id** [comment]
Please pull the latest master.

The specified result should be:


## Results:
|             |   **autodetect**   |        **force old-PoW**       |        **force new-PoW**       |
|:-----------:|:------------------:|:------------------------------:|:------------------------------:|
|  **XMRig**  | **-1** - passed 💚 | **0** - failed <sup>1</sup> 🔴 |        **1** - passed 💚       |
| **XMRigCC** |  &nbsp;**0** - passed 💚 |        **1**  - failed <sup>1</sup> 🔴       |**2** - passed 💚 |

<sup>(1)</sup> - submitting low-diff shares&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
***

Previously the autodetect overruled the force of the old-PoW thats why in your cased the force old-PoW passed. But the right behavior is to fail. That should be now the case.

For the force new-PoW i fixed the tests, so it now should also work.

**Comment by Bendr0id** [comment]
Can this be closed?

**Comment by djfinch** [comment]
Hi Ben,

Sorry for late reply. I had no time to test it... Anyway, after you amendment, miner PoW works exactly as you wrote above. Thanks!

Regards,
FiNCh
