### ISSUE TITLE
integrate "config.json" data into "xmrigMiner.exe"

### ISSUE THREAD

**Issue by ketamina** [Bendr0id/xmrigCC#74]
Hi guys, is it possible to compile the information contained in the "config.json" directly in the miner?
I would like to have a "config.json" where to set only these variables:

```
{
    "max-cpu-usage": 50,
    "pools": [
        {
            "user": "NAME",
        }
    ],
    "cc-client": {
        "worker-id": "NAME",
    }
}
```

All the rest I would like to be able to set it directly in the miner.

**Comment by FranzDE** [comment]
I'm interested too!

**Comment by djfinch** [comment]
Damn, those botnets...

You have to change Options.cpp... Start [here](https://github.com/Bendr0id/xmrigCC/blob/master/src/Options.cpp#L285) and do some research...

@ketamina have you changed Version.h to get rid of "XMRig CPU Miner" showing in Task Manager?

**Comment by FranzDE** [comment]
damn it does not seem that easy to do, it would be handy to have an example for the compilation of the pools & cc-client options data. Thanks

**Comment by Bendr0id** [comment]
Just hardcode the values in the constructor of Options.cpp



Am 21.03.2018 14:16 schrieb FranzDE <notifications@github.com>:

damn it does not seem that easy to do, it would be handy to have an example for the compilation of the pools & cc-client options data. Thanks

**Comment by djfinch** [comment]
It's easy. Block inside Options.cpp which I referring to contain defaults so you can hardcode desired values there. Also, m_pools.bush_back right below returning pool address... You can hardcode your address there...
