### ISSUE TITLE
You can support Xmr-stak?

### ISSUE THREAD

**Issue by m1911** [Bendr0id/xmrigCC#8]
You can support Xmr-stak?

**Comment by Bendr0id** [comment]
XMR-Stak has completly different architecture. It's ofcourse possible but it will need some time.

**Comment by m1911** [comment]
Can't support it lately?
@Bendr0id

**Comment by Bendr0id** [comment]
What do you mean? Right now there is no plan for doing this. Whats your point?

**Comment by m1911** [comment]
I'm just looking forward to your support.

**Comment by Bendr0id** [comment]
Higher prio is currently on adding ssl and numa support.

**Comment by Bendr0id** [comment]
Let's keep it open. Maybe there is some time soon, to dig into it.

**Comment by m1911** [comment]
OK.

**Comment by rekonnected** [comment]
Just a note, if you do end up supporting XMR-STAK, then you'll likely want to change the name of the project from XMRig-CC to XMR-CC or something like that.

**Comment by m1911** [comment]
Xmrig hashrate is not very stable.

**Comment by Bendr0id** [comment]
? Could it be that you mixing things up? XMRig has fluctuating hash rates like any other miner (XMR-Stak included) has.

If there is a concrete problem with logs and proof feel free to share. Nobody else is complaining so far.

**Comment by rekonnected** [comment]
I mean, I see my hashrates fluctuate but it's intentional. I run miners in the background with 0 priority so it'll give up CPU time.

**Comment by m1911** [comment]
Hashrate between 1480-1520 beats cannot stabilize at 1500.

**Comment by rekonnected** [comment]
A fluctuation average of only ~20 is negligible. It'll cause no issues.

**Comment by Bendr0id** [comment]
That is absolutely normal. You'll have that on any miner.

It's impossible to synchronize the hashrates. It's just a numer which isnt 100% accurate, it's influenced by many factors and doesn't tell you anything. 

The only thing which counts is the payout on the pool. Thats something you should measure. Not the hashrate on the miner. It's just an indikator, not a real hashrate.

**Comment by djfinch** [comment]
The main reason to support XMR-STAK is not XMRig's #rate stability but their unified miner which also support CUDA and OpenCL devices. This will be major advantage to C&C graphic rigs running XMR-STAK...
