### ISSUE TITLE
Queue config updates

### ISSUE THREAD

**Issue by redispade** [Bendr0id/xmrigCC#80]
Hi, I have a question, and possibly a feature suggestion. If I want to queue config updates as soon as the client connects, while being absolutely sure that I have fully working config files in my cc server dir, I just need to comment this line right? From what I understood, this line publishes the local config to the CC at work start. Is this correct? (If I manage to get a working code with checks for all exceptions I will submit it back to you if you need it)
Thank you very much
https://github.com/Bendr0id/xmrigCC/blob/128cd248beead2439ba3c99203d4abe14cb1a508/src/cc/CCClient.cpp#L314

**Comment by Bendr0id** [comment]
Yes by commenting this line of code you disable the publish on startup. You still can fetch the latest config of the miner by pulling it via dashboard.

**Comment by Bendr0id** [comment]
An option is implemented for this in version 1.7.x
