### ISSUE TITLE
how to change file name "xmrigMiner.exe"

### ISSUE THREAD

**Issue by b1oodyrevenge** [Bendr0id/xmrigCC#87]
as soon as the change stops working

**Comment by Bendr0id** [comment]
In CMakeLists.txt change:

set(MINER_EXECUTABLE_NAME "xmrigMiner" CACHE STRING "Miner executable file name")
set(DAEMON_EXECUTABLE_NAME "xmrigDaemon" CACHE STRING "Daemon executable file name")

to whatever you want.

Then:
```
cmake .
make -j
```

**Comment by Bendr0id** [comment]
Thought you're already compiling the code. 

There is no easier way to change the miner name than i explained.

**Comment by b1oodyrevenge** [comment]
will this manual work? [](https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md)

**Comment by b1oodyrevenge** [comment]
https://github.com/fireice-uk/xmr-stak/blob/master/doc/compile_Windows.md

**Comment by Bendr0id** [comment]
No it's a complete different application. Are you serious?

https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows

**Comment by b1oodyrevenge** [comment]
I just didn't find your Windows compilation instructions first. according to your instructions, I have made changes to the file names, thank you!
