### ISSUE TITLE
 error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 1756816846** [Bendr0id/xmrigCC#9]
Hello,I want use static compile this
`cmake . -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DWITH_LIBCPUID=OFF -DWITH_AEON=OFF -DWITH_HTTPD=OFF -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a`
But I execuce make:
`Scanning dependencies of target xmrigMiner
[  2%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/Api.cpp.o
[  4%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/ApiState.cpp.o
[  6%] Building CXX object CMakeFiles/xmrigMiner.dir/src/api/NetworkState.cpp.o
[  8%] Building CXX object CMakeFiles/xmrigMiner.dir/src/App.cpp.o
/root/桌面/pool/xmrigCC/src/App.cpp: In static member function ‘static void App::onCommandReceived(uv_async_t*)’:
/root/桌面/pool/xmrigCC/src/App.cpp:250:76: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     auto command = reinterpret_cast<ControlCommand::Command &> (async->data);
`
Start file:
./xmrigMiner: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory
What should i do now？

**Comment by Bendr0id** [comment]
Do you compiled it before non static? Make sure that you delete CMakeCache.txt before.

**Comment by 1756816846** [comment]
cmake . -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7 -DWITH_LIBCPUID=OFF -DWITH_AEON=OFF -DWITH_HTTPD=OFF -DUV_LIBRARY=/usr/lib/x86_64-linux-gnu/libuv.a
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/gcc-7
-- Check for working C compiler: /usr/bin/gcc-7 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-7
-- Check for working CXX compiler: /usr/bin/g++-7 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found UV: /usr/lib/x86_64-linux-gnu/libuv.a  
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Found mhd: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Desktop/pool/xmrigCC

**Comment by 1756816846** [comment]
but:
./xmrigMiner: error while loading shared libraries: libmicrohttpd.so.12: cannot open shared object file: No such file or directory

**Comment by Bendr0id** [comment]
make clean && make

Why aren't you just using the static build? It's exactly the same.

https://github.com/Bendr0id/xmrigCC/releases/download/1.2.2/xmrigCC-1.2.2_miner_only-gcc7-linux-static-x64.tar.gz

**Comment by 1756816846** [comment]
server test:
./xmrigDaemon: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./xmrigDaemon)

**Comment by Bendr0id** [comment]
Currently no clue. Which os? I'll setup a VM and find it out.

**Comment by 1756816846** [comment]
CentOS release 6.4 (Final)

**Comment by Bendr0id** [comment]
Could you please try this:

https://github.com/Bendr0id/xmrigCC/releases/download/1.2.2/xmrigCC-1.2.2_miner_only-gcc7-centos6-static-x64.tar.gz

**Comment by 1756816846** [comment]
Thank you，I now test the success
