### ISSUE TITLE
Unable to instal in linux,boost package needs update

### ISSUE THREAD

**Issue by adiangga** [Bendr0id/xmrigCC#91]
I can not install in linux,it said that my boost package is older. installed boost version is 1.58 and required is 1.62.
I have install 1.64 but my boost version didn't changed. Please help me

**Comment by Bendr0id** [comment]
Please build boost like described in my wiki.

https://github.com/Bendr0id/xmrigCC/wiki

Am 17.04.2018 11:54 schrieb adiangga <notifications@github.com>:

I can not install in linux,it said that my boost package is older. installed boost version is 1.58 and required is 1.62.
I have install 1.64 but my boost version didn't changed. Please help me

**Comment by Bendr0id** [comment]
Can this be closed?

**Comment by adiangga** [comment]
Ok,case closed
