### ISSUE TITLE
Xmrig-proxyCC

### ISSUE THREAD

**Issue by adiangga** [Bendr0id/xmrigCC#92]
Please develop xmrig-proxyCC,where we can change pool by web based,and change algo will overide miner algo, and proxy that support cn-heavy, unlike original xmrig proxy that unsupport cb-heavy. Thank you

**Comment by ariadarkkkis** [comment]
+1 and tls support for windows

**Comment by xmrig** [comment]
@adiangga but xmrig-proxy supports cn-heavy and cn-ipbc you was create issue in wrong repository and looks like not follow the link.

Technically the proxy supports change pools on fly, but still missing web interface for it.
Thank you.

**Comment by ariadarkkkis** [comment]
@xmrig still missing tls feature for both windows and linux. im using windows and I cant use HAproxy to handle tls. Do you know any alternatives for windows server?

**Comment by xmrig** [comment]
Oh I was sure haproxy available for Windows too.

**Comment by ariadarkkkis** [comment]
@xmrig can you provide a link? I didnt find one. I think I can use nginx as an alternative for passing tls connections to proxy
