### ISSUE TITLE
XMRigCCServer 

### ISSUE THREAD

**Issue by dh47** [Bendr0id/xmrigCC#93]
Where did XMRigCCServer go?  Seems like its only in the Windows builds?

**Comment by Bendr0id** [comment]
For server you need to build dynamic. It's not possible to build the server in a static way.

Check the wiki:

https://github.com/Bendr0id/xmrigCC/wiki/Build-Debian%5CUbuntu


Am 17.04.2018 13:22 schrieb dh47 <notifications@github.com>:

Where did XMRigCCServer go? Seems like its only in the Windows builds?

**Comment by dh47** [comment]
Bugger I tried that and have been having issues with the Boost part of the guide.

**Comment by Bendr0id** [comment]
What is exactly the problem with building boost?

**Comment by dh47** [comment]
Compiling and making boost is no issue it's coming to the part where I have to use it with cmake.

It was reported to be created here:
```
/root/boost_1_67_0
/root/boost_1_67_0/stage/lib
```

So how would I go about changing this?
`cmake . -DBOOST_ROOT=~/boost_1_67_0`

**Comment by Bendr0id** [comment]
cmake . -DBOOST_ROOT=/root/boost_1_67_0

**Comment by dh47** [comment]
Oh I was replacing the "DBOOST_ROOT" thanks that worked.
