### ISSUE TITLE
compile error with 64-bit MSYS2 and new XMrigCC 1.6.0

### ISSUE THREAD

**Issue by FranzDE** [Bendr0id/xmrigCC#94]
I followed the guide given here: https://github.com/Bendr0id/xmrigCC/wiki/Build-Windows#64-bit-build-with-msys2

guide code:
`cmake . -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libuv\x64\include" -DUV_LIBRARY="c:\xmrigCC-deps\gcc\libuv\x64\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\lib\libmicrohttpd.a" -DOPENSSL_INCLUDE_DIR="c:\xmrigCC-deps\gcc\openssl\x64\include" -DOPENSSL_ROOT_DIR="c:\xmrigCC-deps\gcc\openssl\x64\lib"  -DBOOST_ROOT="C:\boost_1_67_0" -DBoost_SYSTEM_LIBRARY="C:\boost_1_67_0\stage\lib\libboost_system-mgw72-mt-x64-1_67.a"`

SOLVED:

I suggest you change the guide like this: (with the default folder of boost installation)
`cmake . -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libuv\x64\include" -DUV_LIBRARY="c:\xmrigCC-deps\gcc\libuv\x64\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\lib\libmicrohttpd.a" -DOPENSSL_INCLUDE_DIR="c:\xmrigCC-deps\gcc\openssl\x64\include" -DOPENSSL_ROOT_DIR="c:\xmrigCC-deps\gcc\openssl\x64\lib"  -DBOOST_ROOT="C:\msys64\home\user\boost_1_67_0" -DBoost_SYSTEM_LIBRARY="C:\msys64\home\user\boost_1_67_0\stage\lib\libboost_system-mgw72-mt-x64-1_67.a"`

**Comment by Bendr0id** [comment]
Don't get the problem..?
The documentation says:
**Replace the Boost paths with the path where you builded Boost.**

I builded it on C:\ and seems that you builded in your home directory. Or did i miss something?

Anyways, feel free to modify the Wiki, everyone has the right todo that.

**Comment by FranzDE** [comment]
sorry Bendr0id.

now it works, but it does not make me the build of the miner.
only the loader and the miner.

I try to do it again with the sources

**Comment by Bendr0id** [comment]
```
make[2]: ***  Nessuna regola per generare l'obiettivo "C:\msys64\home\user\boost_1_67_0\stage\lib\libboost_system-mgw72-mt-x64-1_67.a", necessario per "xmrigMiner.exe".  Arresto.
make[2]: *** Attesa per i processi non terminati....
```

make sure that this file: `C:\msys64\home\user\boost_1_67_0\stage\lib\libboost_system-mgw72-mt-x64-1_67.a` realy exists and the naming is correct.

**Comment by Bendr0id** [comment]
You have to build it of course. 

It should exist after you did the ./b2

Please check this folder `C:\msys64\home\user\boost_1_67_0\stage\lib` for its content.

**Comment by FranzDE** [comment]
I was in the wrong folder.
Now I see the files but they have different names:
```
user@user-net MINGW64 ~/boost_1_67_0/stage/lib
$ ls
libboost_system-mgw73-mt-d-x32-1_67.a  libboost_system-mgw73-mt-x32-1_67.a
libboost_system-mgw73-mt-d-x64-1_67.a  libboost_system-mgw73-mt-x64-1_67.a

user@user-net MINGW64 ~/boost_1_67_0/stage/lib
$
```

I guess I need to rename the file **libboost_system-mgw73-mt-x64-1_67.a**
to: **libboost_system-mgw72-mt-x64-1_67.a**

Or simple I can change the last part of the code:
`cmake . -G "Unix Makefiles" -DUV_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libuv\x64\include" -DUV_LIBRARY="c:\xmrigCC-deps\gcc\libuv\x64\lib\libuv.a" -DMHD_INCLUDE_DIR="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\include" -DMHD_LIBRARY="c:\xmrigCC-deps\gcc\libmicrohttpd\x64\lib\libmicrohttpd.a" -DOPENSSL_INCLUDE_DIR="c:\xmrigCC-deps\gcc\openssl\x64\include" -DOPENSSL_ROOT_DIR="c:\xmrigCC-deps\gcc\openssl\x64\lib" -DBOOST_ROOT="C:\msys64\home\user\boost_1_67_0" -DBoost_SYSTEM_LIBRARY="C:\msys64\home\user\boost_1_67_0\stage\lib\libboost_system-mgw72-mt-x64-1_67.a"`
Right?

**Comment by Bendr0id** [comment]
Exactly. i was using mingw72 and you have mingw73.
```
-DBoost_SYSTEM_LIBRARY="C:\msys64\home\user\boost_1_67_0\stage\lib\libboost_system-mgw73-mt-x64-1_67.a"
```
Thats why i wrote in the build instructions: 

**Replace the Boost paths with the path where you builded Boost.**

**Comment by FranzDE** [comment]
now it works perfect!
sorry for the trouble and thanks for the support!
