### ISSUE TITLE
32bit for 1.6.0

### ISSUE THREAD

**Issue by adiangga** [Bendr0id/xmrigCC#95]
Please build xmrigCC windows version for x86 or 32bit, i have miner that run on OS x86

**Comment by Bendr0id** [comment]
Building is not the problem. I have a version, but for whatever reason it crashs on start on my 64bit vm.

I need to debug, will take some time.

Am 17.04.2018 19:28 schrieb adiangga <notifications@github.com>:

Please build xmrigCC windows version for x86 or 32bit, i have miner that run on OS x86

**Comment by Bendr0id** [comment]
Check latest Release 1.6.2
