### ISSUE TITLE
1.6.0 boost issues on termux

### ISSUE THREAD

**Issue by kensagle** [Bendr0id/xmrigCC#96]
I am having issues compiling 1.6.0 in termux on android.  Getting some boot errors.  I will dig into this later to see what I can find out.  Wanted to see of anyone already fixed or working on this.

**Comment by kensagle** [comment]
Boost errors, not boot errors.

**Comment by Bendr0id** [comment]
You need to build boost for android. It's a new dependency

**Comment by kensagle** [comment]
Thanks, I installed boost and boost-dev, but the version available in termux is 1.65.1.  I will look into installing the 1.67 version and see if I can get it working.  Is there anything in 1.67 that is required, or should 1.65 work if I can get all the correct paths and libraries?  Thanks for responding.

**Comment by Bendr0id** [comment]
1.65 is also good, i think. But anyways, you can boost on your own. It's not that hard.

**Comment by kensagle** [comment]
I got it to work by using the default boost 1.65.1 that is packaged for termux.  I edited the CMakeLists.txt file as follows.  I didn't add the boost root path to cmake.

set(Boost_USE_STATIC_RUNTIME OFF)
set(Boost_USE_STATIC_LIBS OFF)

I will test a little more later tonight.  I was playing with a lot of settings so want to make sure that is really the edits that made it work.  I will update another device later with only these edits to be certain.

**Comment by Bendr0id** [comment]
If you do dynamic build you have install boost on every device before you can use the miner. But if you do that it works of course.

Am 18.04.2018 18:34 schrieb kensagle <notifications@github.com>:

I got it to work by using the default boost 1.65.1 that is packaged for termux. I edited the CMakeLists.txt file as follows. I didn't add the boost root path to cmake.

set(Boost_USE_STATIC_RUNTIME OFF)
set(Boost_USE_STATIC_LIBS OFF)

I will test a little more later tonight. I was playing with a lot of settings so want to make sure that is really the edits that made it work. I will update another device later with only these edits to be certain.

**Comment by kensagle** [comment]
I am good with that, I may try to get it to work with a static build if I get some free time.  Thanks for the info.
