### ISSUE TITLE
error in cc client

### ISSUE THREAD

**Issue by adiangga** [Bendr0id/xmrigCC#97]
i got error like below when run in ubuntu. in windows everything ok
 [CC-Client] error: unable to performRequest POST -> http://52.77.219.36:3335/client/setClientStatus?clientId=ubuntu231

**Comment by Bendr0id** [comment]
This is definitely a local issue. Make sure you can access that ip from the Ubuntu machine and that the token is correct. Do you see an error in the server log?

Am 18.04.2018 06:19 schrieb adiangga <notifications@github.com>:

i got error like below when run in ubuntu. in windows everything ok
[CC-Client] error: unable to performRequest POST -> http://52.77.219.36:3335/client/setClientStatus?clientId=ubuntu231

**Comment by Bendr0id** [comment]
Is this solved?

**Comment by Bendr0id** [comment]
No response. Unable to reproduce.
